//HintName: Rootless.JsAccessible.g.cs
// <auto-generated/>
#pragma warning disable CS0219, CS8073, CS8600, CS8601, CS8602, CS8603, CS8604, CS8618, CS8619, CS8620, CS8621, CS8622, CS8625

namespace Jint.Generated
{
    internal static class JsAccessible_Rootless
    {
        internal static void Register()
        {
            global::Jint.Runtime.Interop.JsAccessibleRegistry.Register(typeof(global::Rootless), AddMembers);
        }

        private static void AddMembers(global::Jint.Runtime.Interop.JsAccessibleTypeBuilder builder)
        {
            builder.AddMember(
                "Score",
                typeof(int),
                Read_Score,
                ReadBoxed_Score,
                Write_Score,
                WriteBoxed_Score);
        }

        private static global::Jint.Native.JsValue Read_Score(object target)
            => (global::Jint.Native.JsValue) ((global::Rootless) target).Score;

        private static object ReadBoxed_Score(object target)
            => ((global::Rootless) target).Score;

        private static bool Write_Score(object target, global::Jint.Native.JsValue value)
        {
            if (!(value is global::Jint.Native.JsNumber))
            {
                return false;
            }

            var d = value.AsNumber();
            if (double.IsNaN(d) || double.IsInfinity(d) || global::System.Math.Floor(d) != d || d < -2147483648D || d > 2147483647D)
            {
                return false;
            }

            ((global::Rootless) target).Score = (int) d;
            return true;
        }

        private static void WriteBoxed_Score(object target, object value)
            => ((global::Rootless) target).Score = value is null ? default(int) : (int) value;
    }
}
