//HintName: Sample.Model.JsAccessible.g.cs
// <auto-generated/>
#nullable enable
#pragma warning disable CS0219, CS8073, CS8600, CS8601, CS8602, CS8603, CS8604, CS8618, CS8625

namespace Jint.Generated
{
    internal static class JsAccessible_Sample_Model
    {
        internal static void Register()
        {
            global::Jint.Runtime.Interop.JsAccessibleRegistry.Register(typeof(global::Sample.Model), AddMembers);
        }

        private static void AddMembers(global::Jint.Runtime.Interop.JsAccessibleTypeBuilder builder)
        {
            builder.AddMember(
                "Name",
                typeof(string),
                Read_Name,
                ReadBoxed_Name,
                Write_Name,
                WriteBoxed_Name);
        }

        private static global::Jint.Native.JsValue Read_Name(object target)
            => (global::Jint.Native.JsValue) ((global::Sample.Model) target).Name;

        private static object? ReadBoxed_Name(object target)
            => ((global::Sample.Model) target).Name;

        private static bool Write_Name(object target, global::Jint.Native.JsValue value)
        {
            if (!(value is global::Jint.Native.JsString))
            {
                return false;
            }

            ((global::Sample.Model) target).Name = value.ToString();
            return true;
        }

        private static void WriteBoxed_Name(object target, object? value)
            => ((global::Sample.Model) target).Name = (string) value!;
    }
}
