//HintName: Sample.Model.JsAccessible.g.cs
// <auto-generated/>
#pragma warning disable CS0219, CS8073, CS8600, CS8601, CS8602, CS8603, CS8604, CS8618, CS8619, CS8620, CS8621, CS8622, CS8625

namespace Jint.Generated
{
    internal static class JsAccessible_Sample_Model
    {
        internal static void Register()
        {
            global::Jint.Runtime.Interop.JsAccessibleRegistry.Register(typeof(global::Sample.Model), AddMembers);
        }

        private static void AddMembers(global::Jint.Runtime.Interop.JsAccessibleTypeBuilder builder)
        {
            builder.AddMember(
                "Score",
                typeof(int),
                Read_Score,
                ReadBoxed_Score,
                Write_Score,
                WriteBoxed_Score);
            builder.AddMember(
                "Ticks",
                typeof(long),
                Read_Ticks,
                ReadBoxed_Ticks,
                Write_Ticks,
                WriteBoxed_Ticks);
            builder.AddMember(
                "Ratio",
                typeof(double),
                Read_Ratio,
                ReadBoxed_Ratio,
                Write_Ratio,
                WriteBoxed_Ratio);
            builder.AddMember(
                "Active",
                typeof(bool),
                Read_Active,
                ReadBoxed_Active,
                Write_Active,
                WriteBoxed_Active);
            builder.AddMember(
                "Name",
                typeof(string),
                Read_Name,
                ReadBoxed_Name,
                Write_Name,
                WriteBoxed_Name);
            builder.AddMember(
                "Payload",
                typeof(global::Jint.Native.JsValue),
                Read_Payload,
                ReadBoxed_Payload,
                Write_Payload,
                WriteBoxed_Payload);
            builder.AddMember(
                "Tag",
                typeof(global::Jint.Native.JsString),
                Read_Tag,
                ReadBoxed_Tag,
                null,
                WriteBoxed_Tag);
            builder.AddMember(
                "Tags",
                typeof(string[]),
                null,
                ReadBoxed_Tags,
                null,
                WriteBoxed_Tags);
        }

        private static global::Jint.Native.JsValue Read_Score(object target)
            => (global::Jint.Native.JsValue) ((global::Sample.Model) target).Score;

        private static object ReadBoxed_Score(object target)
            => ((global::Sample.Model) target).Score;

        private static bool Write_Score(object target, global::Jint.Native.JsValue value)
        {
            if (!(value is global::Jint.Native.JsNumber))
            {
                return false;
            }

            var d = value.AsNumber();
            if (double.IsNaN(d) || double.IsInfinity(d) || global::System.Math.Floor(d) != d || d < -2147483648D || d > 2147483647D)
            {
                return false;
            }

            ((global::Sample.Model) target).Score = (int) d;
            return true;
        }

        private static void WriteBoxed_Score(object target, object value)
            => ((global::Sample.Model) target).Score = value is null ? default(int) : (int) value;

        private static global::Jint.Native.JsValue Read_Ticks(object target)
            => (global::Jint.Native.JsValue) ((global::Sample.Model) target).Ticks;

        private static object ReadBoxed_Ticks(object target)
            => ((global::Sample.Model) target).Ticks;

        private static bool Write_Ticks(object target, global::Jint.Native.JsValue value)
        {
            if (!(value is global::Jint.Native.JsNumber))
            {
                return false;
            }

            var d = value.AsNumber();
            if (double.IsNaN(d) || double.IsInfinity(d) || global::System.Math.Floor(d) != d || d < -9223372036854775808D || d >= 9223372036854775808D)
            {
                return false;
            }

            ((global::Sample.Model) target).Ticks = (long) d;
            return true;
        }

        private static void WriteBoxed_Ticks(object target, object value)
            => ((global::Sample.Model) target).Ticks = value is null ? default(long) : (long) value;

        private static global::Jint.Native.JsValue Read_Ratio(object target)
            => (global::Jint.Native.JsValue) ((global::Sample.Model) target).Ratio;

        private static object ReadBoxed_Ratio(object target)
            => ((global::Sample.Model) target).Ratio;

        private static bool Write_Ratio(object target, global::Jint.Native.JsValue value)
        {
            if (!(value is global::Jint.Native.JsNumber))
            {
                return false;
            }

            var d = value.AsNumber();
            ((global::Sample.Model) target).Ratio = d;
            return true;
        }

        private static void WriteBoxed_Ratio(object target, object value)
            => ((global::Sample.Model) target).Ratio = value is null ? default(double) : (double) value;

        private static global::Jint.Native.JsValue Read_Active(object target)
            => (global::Jint.Native.JsValue) ((global::Sample.Model) target).Active;

        private static object ReadBoxed_Active(object target)
            => ((global::Sample.Model) target).Active;

        private static bool Write_Active(object target, global::Jint.Native.JsValue value)
        {
            if (!(value is global::Jint.Native.JsBoolean))
            {
                return false;
            }

            ((global::Sample.Model) target).Active = value.AsBoolean();
            return true;
        }

        private static void WriteBoxed_Active(object target, object value)
            => ((global::Sample.Model) target).Active = value is null ? default(bool) : (bool) value;

        private static global::Jint.Native.JsValue Read_Name(object target)
            => (global::Jint.Native.JsValue) ((global::Sample.Model) target).Name;

        private static object ReadBoxed_Name(object target)
            => ((global::Sample.Model) target).Name;

        private static bool Write_Name(object target, global::Jint.Native.JsValue value)
        {
            if (!(value is global::Jint.Native.JsString))
            {
                return false;
            }

            ((global::Sample.Model) target).Name = value.ToString();
            return true;
        }

        private static void WriteBoxed_Name(object target, object value)
            => ((global::Sample.Model) target).Name = (string) value;

        private static global::Jint.Native.JsValue Read_Payload(object target)
            => ((global::Sample.Model) target).Payload ?? (global::Jint.Native.JsValue) global::Jint.Native.JsValue.Null;

        private static object ReadBoxed_Payload(object target)
            => ((global::Sample.Model) target).Payload;

        private static bool Write_Payload(object target, global::Jint.Native.JsValue value)
        {
            ((global::Sample.Model) target).Payload = value;
            return true;
        }

        private static void WriteBoxed_Payload(object target, object value)
            => ((global::Sample.Model) target).Payload = (global::Jint.Native.JsValue) value;

        private static global::Jint.Native.JsValue Read_Tag(object target)
            => ((global::Sample.Model) target).Tag ?? (global::Jint.Native.JsValue) global::Jint.Native.JsValue.Null;

        private static object ReadBoxed_Tag(object target)
            => ((global::Sample.Model) target).Tag;

        private static void WriteBoxed_Tag(object target, object value)
            => ((global::Sample.Model) target).Tag = (global::Jint.Native.JsString) value;

        private static object ReadBoxed_Tags(object target)
            => ((global::Sample.Model) target).Tags;

        private static void WriteBoxed_Tags(object target, object value)
            => ((global::Sample.Model) target).Tags = (string[]) value;
    }
}
