//HintName: Sample.Model.JsAccessible.g.cs
// <auto-generated/>
#nullable enable
#pragma warning disable CS0219, CS8073, CS8600, CS8601, CS8602, CS8603, CS8604, CS8618, CS8625

namespace Jint.Generated
{
    internal static class JsAccessible_Sample_Model
    {
        internal static void Register()
        {
            global::Jint.Runtime.Interop.JsAccessibleRegistry.Register(typeof(global::Sample.Model), AddMembers);
        }

        private static void AddMembers(global::Jint.Runtime.Interop.JsAccessibleTypeBuilder builder)
        {
            builder.AddMethod("Echo", 1, Invoke_Echo);
            builder.AddMethod("Touch", 1, Invoke_Touch);
            builder.AddMethod("Count", 0, Invoke_Count);
            builder.AddMethod("Describe", 2, Invoke_Describe);
        }

        private static global::Jint.Native.JsValue Invoke_Echo(global::Jint.Engine engine, object target, global::Jint.Native.JsValue[] arguments)
        {
            var result = ((global::Sample.Model) target).Echo(arguments[0]);
            return global::Jint.Native.JsValue.FromObjectWithType(engine, result, typeof(global::Jint.Native.JsValue));
        }

        private static global::Jint.Native.JsValue Invoke_Touch(global::Jint.Engine engine, object target, global::Jint.Native.JsValue[] arguments)
        {
            ((global::Sample.Model) target).Touch(arguments[0]);
            return global::Jint.Native.JsValue.FromObjectWithType(engine, null, typeof(void));
        }

        private static global::Jint.Native.JsValue Invoke_Count(global::Jint.Engine engine, object target, global::Jint.Native.JsValue[] arguments)
        {
            var result = ((global::Sample.Model) target).Count();
            return global::Jint.Native.JsValue.FromObjectWithType(engine, result, typeof(int));
        }

        private static global::Jint.Native.JsValue Invoke_Describe(global::Jint.Engine engine, object target, global::Jint.Native.JsValue[] arguments)
        {
            var result = ((global::Sample.Model) target).Describe(arguments[0], arguments[1]);
            return global::Jint.Native.JsValue.FromObjectWithType(engine, result, typeof(string));
        }
    }
}
