//HintName: JsAccessibleRegistration.g.cs
// <auto-generated/>
#pragma warning disable CS0219, CS8073, CS8600, CS8601, CS8602, CS8603, CS8604, CS8618, CS8619, CS8620, CS8621, CS8622, CS8625

namespace JintSourceGenTests
{
    /// <summary>
    /// Registers this assembly's [Jint.JsAccessible] types with the Jint engine. Call it once, during
    /// startup and before the first engine resolves a member of an annotated type; repeat calls do nothing.
    /// </summary>
    public static class JsAccessibleRegistration
    {
        private static int _registered;

        public static void RegisterAll()
        {
            if (global::System.Threading.Interlocked.Exchange(ref _registered, 1) != 0)
            {
                return;
            }

            global::Jint.Generated.JsAccessible_Sample_Outer_Player.Register();
            global::Jint.Generated.JsAccessible_Sample_Player.Register();
        }
    }
}
