//HintName: Sample.Model.JsAccessible.g.cs
// <auto-generated/>
#nullable enable
#pragma warning disable CS0219, CS8073, CS8600, CS8601, CS8602, CS8603, CS8604, CS8618, CS8625

namespace Jint.Generated
{
    internal static class JsAccessible_Sample_Model
    {
        internal static void Register()
        {
            global::Jint.Runtime.Interop.JsAccessibleRegistry.Register(typeof(global::Sample.Model), AddMembers);
        }

        private static void AddMembers(global::Jint.Runtime.Interop.JsAccessibleTypeBuilder builder)
        {
            builder.AddMember(
                "First",
                typeof(int),
                Read_First,
                ReadBoxed_First,
                Write_First,
                WriteBoxed_First);
            builder.AddMember(
                "Second",
                typeof(int),
                Read_Second,
                ReadBoxed_Second,
                Write_Second,
                WriteBoxed_Second);
        }

        private static global::Jint.Native.JsValue Read_First(object target)
            => (global::Jint.Native.JsValue) ((global::Sample.Model) target).First;

        private static object? ReadBoxed_First(object target)
            => ((global::Sample.Model) target).First;

        private static bool Write_First(object target, global::Jint.Native.JsValue value)
        {
            if (!(value is global::Jint.Native.JsNumber))
            {
                return false;
            }

            var d = global::Jint.JsValueExtensions.AsNumber(value);
            if (double.IsNaN(d) || double.IsInfinity(d) || global::System.Math.Floor(d) != d || d < -2147483648D || d > 2147483647D)
            {
                return false;
            }

            ((global::Sample.Model) target).First = (int) d;
            return true;
        }

        private static void WriteBoxed_First(object target, object? value)
            => ((global::Sample.Model) target).First = value is null ? default(int) : (int) value!;

        private static global::Jint.Native.JsValue Read_Second(object target)
            => (global::Jint.Native.JsValue) ((global::Sample.Model) target).Second;

        private static object? ReadBoxed_Second(object target)
            => ((global::Sample.Model) target).Second;

        private static bool Write_Second(object target, global::Jint.Native.JsValue value)
        {
            if (!(value is global::Jint.Native.JsNumber))
            {
                return false;
            }

            var d = global::Jint.JsValueExtensions.AsNumber(value);
            if (double.IsNaN(d) || double.IsInfinity(d) || global::System.Math.Floor(d) != d || d < -2147483648D || d > 2147483647D)
            {
                return false;
            }

            ((global::Sample.Model) target).Second = (int) d;
            return true;
        }

        private static void WriteBoxed_Second(object target, object? value)
            => ((global::Sample.Model) target).Second = value is null ? default(int) : (int) value!;
    }
}
