//HintName: Sample.Model.JsAccessible.g.cs
// <auto-generated/>
#nullable enable
#pragma warning disable CS0219, CS8073, CS8600, CS8601, CS8602, CS8603, CS8604, CS8618, CS8625

namespace Jint.Generated
{
    internal static class JsAccessible_Sample_Model
    {
        internal static void Register()
        {
            global::Jint.Runtime.Interop.JsAccessibleRegistry.Register(typeof(global::Sample.Model), AddMembers);
        }

        private static void AddMembers(global::Jint.Runtime.Interop.JsAccessibleTypeBuilder builder)
        {
            builder.AddMember(
                "Kept",
                typeof(int),
                Read_Kept,
                ReadBoxed_Kept,
                Write_Kept,
                WriteBoxed_Kept);
        }

        private static global::Jint.Native.JsValue Read_Kept(object target)
            => (global::Jint.Native.JsValue) ((global::Sample.Model) target).Kept;

        private static object? ReadBoxed_Kept(object target)
            => ((global::Sample.Model) target).Kept;

        private static bool Write_Kept(object target, global::Jint.Native.JsValue value)
        {
            if (!(value is global::Jint.Native.JsNumber))
            {
                return false;
            }

            var d = value.AsNumber();
            if (double.IsNaN(d) || double.IsInfinity(d) || global::System.Math.Floor(d) != d || d < -2147483648D || d > 2147483647D)
            {
                return false;
            }

            ((global::Sample.Model) target).Kept = (int) d;
            return true;
        }

        private static void WriteBoxed_Kept(object target, object? value)
            => ((global::Sample.Model) target).Kept = value is null ? default(int) : (int) value!;
    }
}
