//HintName: Sample.Model.JsAccessible.g.cs
// <auto-generated/>
#pragma warning disable CS0219, CS8073, CS8600, CS8601, CS8602, CS8603, CS8604, CS8618, CS8619, CS8620, CS8621, CS8622, CS8625

namespace Jint.Generated
{
    internal static class JsAccessible_Sample_Model
    {
        internal static void Register()
        {
            global::Jint.Runtime.Interop.JsAccessibleRegistry.Register(typeof(global::Sample.Model), AddMembers);
        }

        private static void AddMembers(global::Jint.Runtime.Interop.JsAccessibleTypeBuilder builder)
        {
            builder.AddMember(
                "GetOnly",
                typeof(int),
                Read_GetOnly,
                ReadBoxed_GetOnly,
                null,
                null);
            builder.AddMember(
                "SetOnly",
                typeof(int),
                null,
                null,
                Write_SetOnly,
                WriteBoxed_SetOnly);
            builder.AddMember(
                "Field",
                typeof(int),
                Read_Field,
                ReadBoxed_Field,
                Write_Field,
                WriteBoxed_Field);
            builder.AddMember(
                "ReadOnlyField",
                typeof(string),
                Read_ReadOnlyField,
                ReadBoxed_ReadOnlyField,
                null,
                null);
        }

        private static global::Jint.Native.JsValue Read_GetOnly(object target)
            => (global::Jint.Native.JsValue) ((global::Sample.Model) target).GetOnly;

        private static object ReadBoxed_GetOnly(object target)
            => ((global::Sample.Model) target).GetOnly;

        private static bool Write_SetOnly(object target, global::Jint.Native.JsValue value)
        {
            if (!(value is global::Jint.Native.JsNumber))
            {
                return false;
            }

            var d = value.AsNumber();
            if (double.IsNaN(d) || double.IsInfinity(d) || global::System.Math.Floor(d) != d || d < -2147483648D || d > 2147483647D)
            {
                return false;
            }

            ((global::Sample.Model) target).SetOnly = (int) d;
            return true;
        }

        private static void WriteBoxed_SetOnly(object target, object value)
            => ((global::Sample.Model) target).SetOnly = value is null ? default(int) : (int) value;

        private static global::Jint.Native.JsValue Read_Field(object target)
            => (global::Jint.Native.JsValue) ((global::Sample.Model) target).Field;

        private static object ReadBoxed_Field(object target)
            => ((global::Sample.Model) target).Field;

        private static bool Write_Field(object target, global::Jint.Native.JsValue value)
        {
            if (!(value is global::Jint.Native.JsNumber))
            {
                return false;
            }

            var d = value.AsNumber();
            if (double.IsNaN(d) || double.IsInfinity(d) || global::System.Math.Floor(d) != d || d < -2147483648D || d > 2147483647D)
            {
                return false;
            }

            ((global::Sample.Model) target).Field = (int) d;
            return true;
        }

        private static void WriteBoxed_Field(object target, object value)
            => ((global::Sample.Model) target).Field = value is null ? default(int) : (int) value;

        private static global::Jint.Native.JsValue Read_ReadOnlyField(object target)
            => (global::Jint.Native.JsValue) ((global::Sample.Model) target).ReadOnlyField;

        private static object ReadBoxed_ReadOnlyField(object target)
            => ((global::Sample.Model) target).ReadOnlyField;
    }
}
