//HintName: Sample.Foo.g.cs
// <auto-generated/>
#nullable enable

namespace Sample;

internal sealed partial class Foo
{
    /// <summary>Generated property registration. Call from <c>Initialize()</c>.</summary>
    private void CreateProperties_Generated()
    {
        var properties = new global::Jint.Collections.HybridDictionary<global::Jint.Runtime.Descriptors.PropertyDescriptor>(1, checkExistingKeys: false);
        properties["concat"] = new global::Jint.Runtime.Descriptors.Specialized.LazyPropertyDescriptor<Foo>(this, static host => new __FooFunction(host, __FooFunction.Slot.Concat), global::Jint.Runtime.Descriptors.PropertyFlag.NonEnumerable);
        SetProperties(properties);
    }

    private sealed class __FooFunction : global::Jint.Native.Function.Function
    {
        internal enum Slot : ushort
        {
            Concat,
        }

        private readonly Foo _host;
        private readonly Slot _slot;

        internal __FooFunction(Foo host, Slot slot)
            : base(host.Engine, host.Engine.Realm, GetName(slot))
        {
            _host = host;
            _slot = slot;
            _prototype = host.Engine.Realm.Intrinsics.Function.PrototypeObject;
            _length = new global::Jint.Runtime.Descriptors.PropertyDescriptor(global::Jint.Native.JsNumber.Create(GetLength(slot)), global::Jint.Runtime.Descriptors.PropertyFlag.Configurable);
        }

        protected internal override global::Jint.Native.JsValue Call(global::Jint.Native.JsValue thisObject, global::Jint.Native.JsValue[] arguments)
        {
            switch (_slot)
            {
                case Slot.Concat: return Foo.Concat(thisObject, global::Jint.Runtime.Arguments.At(arguments, 0), new global::System.ReadOnlySpan<global::Jint.Native.JsValue>(arguments, global::System.Math.Min(1, arguments.Length), global::System.Math.Max(0, arguments.Length - 1)));
                default: throw UnknownSlot(_slot);
            }
        }

        private static global::Jint.Native.JsString GetName(Slot slot)
        {
            switch (slot)
            {
                case Slot.Concat: return global::Jint.Native.JsString.CachedCreate("concat");
                default: throw UnknownSlot(slot);
            }
        }

        private static int GetLength(Slot slot)
        {
            switch (slot)
            {
                case Slot.Concat: return 0;
                default: throw UnknownSlot(slot);
            }
        }

        private static global::System.InvalidOperationException UnknownSlot(Slot slot)
            => new global::System.InvalidOperationException("Unknown slot " + slot + " — generator/runtime mismatch.");
    }
}
