//HintName: Sample.Foo.g.cs
// <auto-generated/>
#nullable enable

namespace Sample;

internal sealed partial class Foo
{
    /// <summary>Generated property registration. Call from <c>Initialize()</c>.</summary>
    private void CreateProperties_Generated()
    {
        // no [JsFunction] or [JsProperty] members
    }

    /// <summary>Generated symbol-keyed registration. Call from <c>Initialize()</c>.</summary>
    private void CreateSymbols_Generated()
    {
        var symbols = new global::Jint.Collections.DictionarySlim<global::Jint.Native.JsSymbol, global::Jint.Runtime.Descriptors.PropertyDescriptor>(1);
        symbols[global::Jint.Native.Symbol.GlobalSymbolRegistry.ToStringTag] = new global::Jint.Runtime.Descriptors.PropertyDescriptor(Foo.Tag, global::Jint.Runtime.Descriptors.PropertyFlag.Configurable);
        SetSymbols(symbols);
    }
}
