//HintName: Sample.Foo.g.cs
// <auto-generated/>
#nullable enable

namespace Sample;

internal sealed partial class Foo
{
    /// <summary>Generated property registration. Call from <c>Initialize()</c>.</summary>
    private void CreateProperties_Generated()
    {
        var properties = new global::Jint.Collections.HybridDictionary<global::Jint.Runtime.Descriptors.PropertyDescriptor>(5, checkExistingKeys: false);
        properties["byteAt"] = new global::Jint.Runtime.Descriptors.Specialized.LazyPropertyDescriptor<Foo>(this, static host => new __FooFunction(host, __FooFunction.Slot.ByteAt), global::Jint.Runtime.Descriptors.PropertyFlag.NonEnumerable);
        properties["echo"] = new global::Jint.Runtime.Descriptors.Specialized.LazyPropertyDescriptor<Foo>(this, static host => new __FooFunction(host, __FooFunction.Slot.Echo), global::Jint.Runtime.Descriptors.PropertyFlag.NonEnumerable);
        properties["echoJs"] = new global::Jint.Runtime.Descriptors.Specialized.LazyPropertyDescriptor<Foo>(this, static host => new __FooFunction(host, __FooFunction.Slot.EchoJs), global::Jint.Runtime.Descriptors.PropertyFlag.NonEnumerable);
        properties["trunc"] = new global::Jint.Runtime.Descriptors.Specialized.LazyPropertyDescriptor<Foo>(this, static host => new __FooFunction(host, __FooFunction.Slot.Trunc), global::Jint.Runtime.Descriptors.PropertyFlag.NonEnumerable);
        properties["wrap"] = new global::Jint.Runtime.Descriptors.Specialized.LazyPropertyDescriptor<Foo>(this, static host => new __FooFunction(host, __FooFunction.Slot.Wrap), global::Jint.Runtime.Descriptors.PropertyFlag.NonEnumerable);
        SetProperties(properties);
    }

    private sealed class __FooFunction : global::Jint.Native.Function.Function
    {
        internal enum Slot : ushort
        {
            ByteAt,
            Echo,
            EchoJs,
            Trunc,
            Wrap,
        }

        private readonly Foo _host;
        private readonly Slot _slot;

        internal __FooFunction(Foo host, Slot slot)
            : base(host.Engine, host.Engine.Realm, GetName(slot))
        {
            _host = host;
            _slot = slot;
            _prototype = host.Engine.Realm.Intrinsics.Function.PrototypeObject;
            _length = new global::Jint.Runtime.Descriptors.PropertyDescriptor(global::Jint.Native.JsNumber.Create(GetLength(slot)), global::Jint.Runtime.Descriptors.PropertyFlag.Configurable);
        }

        protected internal override global::Jint.Native.JsValue Call(global::Jint.Native.JsValue thisObject, global::Jint.Native.JsValue[] arguments)
        {
            switch (_slot)
            {
                case Slot.ByteAt: return Foo.ByteAt(thisObject, global::Jint.Runtime.TypeConverter.ToLength(global::Jint.Runtime.Arguments.At(arguments, 0)));
                case Slot.Echo: return Foo.Echo(thisObject, global::Jint.Runtime.TypeConverter.ToString(global::Jint.Runtime.Arguments.At(arguments, 0)));
                case Slot.EchoJs: return Foo.EchoJs(thisObject, global::Jint.Runtime.TypeConverter.ToJsString(global::Jint.Runtime.Arguments.At(arguments, 0)));
                case Slot.Trunc: return Foo.Trunc(thisObject, global::Jint.Runtime.TypeConverter.ToInteger(global::Jint.Runtime.Arguments.At(arguments, 0)));
                case Slot.Wrap: return Foo.Wrap(thisObject, global::Jint.Runtime.TypeConverter.ToObject(_realm, global::Jint.Runtime.Arguments.At(arguments, 0)));
                default: throw UnknownSlot(_slot);
            }
        }

        private static global::Jint.Native.JsString GetName(Slot slot)
        {
            switch (slot)
            {
                case Slot.ByteAt: return global::Jint.Native.JsString.CachedCreate("byteAt");
                case Slot.Echo: return global::Jint.Native.JsString.CachedCreate("echo");
                case Slot.EchoJs: return global::Jint.Native.JsString.CachedCreate("echoJs");
                case Slot.Trunc: return global::Jint.Native.JsString.CachedCreate("trunc");
                case Slot.Wrap: return global::Jint.Native.JsString.CachedCreate("wrap");
                default: throw UnknownSlot(slot);
            }
        }

        private static int GetLength(Slot slot)
        {
            switch (slot)
            {
                case Slot.ByteAt: return 1;
                case Slot.Echo: return 1;
                case Slot.EchoJs: return 1;
                case Slot.Trunc: return 1;
                case Slot.Wrap: return 1;
                default: throw UnknownSlot(slot);
            }
        }

        private static global::System.InvalidOperationException UnknownSlot(Slot slot)
            => new global::System.InvalidOperationException("Unknown slot " + slot + " — generator/runtime mismatch.");
    }
}
