//HintName: Sample.Foo.g.cs
// <auto-generated/>
#nullable enable

namespace Sample;

internal sealed partial class Foo
{
    /// <summary>Generated property registration. Call from <c>Initialize()</c>.</summary>
    private void CreateProperties_Generated()
    {
        var properties = new global::Jint.Collections.HybridDictionary<global::Jint.Runtime.Descriptors.PropertyDescriptor>(3, checkExistingKeys: false);
        properties["MutableTag"] = new global::Jint.Runtime.Descriptors.PropertyDescriptor(Foo.MutableTag, global::Jint.Runtime.Descriptors.PropertyFlag.NonEnumerable);
        properties["PI"] = new global::Jint.Runtime.Descriptors.PropertyDescriptor(Foo.PiValue, global::Jint.Runtime.Descriptors.PropertyFlag.AllForbidden);
        properties["answer"] = new global::Jint.Runtime.Descriptors.PropertyDescriptor(Foo.Answer, global::Jint.Runtime.Descriptors.PropertyFlag.AllForbidden);
        SetProperties(properties);
    }
}
