//HintName: JintAttributes.g.cs
// <auto-generated/>
#nullable enable

namespace Jint;

[global::System.AttributeUsage(global::System.AttributeTargets.Class)]
[global::System.Diagnostics.Conditional("JINT_SOURCE_GENERATORS")]
internal sealed class JsObjectAttribute : global::System.Attribute
{
}

[global::System.AttributeUsage(global::System.AttributeTargets.Method)]
[global::System.Diagnostics.Conditional("JINT_SOURCE_GENERATORS")]
internal sealed class JsFunctionAttribute : global::System.Attribute
{
    public string? Name { get; set; }
    public int Length { get; set; } = -1;
}

[global::System.AttributeUsage(global::System.AttributeTargets.Field | global::System.AttributeTargets.Property)]
[global::System.Diagnostics.Conditional("JINT_SOURCE_GENERATORS")]
internal sealed class JsPropertyAttribute : global::System.Attribute
{
    public string? Name { get; set; }
    public global::Jint.Runtime.Descriptors.PropertyFlag Flags { get; set; } = global::Jint.Runtime.Descriptors.PropertyFlag.AllForbidden;
}

[global::System.AttributeUsage(global::System.AttributeTargets.Parameter)]
[global::System.Diagnostics.Conditional("JINT_SOURCE_GENERATORS")]
internal sealed class RestAttribute : global::System.Attribute
{
}

// Marks a parameter as receiving the result of a TypeConverter.ToXxx coercion of arguments[N].
// The CLR parameter type must match the converter's return type (double for ToNumber, int for
// ToInt32, uint for ToUint32). The generator emits the conversion at the dispatcher boundary.

[global::System.AttributeUsage(global::System.AttributeTargets.Parameter)]
[global::System.Diagnostics.Conditional("JINT_SOURCE_GENERATORS")]
internal sealed class ToNumberAttribute : global::System.Attribute { }

[global::System.AttributeUsage(global::System.AttributeTargets.Parameter)]
[global::System.Diagnostics.Conditional("JINT_SOURCE_GENERATORS")]
internal sealed class ToInt32Attribute : global::System.Attribute { }

[global::System.AttributeUsage(global::System.AttributeTargets.Parameter)]
[global::System.Diagnostics.Conditional("JINT_SOURCE_GENERATORS")]
internal sealed class ToUint32Attribute : global::System.Attribute { }

[global::System.AttributeUsage(global::System.AttributeTargets.Field | global::System.AttributeTargets.Property)]
[global::System.Diagnostics.Conditional("JINT_SOURCE_GENERATORS")]
internal sealed class JsSymbolAttribute : global::System.Attribute
{
    public JsSymbolAttribute(string symbolName)
    {
        SymbolName = symbolName;
    }

    public string SymbolName { get; }
    public global::Jint.Runtime.Descriptors.PropertyFlag Flags { get; set; } = global::Jint.Runtime.Descriptors.PropertyFlag.Configurable;
}
