//HintName: Sample.Foo.g.cs
// <auto-generated/>
#nullable enable
#pragma warning disable MA0195

namespace Sample;

internal sealed partial class Foo
{
    private static readonly global::Jint.Key __Key_abs = "abs";
    private static readonly global::Jint.Key __Key_charAt = "charAt";
    private static readonly global::Jint.Key __Key_passthrough = "passthrough";
    private static readonly global::Jint.Key __Key_untouched = "untouched";

    /// <summary>Generated property registration. Call from <c>Initialize()</c>.</summary>
    private void CreateProperties_Generated()
    {
        var properties = new global::Jint.Collections.StringDictionarySlim<global::Jint.Runtime.Descriptors.PropertyDescriptor>(4);
        properties.AddDangerous(__Key_abs, new global::Jint.Runtime.Descriptors.Specialized.LazyPropertyDescriptor<Foo>(this, static host => new __FooFunction(host, __FooFunction.Slot.Abs), global::Jint.Runtime.Descriptors.PropertyFlag.NonEnumerable));
        properties.AddDangerous(__Key_charAt, new global::Jint.Runtime.Descriptors.Specialized.LazyPropertyDescriptor<Foo>(this, static host => new __FooFunction(host, __FooFunction.Slot.CharAt), global::Jint.Runtime.Descriptors.PropertyFlag.NonEnumerable));
        properties.AddDangerous(__Key_passthrough, new global::Jint.Runtime.Descriptors.Specialized.LazyPropertyDescriptor<Foo>(this, static host => new __FooFunction(host, __FooFunction.Slot.Passthrough), global::Jint.Runtime.Descriptors.PropertyFlag.NonEnumerable));
        properties.AddDangerous(__Key_untouched, new global::Jint.Runtime.Descriptors.Specialized.LazyPropertyDescriptor<Foo>(this, static host => new __FooFunction(host, __FooFunction.Slot.Untouched), global::Jint.Runtime.Descriptors.PropertyFlag.NonEnumerable));
        SetProperties(properties);
    }

    private sealed class __FooFunction : global::Jint.Native.Function.Function
    {
        internal enum Slot : ushort
        {
            Abs,
            CharAt,
            Passthrough,
            Untouched,
        }

        private readonly Foo _host;
        private readonly Slot _slot;

        internal __FooFunction(Foo host, Slot slot)
            : base(host.Engine, host._realm, GetName(slot))
        {
            _host = host;
            _slot = slot;
            _prototype = host._realm.Intrinsics.Function.PrototypeObject;
            _length = new global::Jint.Runtime.Descriptors.PropertyDescriptor(global::Jint.Native.JsNumber.Create(GetLength(slot)), global::Jint.Runtime.Descriptors.PropertyFlag.Configurable);
        }

        protected internal override global::Jint.Native.JsValue Call(global::Jint.Native.JsValue thisObject, global::Jint.Native.JsValue[] arguments)
        {
            switch (_slot)
            {
                case Slot.Abs: return Foo.Abs(thisObject, global::Jint.Runtime.TypeConverter.ToNumber(global::Jint.Runtime.Arguments.At(arguments, 0)));
                case Slot.CharAt: return Foo.CharAt(thisObject, global::Jint.Runtime.TypeConverter.ToJsString(global::Jint.Runtime.Arguments.At(arguments, 0)), global::Jint.Runtime.TypeConverter.ToInteger(global::Jint.Runtime.Arguments.At(arguments, 1)));
                case Slot.Passthrough: return Foo.Passthrough(thisObject, global::Jint.Runtime.Arguments.At(arguments, 0));
                case Slot.Untouched: return Foo.Untouched(thisObject);
                default: throw UnknownSlot(_slot);
            }
        }

        private static global::Jint.Native.JsString GetName(Slot slot)
        {
            switch (slot)
            {
                case Slot.Abs: return global::Jint.Native.JsString.CachedCreate("abs");
                case Slot.CharAt: return global::Jint.Native.JsString.CachedCreate("charAt");
                case Slot.Passthrough: return global::Jint.Native.JsString.CachedCreate("passthrough");
                case Slot.Untouched: return global::Jint.Native.JsString.CachedCreate("untouched");
                default: throw UnknownSlot(slot);
            }
        }

        private static int GetLength(Slot slot)
        {
            switch (slot)
            {
                case Slot.Abs: return 1;
                case Slot.CharAt: return 2;
                case Slot.Passthrough: return 1;
                case Slot.Untouched: return 0;
                default: throw UnknownSlot(slot);
            }
        }

        private static global::System.InvalidOperationException UnknownSlot(Slot slot)
            => new global::System.InvalidOperationException("Unknown slot " + slot + " — generator/runtime mismatch.");

        internal override global::Jint.Native.Function.FastCallShape GetFastCallShape(int argumentCount)
        {
            switch (_slot)
            {
                case Slot.Abs: return new global::Jint.Native.Function.FastCallShape(true, true, global::Jint.Native.Function.FastCallGuard.Any, global::Jint.Native.Function.FastCallGuard.Number, global::Jint.Native.Function.FastCallGuard.Any);
                case Slot.CharAt: return new global::Jint.Native.Function.FastCallShape(true, true, global::Jint.Native.Function.FastCallGuard.Any, global::Jint.Native.Function.FastCallGuard.String, global::Jint.Native.Function.FastCallGuard.Number);
                case Slot.Passthrough: return new global::Jint.Native.Function.FastCallShape(true, false, global::Jint.Native.Function.FastCallGuard.Any, global::Jint.Native.Function.FastCallGuard.Any, global::Jint.Native.Function.FastCallGuard.Any);
                default: return default;
            }
        }

        internal override global::Jint.Native.JsValue CallFast(global::Jint.Native.JsValue thisObject, global::Jint.Native.JsValue arg0, global::Jint.Native.JsValue arg1)
        {
            switch (_slot)
            {
                case Slot.Abs: return Foo.Abs(thisObject, global::Jint.Runtime.TypeConverter.ToNumber(arg0));
                case Slot.CharAt: return Foo.CharAt(thisObject, global::Jint.Runtime.TypeConverter.ToJsString(arg0), global::Jint.Runtime.TypeConverter.ToInteger(arg1));
                case Slot.Passthrough: return Foo.Passthrough(thisObject, arg0);
                default: return base.CallFast(thisObject, arg0, arg1);
            }
        }
    }
}
