//HintName: Sample.Foo.g.cs
// <auto-generated/>
#nullable enable

namespace Sample;

internal sealed partial class Foo
{
    private static readonly global::Jint.Key __Key_arguments = "arguments";
    private static readonly global::Jint.Key __Key_caller = "caller";

    /// <summary>Generated property registration. Call from <c>Initialize()</c>.</summary>
    private void CreateProperties_Generated()
    {
        var properties = new global::Jint.Collections.StringDictionarySlim<global::Jint.Runtime.Descriptors.PropertyDescriptor>(2);
        var __thrower = new global::Jint.Runtime.Descriptors.GetSetPropertyDescriptor.ThrowerPropertyDescriptor(_engine, global::Jint.Runtime.Descriptors.PropertyFlag.Configurable);
        properties.AddDangerous(__Key_arguments, __thrower);
        properties.AddDangerous(__Key_caller, __thrower);
        SetProperties(properties);
    }
}
