//HintName: Sample.Foo.g.cs
// <auto-generated/>
#nullable enable
#pragma warning disable MA0195

namespace Sample;

internal sealed partial class Foo
{
    private static readonly global::Jint.Key __Key_abs = "abs";
    private static readonly global::Jint.Key __Key_concat = "concat";
    private static readonly global::Jint.Key __Key_max = "max";
    private static readonly global::Jint.Key __Key_push = "push";

    /// <summary>Generated property registration. Call from <c>Initialize()</c>.</summary>
    private void CreateProperties_Generated()
    {
        var properties = new global::Jint.Collections.StringDictionarySlim<global::Jint.Runtime.Descriptors.PropertyDescriptor>(4);
        properties.AddDangerous(__Key_abs, new global::Jint.Runtime.Descriptors.Specialized.LazyPropertyDescriptor<Foo>(this, static host => new __FooFunction(host, __FooFunction.Slot.Abs), global::Jint.Runtime.Descriptors.PropertyFlag.NonEnumerable));
        properties.AddDangerous(__Key_concat, new global::Jint.Runtime.Descriptors.Specialized.LazyPropertyDescriptor<Foo>(this, static host => new __FooFunction(host, __FooFunction.Slot.Concat), global::Jint.Runtime.Descriptors.PropertyFlag.NonEnumerable));
        properties.AddDangerous(__Key_max, new global::Jint.Runtime.Descriptors.Specialized.LazyPropertyDescriptor<Foo>(this, static host => new __FooFunction(host, __FooFunction.Slot.Max), global::Jint.Runtime.Descriptors.PropertyFlag.NonEnumerable));
        properties.AddDangerous(__Key_push, new global::Jint.Runtime.Descriptors.Specialized.LazyPropertyDescriptor<Foo>(this, static host => new __FooFunction(host, __FooFunction.Slot.Push), global::Jint.Runtime.Descriptors.PropertyFlag.NonEnumerable));
        SetProperties(properties);
    }

    private sealed class __FooFunction : global::Jint.Native.Function.Function
    {
        internal enum Slot : ushort
        {
            Abs,
            Concat,
            Max,
            Push,
        }

        private readonly Foo _host;
        private readonly Slot _slot;

        internal __FooFunction(Foo host, Slot slot)
            : base(host.Engine, host._realm, GetName(slot))
        {
            _host = host;
            _slot = slot;
            _prototype = host._realm.Intrinsics.Function.PrototypeObject;
            _length = new global::Jint.Runtime.Descriptors.PropertyDescriptor(global::Jint.Native.JsNumber.Create(GetLength(slot)), global::Jint.Runtime.Descriptors.PropertyFlag.Configurable);
        }

        protected internal override global::Jint.Native.JsValue Call(global::Jint.Native.JsValue thisObject, global::Jint.Native.JsValue[] arguments)
        {
            switch (_slot)
            {
                case Slot.Abs: return Foo.Abs(thisObject, global::Jint.Runtime.TypeConverter.ToNumber(global::Jint.Runtime.Arguments.At(arguments, 0)));
                case Slot.Concat: return Foo.Concat(thisObject, global::Jint.Runtime.Arguments.At(arguments, 0), new global::System.ReadOnlySpan<global::Jint.Native.JsValue>(arguments, global::System.Math.Min(1, arguments.Length), global::System.Math.Max(0, arguments.Length - 1)));
                case Slot.Max:
                {
                    var __values = new global::System.ReadOnlySpan<global::Jint.Native.JsValue>(arguments);
                    global::System.Span<double> __coerced = __values.Length <= 16
                        ? stackalloc double[__values.Length]
                        : new double[__values.Length];
                    for (var __i = 0; __i < __values.Length; __i++)
                    {
                        __coerced[__i] = global::Jint.Runtime.TypeConverter.ToNumber(__values[__i]);
                    }
                    return Foo.Max(thisObject, __coerced);
                }
                case Slot.Push: return Foo.Push(thisObject, new global::System.ReadOnlySpan<global::Jint.Native.JsValue>(arguments));
                default: throw UnknownSlot(_slot);
            }
        }

        private static global::Jint.Native.JsString GetName(Slot slot)
        {
            switch (slot)
            {
                case Slot.Abs: return global::Jint.Native.JsString.CachedCreate("abs");
                case Slot.Concat: return global::Jint.Native.JsString.CachedCreate("concat");
                case Slot.Max: return global::Jint.Native.JsString.CachedCreate("max");
                case Slot.Push: return global::Jint.Native.JsString.CachedCreate("push");
                default: throw UnknownSlot(slot);
            }
        }

        private static int GetLength(Slot slot)
        {
            switch (slot)
            {
                case Slot.Abs: return 1;
                case Slot.Concat: return 1;
                case Slot.Max: return 2;
                case Slot.Push: return 1;
                default: throw UnknownSlot(slot);
            }
        }

        private static global::System.InvalidOperationException UnknownSlot(Slot slot)
            => new global::System.InvalidOperationException("Unknown slot " + slot + " — generator/runtime mismatch.");

        internal override global::Jint.Native.Function.FastCallShape GetFastCallShape(int argumentCount)
        {
            switch (_slot)
            {
                case Slot.Abs: return new global::Jint.Native.Function.FastCallShape(true, true, false, global::Jint.Native.Function.FastCallGuard.Any, global::Jint.Native.Function.FastCallGuard.Number, global::Jint.Native.Function.FastCallGuard.Any);
                case Slot.Concat:
                {
                    if (argumentCount > 2) return default;
                    return new global::Jint.Native.Function.FastCallShape(true, false, true, global::Jint.Native.Function.FastCallGuard.Any, global::Jint.Native.Function.FastCallGuard.Any, global::Jint.Native.Function.FastCallGuard.Any);
                }
                case Slot.Max:
                {
                    switch (argumentCount)
                    {
                        case 0: return new global::Jint.Native.Function.FastCallShape(true, true, true, global::Jint.Native.Function.FastCallGuard.Any, global::Jint.Native.Function.FastCallGuard.Any, global::Jint.Native.Function.FastCallGuard.Any);
                        case 1: return new global::Jint.Native.Function.FastCallShape(true, true, true, global::Jint.Native.Function.FastCallGuard.Any, global::Jint.Native.Function.FastCallGuard.Number, global::Jint.Native.Function.FastCallGuard.Any);
                        case 2: return new global::Jint.Native.Function.FastCallShape(true, true, true, global::Jint.Native.Function.FastCallGuard.Any, global::Jint.Native.Function.FastCallGuard.Number, global::Jint.Native.Function.FastCallGuard.Number);
                        default: return default;
                    }
                }
                case Slot.Push:
                {
                    if (argumentCount > 2) return default;
                    return new global::Jint.Native.Function.FastCallShape(true, false, true, global::Jint.Native.Function.FastCallGuard.Any, global::Jint.Native.Function.FastCallGuard.Any, global::Jint.Native.Function.FastCallGuard.Any);
                }
                default: return default;
            }
        }

        internal override global::Jint.Native.JsValue CallFast(global::Jint.Native.JsValue thisObject, global::Jint.Native.JsValue arg0, global::Jint.Native.JsValue arg1)
        {
            switch (_slot)
            {
                case Slot.Abs: return Foo.Abs(thisObject, global::Jint.Runtime.TypeConverter.ToNumber(arg0));
                default: return base.CallFast(thisObject, arg0, arg1);
            }
        }

        internal override global::Jint.Native.JsValue CallFastVariadic(global::Jint.Native.JsValue thisObject, global::System.ReadOnlySpan<global::Jint.Native.JsValue> arguments)
        {
            switch (_slot)
            {
                case Slot.Concat: return Foo.Concat(thisObject, global::Jint.Runtime.Arguments.At(arguments, 0), arguments.Slice(global::System.Math.Min(1, arguments.Length), global::System.Math.Max(0, arguments.Length - 1)));
                case Slot.Max:
                {
                    var __values = arguments;
                    global::System.Span<double> __coerced = __values.Length <= 16
                        ? stackalloc double[__values.Length]
                        : new double[__values.Length];
                    for (var __i = 0; __i < __values.Length; __i++)
                    {
                        __coerced[__i] = global::Jint.Runtime.TypeConverter.ToNumber(__values[__i]);
                    }
                    return Foo.Max(thisObject, __coerced);
                }
                case Slot.Push: return Foo.Push(thisObject, arguments);
                default: return base.CallFastVariadic(thisObject, arguments);
            }
        }
    }
}
