//HintName: Sample.Foo.g.cs
// <auto-generated/>
#nullable enable
#pragma warning disable MA0195

namespace Sample;

internal sealed partial class Foo
{
    private static readonly global::Jint.Key __Key_impostor = "impostor";
    private static readonly global::Jint.Key __Key_mapGet = "mapGet";
    private static readonly global::Jint.Key __Key_mapSet = "mapSet";
    private static readonly global::Jint.Key __Key_setAdd = "setAdd";

    /// <summary>Generated property registration. Call from <c>Initialize()</c>.</summary>
    private void CreateProperties_Generated()
    {
        var properties = new global::Jint.Collections.StringDictionarySlim<global::Jint.Runtime.Descriptors.PropertyDescriptor>(4);
        properties.AddDangerous(__Key_impostor, new global::Jint.Runtime.Descriptors.Specialized.LazyPropertyDescriptor<Foo>(this, static host => new __FooFunction(host, __FooFunction.Slot.Impostor), global::Jint.Runtime.Descriptors.PropertyFlag.NonEnumerable));
        properties.AddDangerous(__Key_mapGet, new global::Jint.Runtime.Descriptors.Specialized.LazyPropertyDescriptor<Foo>(this, static host => new __FooFunction(host, __FooFunction.Slot.MapGet), global::Jint.Runtime.Descriptors.PropertyFlag.NonEnumerable));
        properties.AddDangerous(__Key_mapSet, new global::Jint.Runtime.Descriptors.Specialized.LazyPropertyDescriptor<Foo>(this, static host => new __FooFunction(host, __FooFunction.Slot.MapSet), global::Jint.Runtime.Descriptors.PropertyFlag.NonEnumerable));
        properties.AddDangerous(__Key_setAdd, new global::Jint.Runtime.Descriptors.Specialized.LazyPropertyDescriptor<Foo>(this, static host => new __FooFunction(host, __FooFunction.Slot.SetAdd), global::Jint.Runtime.Descriptors.PropertyFlag.NonEnumerable));
        SetProperties(properties);
    }

    private sealed class __FooFunction : global::Jint.Native.Function.Function
    {
        internal enum Slot : ushort
        {
            Impostor,
            MapGet,
            MapSet,
            SetAdd,
        }

        private readonly Foo _host;
        private readonly Slot _slot;

        internal __FooFunction(Foo host, Slot slot)
            : base(host.Engine, host._realm, GetName(slot))
        {
            _host = host;
            _slot = slot;
            _prototype = host._realm.Intrinsics.Function.PrototypeObject;
            _length = new global::Jint.Runtime.Descriptors.PropertyDescriptor(global::Jint.Native.JsNumber.Create(GetLength(slot)), global::Jint.Runtime.Descriptors.PropertyFlag.Configurable);
        }

        protected internal override global::Jint.Native.JsValue Call(global::Jint.Native.JsValue thisObject, global::Jint.Native.JsValue[] arguments)
        {
            switch (_slot)
            {
                case Slot.Impostor: return Foo.Impostor(thisObject, global::Jint.Runtime.Arguments.At(arguments, 0));
                case Slot.MapGet: return Foo.MapGet(thisObject, global::Jint.Runtime.Arguments.At(arguments, 0));
                case Slot.MapSet: return Foo.MapSet(thisObject, global::Jint.Runtime.Arguments.At(arguments, 0), global::Jint.Runtime.Arguments.At(arguments, 1));
                case Slot.SetAdd: return Foo.SetAdd(thisObject, global::Jint.Runtime.Arguments.At(arguments, 0));
                default: throw UnknownSlot(_slot);
            }
        }

        private static global::Jint.Native.JsString GetName(Slot slot)
        {
            switch (slot)
            {
                case Slot.Impostor: return global::Jint.Native.JsString.CachedCreate("impostor");
                case Slot.MapGet: return global::Jint.Native.JsString.CachedCreate("mapGet");
                case Slot.MapSet: return global::Jint.Native.JsString.CachedCreate("mapSet");
                case Slot.SetAdd: return global::Jint.Native.JsString.CachedCreate("setAdd");
                default: throw UnknownSlot(slot);
            }
        }

        private static int GetLength(Slot slot)
        {
            switch (slot)
            {
                case Slot.Impostor: return 1;
                case Slot.MapGet: return 1;
                case Slot.MapSet: return 2;
                case Slot.SetAdd: return 1;
                default: throw UnknownSlot(slot);
            }
        }

        private static global::System.InvalidOperationException UnknownSlot(Slot slot)
            => new global::System.InvalidOperationException("Unknown slot " + slot + " — generator/runtime mismatch.");

        internal override global::Jint.Native.Function.FastCallShape GetFastCallShape(int argumentCount)
        {
            switch (_slot)
            {
                case Slot.Impostor: return new global::Jint.Native.Function.FastCallShape(true, true, false, global::Jint.Native.Function.FastCallGuard.Map | global::Jint.Native.Function.FastCallGuard.Set, global::Jint.Native.Function.FastCallGuard.Any, global::Jint.Native.Function.FastCallGuard.Any);
                case Slot.MapGet: return new global::Jint.Native.Function.FastCallShape(true, true, false, global::Jint.Native.Function.FastCallGuard.Map, global::Jint.Native.Function.FastCallGuard.Any, global::Jint.Native.Function.FastCallGuard.Any);
                case Slot.MapSet: return new global::Jint.Native.Function.FastCallShape(true, true, false, global::Jint.Native.Function.FastCallGuard.Map, global::Jint.Native.Function.FastCallGuard.Any, global::Jint.Native.Function.FastCallGuard.Any);
                case Slot.SetAdd: return new global::Jint.Native.Function.FastCallShape(true, true, false, global::Jint.Native.Function.FastCallGuard.Set, global::Jint.Native.Function.FastCallGuard.Any, global::Jint.Native.Function.FastCallGuard.Any);
                default: return default;
            }
        }

        internal override global::Jint.Native.JsValue CallFast(global::Jint.Native.JsValue thisObject, global::Jint.Native.JsValue arg0, global::Jint.Native.JsValue arg1)
        {
            switch (_slot)
            {
                case Slot.Impostor: return Foo.Impostor(thisObject, arg0);
                case Slot.MapGet: return Foo.MapGet(thisObject, arg0);
                case Slot.MapSet: return Foo.MapSet(thisObject, arg0, arg1);
                case Slot.SetAdd: return Foo.SetAdd(thisObject, arg0);
                default: return base.CallFast(thisObject, arg0, arg1);
            }
        }
    }
}
