//HintName: Sample.Foo.g.cs
// <auto-generated/>
#nullable enable
#pragma warning disable MA0195

namespace Sample;

internal sealed partial class Foo
{
    private static readonly global::Jint.Key __Key_charCodeAt = "charCodeAt";
    private static readonly global::Jint.Key __Key_derived = "derived";
    private static readonly global::Jint.Key __Key_substring = "substring";

    /// <summary>Generated property registration. Call from <c>Initialize()</c>.</summary>
    private void CreateProperties_Generated()
    {
        var properties = new global::Jint.Collections.StringDictionarySlim<global::Jint.Runtime.Descriptors.PropertyDescriptor>(3);
        properties.AddDangerous(__Key_charCodeAt, new global::Jint.Runtime.Descriptors.Specialized.LazyPropertyDescriptor<Foo>(this, static host => new __FooFunction(host, __FooFunction.Slot.CharCodeAt), global::Jint.Runtime.Descriptors.PropertyFlag.NonEnumerable));
        properties.AddDangerous(__Key_derived, new global::Jint.Runtime.Descriptors.Specialized.LazyPropertyDescriptor<Foo>(this, static host => new __FooFunction(host, __FooFunction.Slot.Derived), global::Jint.Runtime.Descriptors.PropertyFlag.NonEnumerable));
        properties.AddDangerous(__Key_substring, new global::Jint.Runtime.Descriptors.Specialized.LazyPropertyDescriptor<Foo>(this, static host => new __FooFunction(host, __FooFunction.Slot.Substring), global::Jint.Runtime.Descriptors.PropertyFlag.NonEnumerable));
        SetProperties(properties);
    }

    private sealed class __FooFunction : global::Jint.Native.Function.Function
    {
        internal enum Slot : ushort
        {
            CharCodeAt,
            Derived,
            Substring,
        }

        private readonly Foo _host;
        private readonly Slot _slot;

        internal __FooFunction(Foo host, Slot slot)
            : base(host.Engine, host._realm, GetName(slot))
        {
            _host = host;
            _slot = slot;
            _prototype = host._realm.Intrinsics.Function.PrototypeObject;
            _length = new global::Jint.Runtime.Descriptors.PropertyDescriptor(global::Jint.Native.JsNumber.Create(GetLength(slot)), global::Jint.Runtime.Descriptors.PropertyFlag.Configurable);
        }

        protected internal override global::Jint.Native.JsValue Call(global::Jint.Native.JsValue thisObject, global::Jint.Native.JsValue[] arguments)
        {
            switch (_slot)
            {
                case Slot.CharCodeAt: return Foo.CharCodeAt(thisObject, global::Jint.Runtime.Arguments.At(arguments, 0));
                case Slot.Derived: return Foo.Derived(thisObject, global::Jint.Runtime.TypeConverter.ToNumber(global::Jint.Runtime.Arguments.At(arguments, 0)));
                case Slot.Substring: return Foo.Substring(thisObject, global::Jint.Runtime.Arguments.At(arguments, 0), global::Jint.Runtime.Arguments.At(arguments, 1));
                default: throw UnknownSlot(_slot);
            }
        }

        private static global::Jint.Native.JsString GetName(Slot slot)
        {
            switch (slot)
            {
                case Slot.CharCodeAt: return global::Jint.Native.JsString.CachedCreate("charCodeAt");
                case Slot.Derived: return global::Jint.Native.JsString.CachedCreate("derived");
                case Slot.Substring: return global::Jint.Native.JsString.CachedCreate("substring");
                default: throw UnknownSlot(slot);
            }
        }

        private static int GetLength(Slot slot)
        {
            switch (slot)
            {
                case Slot.CharCodeAt: return 1;
                case Slot.Derived: return 1;
                case Slot.Substring: return 2;
                default: throw UnknownSlot(slot);
            }
        }

        private static global::System.InvalidOperationException UnknownSlot(Slot slot)
            => new global::System.InvalidOperationException("Unknown slot " + slot + " — generator/runtime mismatch.");

        internal override global::Jint.Native.Function.FastCallShape GetFastCallShape(int argumentCount)
        {
            switch (_slot)
            {
                case Slot.CharCodeAt: return new global::Jint.Native.Function.FastCallShape(true, true, false, global::Jint.Native.Function.FastCallGuard.String, global::Jint.Native.Function.FastCallGuard.Number, global::Jint.Native.Function.FastCallGuard.Any);
                case Slot.Derived: return new global::Jint.Native.Function.FastCallShape(true, true, false, global::Jint.Native.Function.FastCallGuard.Any, global::Jint.Native.Function.FastCallGuard.Number, global::Jint.Native.Function.FastCallGuard.Any);
                case Slot.Substring: return new global::Jint.Native.Function.FastCallShape(true, true, false, global::Jint.Native.Function.FastCallGuard.String, global::Jint.Native.Function.FastCallGuard.Number | global::Jint.Native.Function.FastCallGuard.Undefined, global::Jint.Native.Function.FastCallGuard.Number | global::Jint.Native.Function.FastCallGuard.Undefined);
                default: return default;
            }
        }

        internal override global::Jint.Native.JsValue CallFast(global::Jint.Native.JsValue thisObject, global::Jint.Native.JsValue arg0, global::Jint.Native.JsValue arg1)
        {
            switch (_slot)
            {
                case Slot.CharCodeAt: return Foo.CharCodeAt(thisObject, arg0);
                case Slot.Derived: return Foo.Derived(thisObject, global::Jint.Runtime.TypeConverter.ToNumber(arg0));
                case Slot.Substring: return Foo.Substring(thisObject, arg0, arg1);
                default: return base.CallFast(thisObject, arg0, arg1);
            }
        }
    }
}
