//HintName: Sample.Foo.g.cs
// <auto-generated/>
#nullable enable
#pragma warning disable MA0195

namespace Sample;

internal sealed partial class Foo
{
    /// <summary>Generated property registration. Call from <c>Initialize()</c>.</summary>
    private void CreateProperties_Generated()
    {
        // no [JsFunction] / [JsProperty] / [JsAccessor] / [JsThrowerAccessor] / [JsIntrinsicReference] members
    }

    /// <summary>Generated symbol-keyed registration. Call from <c>Initialize()</c>.</summary>
    private void CreateSymbols_Generated()
    {
        var symbols = new global::Jint.Collections.DictionarySlim<global::Jint.Native.JsSymbol, global::Jint.Runtime.Descriptors.PropertyDescriptor>(1);
        symbols[global::Jint.Native.Symbol.GlobalSymbolRegistry.Species] = new global::Jint.Runtime.Descriptors.Specialized.LazyGetSetPropertyDescriptor<Foo>(this, static host => new __FooFunction(host), null, global::Jint.Runtime.Descriptors.PropertyFlag.EnumerableSet | global::Jint.Runtime.Descriptors.PropertyFlag.Configurable);
        SetSymbols(symbols);
    }

    private sealed class __FooFunction : global::Jint.Native.Function.Function
    {

        private readonly Foo _host;

        internal __FooFunction(Foo host)
            : base(host.Engine, host._realm, global::Jint.Native.JsString.CachedCreate("get [Symbol.species]"))
        {
            _host = host;
            _prototype = host._realm.Intrinsics.Function.PrototypeObject;
            _length = new global::Jint.Runtime.Descriptors.PropertyDescriptor(global::Jint.Native.JsNumber.Create(0), global::Jint.Runtime.Descriptors.PropertyFlag.Configurable);
        }

        protected internal override global::Jint.Native.JsValue Call(global::Jint.Native.JsValue thisObject, global::Jint.Native.JsValue[] arguments)
        {
            return Foo.Species(thisObject);
        }
    }
}
