//HintName: Sample.Foo.g.cs
// <auto-generated/>
#nullable enable

namespace Sample;

internal sealed partial class Foo
{
    private static readonly global::Jint.Key __Key_size = "size";

    /// <summary>Generated property registration. Call from <c>Initialize()</c>.</summary>
    private void CreateProperties_Generated()
    {
        var properties = new global::Jint.Collections.StringDictionarySlim<global::Jint.Runtime.Descriptors.PropertyDescriptor>(1);
        properties.AddDangerous(__Key_size, new global::Jint.Runtime.Descriptors.Specialized.LazyGetSetPropertyDescriptor<Foo>(this, static host => new __FooFunction(host), null, global::Jint.Runtime.Descriptors.PropertyFlag.EnumerableSet | global::Jint.Runtime.Descriptors.PropertyFlag.Configurable));
        SetProperties(properties);
    }

    private sealed class __FooFunction : global::Jint.Native.Function.Function
    {

        private readonly Foo _host;

        internal __FooFunction(Foo host)
            : base(host.Engine, host._realm, global::Jint.Native.JsString.CachedCreate("get size"))
        {
            _host = host;
            _prototype = host._realm.Intrinsics.Function.PrototypeObject;
            _length = new global::Jint.Runtime.Descriptors.PropertyDescriptor(global::Jint.Native.JsNumber.Create(0), global::Jint.Runtime.Descriptors.PropertyFlag.Configurable);
        }

        protected internal override global::Jint.Native.JsValue Call(global::Jint.Native.JsValue thisObject, global::Jint.Native.JsValue[] arguments)
        {
            return _host.SizeGet(thisObject);
        }
    }
}
