//HintName: Sample.Foo.g.cs
// <auto-generated/>
#nullable enable
#pragma warning disable MA0195

namespace Sample;

internal sealed partial class Foo : global::Jint.Native.Object.IBuiltinShaped
{
    private static readonly global::Jint.Key __Key_bar = "bar";
    private static readonly global::Jint.Key __Key_arguments = "arguments";
    private static readonly global::Jint.Key __Key_caller = "caller";

    /// <summary>Generated property registration. Call from <c>Initialize()</c>.</summary>
    private void CreateProperties_Generated()
    {
        InitializeBuiltinShape();
    }

    private static readonly global::Jint.Native.Object.BuiltinShape __builtinShape = BuildBuiltinShape_Generated();

    private static global::Jint.Native.Object.BuiltinShape BuildBuiltinShape_Generated()
    {
        var builder = new global::Jint.Native.Object.BuiltinShape.Builder(3);
        builder.Function(__Key_bar, (global::System.UInt16) 0, global::Jint.Runtime.Descriptors.PropertyFlag.NonEnumerable);
        builder.Factory(__Key_arguments, static host => new global::Jint.Runtime.Descriptors.GetSetPropertyDescriptor.ThrowerPropertyDescriptor(((Foo) host)._realm, global::Jint.Runtime.Descriptors.PropertyFlag.Configurable));
        builder.Factory(__Key_caller, static host => new global::Jint.Runtime.Descriptors.GetSetPropertyDescriptor.ThrowerPropertyDescriptor(((Foo) host)._realm, global::Jint.Runtime.Descriptors.PropertyFlag.Configurable));
        return builder.Build();
    }

    private global::Jint.Runtime.Descriptors.PropertyDescriptor?[]? __builtinDescriptors;

    global::Jint.Native.Object.BuiltinShape global::Jint.Native.Object.IBuiltinShaped.BuiltinShape => __builtinShape;

    global::Jint.Runtime.Descriptors.PropertyDescriptor?[]? global::Jint.Native.Object.IBuiltinShaped.BuiltinDescriptors { get => __builtinDescriptors; set => __builtinDescriptors = value; }

    global::Jint.Native.Function.Function global::Jint.Native.Object.IBuiltinShaped.MakeBuiltinFunction(global::System.UInt16 slot) => new __FooFunction(this);

    private sealed class __FooFunction : global::Jint.Native.Function.Function
    {

        private readonly Foo _host;

        internal __FooFunction(Foo host)
            : base(host.Engine, host._realm, global::Jint.Native.JsString.CachedCreate("bar"))
        {
            _host = host;
            _prototype = host._realm.Intrinsics.Function.PrototypeObject;
            _length = new global::Jint.Runtime.Descriptors.PropertyDescriptor(global::Jint.Native.JsNumber.Create(1), global::Jint.Runtime.Descriptors.PropertyFlag.Configurable);
        }

        protected internal override global::Jint.Native.JsValue Call(global::Jint.Native.JsValue thisObject, global::Jint.Native.JsValue[] arguments)
        {
            return Foo.Bar(global::Jint.Runtime.Arguments.At(arguments, 0));
        }
    }
}
