//HintName: JintAttributes.g.cs
// <auto-generated/>
#nullable enable

namespace Jint;

[global::System.AttributeUsage(global::System.AttributeTargets.Class)]
[global::System.Diagnostics.Conditional("JINT_SOURCE_GENERATORS")]
internal sealed class JsObjectAttribute : global::System.Attribute
{
}

[global::System.AttributeUsage(global::System.AttributeTargets.Method)]
[global::System.Diagnostics.Conditional("JINT_SOURCE_GENERATORS")]
internal sealed class JsFunctionAttribute : global::System.Attribute
{
    public string? Name { get; set; }
    public int Length { get; set; } = -1;
}

[global::System.AttributeUsage(global::System.AttributeTargets.Field | global::System.AttributeTargets.Property)]
[global::System.Diagnostics.Conditional("JINT_SOURCE_GENERATORS")]
internal sealed class JsPropertyAttribute : global::System.Attribute
{
    public string? Name { get; set; }
    public global::Jint.Runtime.Descriptors.PropertyFlag Flags { get; set; } = global::Jint.Runtime.Descriptors.PropertyFlag.AllForbidden;
}

[global::System.AttributeUsage(global::System.AttributeTargets.Parameter)]
[global::System.Diagnostics.Conditional("JINT_SOURCE_GENERATORS")]
internal sealed class RestAttribute : global::System.Attribute
{
}

// Marks a parameter as receiving the result of a TypeConverter.ToXxx coercion of arguments[N].
// The CLR parameter type must match the converter's return type (double for ToNumber, int for
// ToInt32, uint for ToUint32). The generator emits the conversion at the dispatcher boundary.

[global::System.AttributeUsage(global::System.AttributeTargets.Parameter)]
[global::System.Diagnostics.Conditional("JINT_SOURCE_GENERATORS")]
internal sealed class ToNumberAttribute : global::System.Attribute { }

[global::System.AttributeUsage(global::System.AttributeTargets.Parameter)]
[global::System.Diagnostics.Conditional("JINT_SOURCE_GENERATORS")]
internal sealed class ToInt32Attribute : global::System.Attribute { }

[global::System.AttributeUsage(global::System.AttributeTargets.Parameter)]
[global::System.Diagnostics.Conditional("JINT_SOURCE_GENERATORS")]
internal sealed class ToUint32Attribute : global::System.Attribute { }

[global::System.AttributeUsage(global::System.AttributeTargets.Parameter)]
[global::System.Diagnostics.Conditional("JINT_SOURCE_GENERATORS")]
internal sealed class ToIntegerAttribute : global::System.Attribute { }

[global::System.AttributeUsage(global::System.AttributeTargets.Parameter)]
[global::System.Diagnostics.Conditional("JINT_SOURCE_GENERATORS")]
internal sealed class ToLengthAttribute : global::System.Attribute { }

[global::System.AttributeUsage(global::System.AttributeTargets.Parameter)]
[global::System.Diagnostics.Conditional("JINT_SOURCE_GENERATORS")]
internal sealed class ToStringAttribute : global::System.Attribute { }

[global::System.AttributeUsage(global::System.AttributeTargets.Parameter)]
[global::System.Diagnostics.Conditional("JINT_SOURCE_GENERATORS")]
internal sealed class ToJsStringAttribute : global::System.Attribute { }

[global::System.AttributeUsage(global::System.AttributeTargets.Parameter)]
[global::System.Diagnostics.Conditional("JINT_SOURCE_GENERATORS")]
internal sealed class ToObjectAttribute : global::System.Attribute { }

// Marks a [JsFunction]/[JsSymbolFunction] method whose dispatcher should call
// TypeConverter.RequireObjectCoercible(_host._engine, thisObject) before invoking the user method.
// Common pattern for String and Array prototype methods that require 'this' to be defined/non-null.
[global::System.AttributeUsage(global::System.AttributeTargets.Method)]
[global::System.Diagnostics.Conditional("JINT_SOURCE_GENERATORS")]
internal sealed class RequireObjectCoercibleAttribute : global::System.Attribute { }

[global::System.AttributeUsage(global::System.AttributeTargets.Field | global::System.AttributeTargets.Property)]
[global::System.Diagnostics.Conditional("JINT_SOURCE_GENERATORS")]
internal sealed class JsSymbolAttribute : global::System.Attribute
{
    public JsSymbolAttribute(string symbolName)
    {
        SymbolName = symbolName;
    }

    public string SymbolName { get; }
    public global::Jint.Runtime.Descriptors.PropertyFlag Flags { get; set; } = global::Jint.Runtime.Descriptors.PropertyFlag.Configurable;
}

internal enum AccessorKind { Get, Set }

// Pairs by Name on the same class. The CLR method takes the standard JsValue thisObject + value
// parameters; the generator emits a GetSetPropertyDescriptor wrapping both halves and an entry
// per method in the per-host dispatcher.
[global::System.AttributeUsage(global::System.AttributeTargets.Method, AllowMultiple = false)]
[global::System.Diagnostics.Conditional("JINT_SOURCE_GENERATORS")]
internal sealed class JsAccessorAttribute : global::System.Attribute
{
    public JsAccessorAttribute(string name, AccessorKind kind = AccessorKind.Get)
    {
        Name = name;
        Kind = kind;
    }

    public string Name { get; }
    public AccessorKind Kind { get; }
    public global::Jint.Runtime.Descriptors.PropertyFlag Flags { get; set; } = global::Jint.Runtime.Descriptors.PropertyFlag.Configurable;
}

// Class-level, repeats. Each one registers a single shared ThrowerPropertyDescriptor on the host
// under the named key. Used for FunctionPrototype's "arguments" and "caller".
[global::System.AttributeUsage(global::System.AttributeTargets.Class, AllowMultiple = true)]
[global::System.Diagnostics.Conditional("JINT_SOURCE_GENERATORS")]
internal sealed class JsThrowerAccessorAttribute : global::System.Attribute
{
    public JsThrowerAccessorAttribute(string name) { Name = name; }
    public string Name { get; }
    public global::Jint.Runtime.Descriptors.PropertyFlag Flags { get; set; } = global::Jint.Runtime.Descriptors.PropertyFlag.Configurable;
}

// Like [JsFunction] but registers in SymbolDictionary instead of PropertyDictionary.
// SymbolName must match a static property on Jint.Native.Symbol.GlobalSymbolRegistry.
[global::System.AttributeUsage(global::System.AttributeTargets.Method)]
[global::System.Diagnostics.Conditional("JINT_SOURCE_GENERATORS")]
internal sealed class JsSymbolFunctionAttribute : global::System.Attribute
{
    public JsSymbolFunctionAttribute(string symbolName) { SymbolName = symbolName; }
    public string SymbolName { get; }
    public int Length { get; set; } = -1;
    public global::Jint.Runtime.Descriptors.PropertyFlag Flags { get; set; } = global::Jint.Runtime.Descriptors.PropertyFlag.AllForbidden;
}

// Symbol-keyed accessor: pairs by SymbolName on the same class. Get and Set halves emit one
// GetSetPropertyDescriptor wrapping eagerly-allocated dispatcher slots, registered under
// GlobalSymbolRegistry.<SymbolName>. Most commonly used for "@@species" getters.
[global::System.AttributeUsage(global::System.AttributeTargets.Method, AllowMultiple = false)]
[global::System.Diagnostics.Conditional("JINT_SOURCE_GENERATORS")]
internal sealed class JsSymbolAccessorAttribute : global::System.Attribute
{
    public JsSymbolAccessorAttribute(string symbolName, AccessorKind kind = AccessorKind.Get)
    {
        SymbolName = symbolName;
        Kind = kind;
    }

    public string SymbolName { get; }
    public AccessorKind Kind { get; }
    public global::Jint.Runtime.Descriptors.PropertyFlag Flags { get; set; } = global::Jint.Runtime.Descriptors.PropertyFlag.Configurable;
}
