//HintName: Sample.Foo.g.cs
// <auto-generated/>
#nullable enable

namespace Sample;

internal sealed partial class Foo
{
    private static readonly global::Jint.Key __Key_max = "max";

    /// <summary>Generated property registration. Call from <c>Initialize()</c>.</summary>
    private void CreateProperties_Generated()
    {
        var properties = new global::Jint.Collections.StringDictionarySlim<global::Jint.Runtime.Descriptors.PropertyDescriptor>(1);
        properties.AddDangerous(__Key_max, new global::Jint.Runtime.Descriptors.Specialized.LazyPropertyDescriptor<Foo>(this, static host => new __FooFunction(host), global::Jint.Runtime.Descriptors.PropertyFlag.NonEnumerable));
        SetProperties(properties);
    }

    private sealed class __FooFunction : global::Jint.Native.Function.Function
    {

        private readonly Foo _host;

        internal __FooFunction(Foo host)
            : base(host.Engine, host._realm, global::Jint.Native.JsString.CachedCreate("max"))
        {
            _host = host;
            _prototype = host._realm.Intrinsics.Function.PrototypeObject;
            _length = new global::Jint.Runtime.Descriptors.PropertyDescriptor(global::Jint.Native.JsNumber.Create(2), global::Jint.Runtime.Descriptors.PropertyFlag.Configurable);
        }

        protected internal override global::Jint.Native.JsValue Call(global::Jint.Native.JsValue thisObject, global::Jint.Native.JsValue[] arguments)
        {
            var __values = new global::System.ReadOnlySpan<global::Jint.Native.JsValue>(arguments, 0, arguments.Length);
            global::System.Span<double> __coerced = __values.Length <= 16
                ? stackalloc double[__values.Length]
                : new double[__values.Length];
            for (var __i = 0; __i < __values.Length; __i++)
            {
                __coerced[__i] = global::Jint.Runtime.TypeConverter.ToNumber(__values[__i]);
            }
                return Foo.Max(thisObject, __coerced);
        }
    }
}
