//HintName: Sample.Foo.g.cs
// <auto-generated/>
#nullable enable
#pragma warning disable MA0195

namespace Sample;

internal sealed partial class Foo : global::Jint.Native.Object.IBuiltinShaped
{
    private static readonly global::Jint.Key __Key_next = "next";
    private static readonly global::Jint.Key __Key_plain = "plain";

    /// <summary>Generated property registration. Call from <c>Initialize()</c>.</summary>
    private void CreateProperties_Generated()
    {
        InitializeBuiltinShape();
    }

    private static readonly global::Jint.Native.Object.BuiltinShape __builtinShape = BuildBuiltinShape_Generated();

    private static global::Jint.Native.Object.BuiltinShape BuildBuiltinShape_Generated()
    {
        var builder = new global::Jint.Native.Object.BuiltinShape.Builder(2);
        builder.Function(__Key_next, (global::System.UInt16) __FooFunction.Slot.Next, global::Jint.Runtime.Descriptors.PropertyFlag.ConfigurableEnumerableWritable);
        builder.Function(__Key_plain, (global::System.UInt16) __FooFunction.Slot.Plain, global::Jint.Runtime.Descriptors.PropertyFlag.NonEnumerable);
        return builder.Build();
    }

    private global::Jint.Runtime.Descriptors.PropertyDescriptor?[]? __builtinDescriptors;

    global::Jint.Native.Object.BuiltinShape global::Jint.Native.Object.IBuiltinShaped.BuiltinShape => __builtinShape;

    global::Jint.Runtime.Descriptors.PropertyDescriptor?[]? global::Jint.Native.Object.IBuiltinShaped.BuiltinDescriptors { get => __builtinDescriptors; set => __builtinDescriptors = value; }

    global::Jint.Native.Function.Function global::Jint.Native.Object.IBuiltinShaped.MakeBuiltinFunction(global::System.UInt16 slot) => new __FooFunction(this, (__FooFunction.Slot) slot);

    private sealed class __FooFunction : global::Jint.Native.Function.Function
    {
        internal enum Slot : ushort
        {
            Next,
            Plain,
        }

        private readonly Foo _host;
        private readonly Slot _slot;

        internal __FooFunction(Foo host, Slot slot)
            : base(host.Engine, host._realm, GetName(slot))
        {
            _host = host;
            _slot = slot;
            _prototype = host._realm.Intrinsics.Function.PrototypeObject;
            _length = new global::Jint.Runtime.Descriptors.PropertyDescriptor(global::Jint.Native.JsNumber.Create(GetLength(slot)), global::Jint.Runtime.Descriptors.PropertyFlag.Configurable);
        }

        protected internal override global::Jint.Native.JsValue Call(global::Jint.Native.JsValue thisObject, global::Jint.Native.JsValue[] arguments)
        {
            switch (_slot)
            {
                case Slot.Next: return Foo.Next(thisObject);
                case Slot.Plain: return Foo.Plain(thisObject);
                default: throw UnknownSlot(_slot);
            }
        }

        private static global::Jint.Native.JsString GetName(Slot slot)
        {
            switch (slot)
            {
                case Slot.Next: return global::Jint.Native.JsString.CachedCreate("next");
                case Slot.Plain: return global::Jint.Native.JsString.CachedCreate("plain");
                default: throw UnknownSlot(slot);
            }
        }

        private static int GetLength(Slot slot)
        {
            switch (slot)
            {
                case Slot.Next: return 0;
                case Slot.Plain: return 0;
                default: throw UnknownSlot(slot);
            }
        }

        private static global::System.InvalidOperationException UnknownSlot(Slot slot)
            => new global::System.InvalidOperationException("Unknown slot " + slot + " — generator/runtime mismatch.");
    }
}
