//HintName: Sample.Foo.g.cs
// <auto-generated/>
#nullable enable
#pragma warning disable MA0195

namespace Sample;

internal sealed partial class Foo
{
    private static readonly global::Jint.Key __Key_Array = "Array";
    private static readonly global::Jint.Key __Key_Generator = "Generator";
    private static readonly global::Jint.Key __Key_JSON = "JSON";
    private static readonly global::Jint.Key __Key_eval = "eval";

    /// <summary>Generated property registration. Call from <c>Initialize()</c>.</summary>
    private void CreateProperties_Generated()
    {
        var properties = new global::Jint.Collections.StringDictionarySlim<global::Jint.Runtime.Descriptors.PropertyDescriptor>(4);
        properties.AddDangerous(__Key_Array, new global::Jint.Runtime.Descriptors.Specialized.LazyPropertyDescriptor<Foo>(this, static host => host._realm.Intrinsics.Array, global::Jint.Runtime.Descriptors.PropertyFlag.Writable | global::Jint.Runtime.Descriptors.PropertyFlag.Configurable));
        properties.AddDangerous(__Key_Generator, new global::Jint.Runtime.Descriptors.Specialized.LazyPropertyDescriptor<Foo>(this, static host => host._realm.Intrinsics.GeneratorFunction, global::Jint.Runtime.Descriptors.PropertyFlag.Writable | global::Jint.Runtime.Descriptors.PropertyFlag.Configurable));
        properties.AddDangerous(__Key_JSON, new global::Jint.Runtime.Descriptors.Specialized.LazyPropertyDescriptor<Foo>(this, static host => host._realm.Intrinsics.Json, global::Jint.Runtime.Descriptors.PropertyFlag.Writable | global::Jint.Runtime.Descriptors.PropertyFlag.Configurable));
        properties.AddDangerous(__Key_eval, new global::Jint.Runtime.Descriptors.Specialized.LazyPropertyDescriptor<Foo>(this, static host => host._realm.Intrinsics.Eval, global::Jint.Runtime.Descriptors.PropertyFlag.Writable | global::Jint.Runtime.Descriptors.PropertyFlag.Configurable));
        SetProperties(properties);
    }
}
