//HintName: JintAttributes.g.cs
// <auto-generated/>
#nullable enable

namespace Jint;

[global::System.AttributeUsage(global::System.AttributeTargets.Class)]
[global::System.Diagnostics.Conditional("JINT_SOURCE_GENERATORS")]
internal sealed class JsObjectAttribute : global::System.Attribute
{
}

[global::System.AttributeUsage(global::System.AttributeTargets.Method)]
[global::System.Diagnostics.Conditional("JINT_SOURCE_GENERATORS")]
internal sealed class JsFunctionAttribute : global::System.Attribute
{
    public string? Name { get; set; }
    public int Length { get; set; } = -1;
}

[global::System.AttributeUsage(global::System.AttributeTargets.Field | global::System.AttributeTargets.Property)]
[global::System.Diagnostics.Conditional("JINT_SOURCE_GENERATORS")]
internal sealed class JsPropertyAttribute : global::System.Attribute
{
    public string? Name { get; set; }
    public global::Jint.Runtime.Descriptors.PropertyFlag Flags { get; set; } = global::Jint.Runtime.Descriptors.PropertyFlag.AllForbidden;
}

[global::System.AttributeUsage(global::System.AttributeTargets.Parameter)]
[global::System.Diagnostics.Conditional("JINT_SOURCE_GENERATORS")]
internal sealed class RestAttribute : global::System.Attribute
{
}

[global::System.AttributeUsage(global::System.AttributeTargets.Field | global::System.AttributeTargets.Property)]
[global::System.Diagnostics.Conditional("JINT_SOURCE_GENERATORS")]
internal sealed class JsSymbolAttribute : global::System.Attribute
{
    public JsSymbolAttribute(string symbolName)
    {
        SymbolName = symbolName;
    }

    public string SymbolName { get; }
    public global::Jint.Runtime.Descriptors.PropertyFlag Flags { get; set; } = global::Jint.Runtime.Descriptors.PropertyFlag.Configurable;
}
