//HintName: Sample.Foo.g.cs
// <auto-generated/>
#nullable enable
#pragma warning disable MA0195

namespace Sample;

internal sealed partial class Foo
{
    private static readonly global::Jint.Key __Key_arrayLength = "arrayLength";
    private static readonly global::Jint.Key __Key_getTime = "getTime";

    /// <summary>Generated property registration. Call from <c>Initialize()</c>.</summary>
    private void CreateProperties_Generated()
    {
        var properties = new global::Jint.Collections.StringDictionarySlim<global::Jint.Runtime.Descriptors.PropertyDescriptor>(2);
        properties.AddDangerous(__Key_arrayLength, new global::Jint.Runtime.Descriptors.Specialized.LazyPropertyDescriptor<Foo>(this, static host => new __FooFunction(host, __FooFunction.Slot.ArrayLength), global::Jint.Runtime.Descriptors.PropertyFlag.NonEnumerable));
        properties.AddDangerous(__Key_getTime, new global::Jint.Runtime.Descriptors.Specialized.LazyPropertyDescriptor<Foo>(this, static host => new __FooFunction(host, __FooFunction.Slot.GetTime), global::Jint.Runtime.Descriptors.PropertyFlag.NonEnumerable));
        SetProperties(properties);
    }

    private sealed class __FooFunction : global::Jint.Native.Function.Function
    {
        internal enum Slot : ushort
        {
            ArrayLength,
            GetTime,
        }

        private readonly Foo _host;
        private readonly Slot _slot;

        internal __FooFunction(Foo host, Slot slot)
            : base(host.Engine, host._realm, GetName(slot))
        {
            _host = host;
            _slot = slot;
            _prototype = host._realm.Intrinsics.Function.PrototypeObject;
            _length = new global::Jint.Runtime.Descriptors.PropertyDescriptor(global::Jint.Native.JsNumber.Create(GetLength(slot)), global::Jint.Runtime.Descriptors.PropertyFlag.Configurable);
        }

        protected internal override global::Jint.Native.JsValue Call(global::Jint.Native.JsValue thisObject, global::Jint.Native.JsValue[] arguments)
        {
            switch (_slot)
            {
                case Slot.ArrayLength:
                {
                    var __cast = thisObject as global::Jint.Native.Array.ArrayInstance;
                    if (__cast is null) global::Jint.Runtime.Throw.TypeError(_host._realm, "arrayLength requires 'this' to be of type ArrayInstance");
                    return Foo.ArrayLength(__cast);
                }
                case Slot.GetTime:
                {
                    var __cast = thisObject as global::Jint.Native.JsDate;
                    if (__cast is null) global::Jint.Runtime.Throw.TypeError(_host._realm, "getTime requires 'this' to be of type JsDate");
                    return Foo.GetTime(__cast);
                }
                default: throw UnknownSlot(_slot);
            }
        }

        private static global::Jint.Native.JsString GetName(Slot slot)
        {
            switch (slot)
            {
                case Slot.ArrayLength: return global::Jint.Native.JsString.CachedCreate("arrayLength");
                case Slot.GetTime: return global::Jint.Native.JsString.CachedCreate("getTime");
                default: throw UnknownSlot(slot);
            }
        }

        private static int GetLength(Slot slot)
        {
            switch (slot)
            {
                case Slot.ArrayLength: return 0;
                case Slot.GetTime: return 0;
                default: throw UnknownSlot(slot);
            }
        }

        private static global::System.InvalidOperationException UnknownSlot(Slot slot)
            => new global::System.InvalidOperationException("Unknown slot " + slot + " — generator/runtime mismatch.");

        internal override global::Jint.Native.Function.FastCallShape GetFastCallShape(int argumentCount)
        {
            switch (_slot)
            {
                case Slot.ArrayLength: return new global::Jint.Native.Function.FastCallShape(true, true, false, global::Jint.Native.Function.FastCallGuard.Array, global::Jint.Native.Function.FastCallGuard.Any, global::Jint.Native.Function.FastCallGuard.Any);
                case Slot.GetTime: return new global::Jint.Native.Function.FastCallShape(true, true, false, global::Jint.Native.Function.FastCallGuard.Date, global::Jint.Native.Function.FastCallGuard.Any, global::Jint.Native.Function.FastCallGuard.Any);
                default: return default;
            }
        }

        internal override global::Jint.Native.JsValue CallFast(global::Jint.Native.JsValue thisObject, global::Jint.Native.JsValue arg0, global::Jint.Native.JsValue arg1)
        {
            switch (_slot)
            {
                case Slot.ArrayLength:
                {
                    var __cast = thisObject as global::Jint.Native.Array.ArrayInstance;
                    if (__cast is null) global::Jint.Runtime.Throw.TypeError(_host._realm, "arrayLength requires 'this' to be of type ArrayInstance");
                    return Foo.ArrayLength(__cast);
                }
                case Slot.GetTime:
                {
                    var __cast = thisObject as global::Jint.Native.JsDate;
                    if (__cast is null) global::Jint.Runtime.Throw.TypeError(_host._realm, "getTime requires 'this' to be of type JsDate");
                    return Foo.GetTime(__cast);
                }
                default: return base.CallFast(thisObject, arg0, arg1);
            }
        }
    }
}
