using System.Globalization;
using System.Text;

namespace Jint.Browser.BindingGenerator;

/// <summary>Writes the checked-in <c>Jint.Browser/Dom/Generated/*.g.cs</c>.</summary>
internal sealed class Emitter
{
    private const string Header = """
        // <auto-generated>
        //     Generated by tools/dom-bindings/Jint.Browser.BindingGenerator from the AngleSharp assemblies
        //     pinned in tools/dom-bindings/pin.json. Do not edit: DomBindingsStalenessTests runs the same
        //     emitter in memory and fails on any difference. Regenerate with JINT_DOM_BINDINGS=update, or
        //     with the command in tools/dom-bindings/README.md.
        // </auto-generated>

        #nullable enable

        namespace Jint.Browser.Dom;


        """;

    private readonly BindingModel _model;

    internal Emitter(BindingModel model) => _model = model;

    internal Dictionary<string, string> Emit()
    {
        var files = new Dictionary<string, string>(StringComparer.Ordinal)
        {
            ["DomInterfaces.g.cs"] = EmitRegistry(),
            ["DomTypeMap.g.cs"] = EmitTypeMap(),
            ["DomEnums.g.cs"] = EmitEnums(),
            ["DomCollectionAccessors.g.cs"] = EmitAccessors(),
        };

        foreach (var group in _model.Interfaces.Select(i => i.Group).Distinct().OrderBy(g => g, StringComparer.Ordinal))
        {
            files["DomShapes." + group + ".g.cs"] = EmitShapes(group);
        }

        // Normalized to LF, because part of the output comes from raw string literals in THIS file and a raw
        // string literal takes its line endings verbatim from the source: on a Windows checkout, where
        // .gitattributes has already turned these sources into CRLF, the headers would come out CRLF and
        // everything the StringBuilders wrote would come out LF. The staleness test compares against a file
        // it reads with CRLF normalized away, so a mixed emitter output can never equal it — and would fail
        // on Windows only.
        foreach (var name in files.Keys.ToList())
        {
            files[name] = files[name].Replace("\r\n", "\n", StringComparison.Ordinal);
        }

        return files;
    }

    private string EmitRegistry()
    {
        var builder = new StringBuilder(Header);
        builder.Append("""
            /// <summary>
            /// Every WebIDL interface the generator found in the pinned AngleSharp assemblies, parents before
            /// children so that a prototype chain can be built by walking <c>Parent</c>.
            /// </summary>
            internal static partial class DomInterfaces
            {

            """);

        foreach (var model in _model.Interfaces)
        {
            builder.Append("    /// <summary>The <c>").Append(model.DomName).Append("</c> interface, projected from <c>")
                .Append(model.ClrType.FullName).Append("</c>.</summary>\n")
                .Append("    internal static readonly DomInterfaceDefinition ").Append(model.FieldName).Append(";\n\n");
        }

        builder.Append("    /// <summary>Every definition, in the order they were created.</summary>\n");
        builder.Append("    internal static readonly DomInterfaceDefinition[] All;\n\n");

        builder.Append("    static DomInterfaces()\n    {\n");
        builder.Append("        var all = new global::System.Collections.Generic.List<DomInterfaceDefinition>(").Append(_model.Interfaces.Count).Append(");\n\n");

        foreach (var model in _model.Interfaces)
        {
            builder.Append("        ").Append(model.FieldName).Append(" = Add(new DomInterfaceDefinition(\n")
                .Append("            ").Append(CSharpNames.Literal(model.DomName)).Append(",\n")
                .Append("            typeof(").Append(CSharpNames.Render(model.ClrType)).Append("),\n")
                .Append("            ").Append(model.ManualShape ?? "Build" + model.FieldName).Append(",\n")
                .Append("            ").Append(model.Parent is null ? "null" : model.Parent.FieldName).Append(",\n")
                .Append("            rootsAtEventTarget: ").Append(model.RootsAtEventTarget ? "true" : "false").Append(",\n")
                .Append("            hasInterfaceObject: ").Append(model.HasInterfaceObject ? "true" : "false").Append(",\n")
                .Append("            DomWrapperKind.").Append(model.Kind)
                .Append(model.AccessorReference is null ? "" : ",\n            collectionAccessor: " + model.AccessorReference)
                .Append(model.Constants.Count == 0
                    ? ""
                    : ",\n            constants:\n            [\n" + string.Concat(model.Constants.Select(c =>
                        "                new DomConstant(" + CSharpNames.Literal(c.Name) + ", " + c.Value.ToString(CultureInfo.InvariantCulture) + "),\n")) + "            ]")
                .Append("));\n\n");
        }

        builder.Append("        All = all.ToArray();\n\n");
        builder.Append("        DomInterfaceDefinition Add(DomInterfaceDefinition definition)\n        {\n");
        builder.Append("            definition.Index = all.Count;\n            all.Add(definition);\n            return definition;\n        }\n");
        builder.Append("    }\n}\n");

        return builder.ToString();
    }

    private string EmitShapes(string group)
    {
        var builder = new StringBuilder(Header);

        // AngleSharp and AngleSharp.Css both declare an AngleSharp.Dom.ElementExtensions, so a member that
        // AngleSharp spells as an extension method is called in extension form and the namespace comes in
        // here — naming either class by its full name is CS0433 whichever one is meant.
        foreach (var extensionNamespace in _model.ExtensionNamespaces)
        {
            builder.Append("using ").Append(extensionNamespace).Append(";\n");
        }

        if (_model.ExtensionNamespaces.Count > 0)
        {
            builder.Append('\n');
        }

        builder.Append("internal static partial class DomInterfaces\n{\n");

        var first = true;
        foreach (var model in _model.Interfaces.Where(i => i.Group == group && i.ManualShape is null))
        {
            if (!first)
            {
                builder.Append('\n');
            }

            first = false;

            builder.Append("    /// <summary>The members of <c>").Append(model.DomName).Append("</c>.</summary>\n");
            builder.Append("    private static global::Jint.Native.JsObjectShape Build").Append(model.FieldName).Append("()\n");

            // An interface with hand-written additions takes a block body, so the addition runs against the
            // half-built builder and every member — generated and hand-written — lands in one shape. Everyone
            // else keeps the expression body, which is what keeps this change's diff to the interfaces that
            // actually gained something.
            if (model.ShapeAdditions is not null)
            {
                builder.Append("    {\n");
                builder.Append("        var builder = new global::Jint.Native.JsObjectShape.Builder()\n");
            }
            else
            {
                builder.Append("        => new global::Jint.Native.JsObjectShape.Builder()\n");
            }

            builder.Append("            .ToStringTag(").Append(CSharpNames.Literal(model.DomName)).Append(")\n");

            // https://webidl.spec.whatwg.org/#interface-prototype-object — `constructor` is
            // { writable: true, enumerable: false, configurable: true }, and per-realm because the interface
            // object it names belongs to one engine.
            builder.Append("            .PerRealmSlot(\"constructor\", enumerable: false)\n");

            foreach (var constant in model.Constants)
            {
                // https://webidl.spec.whatwg.org/#es-constants — { writable: false, enumerable: true,
                // configurable: false }, which is what JsObjectShape.Constant forces.
                builder.Append("            .Constant(").Append(CSharpNames.Literal(constant.Name))
                    .Append(", global::Jint.Native.JsNumber.Create(").Append(constant.Value.ToString(CultureInfo.InvariantCulture)).Append("))\n");
            }

            foreach (var member in model.Members)
            {
                var label = model.DomName + "." + member.DomName;

                if (member.Kind == MemberKind.Operation)
                {
                    // https://webidl.spec.whatwg.org/#es-operations — { writable: true, enumerable: true,
                    // configurable: true }, which is JsObjectShape.Method's default and the opposite of
                    // ECMAScript's rule for a built-in.
                    builder.Append("            .Method(").Append(CSharpNames.Literal(member.DomName)).Append(",\n");
                    AppendGuardedBody(builder, label, member.Body);
                    builder.Append(",\n");
                    builder.Append("                length: ").Append(member.Length).Append(")\n");
                }
                else
                {
                    // https://webidl.spec.whatwg.org/#es-attributes — { enumerable: true, configurable: true },
                    // JsObjectShape.Accessor's default.
                    builder.Append("            .Accessor(").Append(CSharpNames.Literal(member.DomName)).Append(",\n");
                    AppendGuardedBody(builder, label, member.Body);

                    if (member.SetterBody is { } setter)
                    {
                        builder.Append(",\n");
                        AppendGuardedBody(builder, label, setter);
                    }

                    builder.Append(")\n");
                }
            }

            if (model.ShapeAdditions is not null)
            {
                // The last member's own newline becomes the statement terminator, so the chain ends the way a
                // hand-written one would rather than with a semicolon on a line of its own.
                builder.Length -= 1;
                builder.Append(";\n\n");
                builder.Append("        global::").Append(model.ShapeAdditions).Append("(builder);\n");
                builder.Append("        return builder.Build();\n");
                builder.Append("    }\n");
            }
            else
            {
                builder.Append("            .Build();\n");
            }
        }

        builder.Append("}\n");
        return builder.ToString();
    }

    /// <summary>
    /// One member body, wrapped in the invoker that turns an <c>AngleSharp.Dom.DomException</c> into the
    /// <c>DOMException</c> the standard prescribes. Every member goes through it — an operation, both halves
    /// of an attribute — because which of them can refuse is AngleSharp's business rather than the metadata's,
    /// and a page's only vocabulary for a refusal is <c>e.name</c>. <c>Jint.Browser/Dom/DomFailures</c> is the
    /// whole of the conversion; here there is deliberately no <c>catch</c> to get out of step with it.
    /// </summary>
    private static void AppendGuardedBody(StringBuilder builder, string label, string body)
    {
        builder.Append("                global::Jint.Browser.Dom.DomFailures.Guard(")
            .Append(CSharpNames.Literal(label))
            .Append(", static (thisObj, args) =>\n                {\n");
        AppendBody(builder, body, "                    ");
        builder.Append("                })");
    }

    private static void AppendBody(StringBuilder builder, string body, string indent)
    {
        foreach (var line in body.Split('\n'))
        {
            if (line.Length == 0)
            {
                builder.Append('\n');
                continue;
            }

            builder.Append(indent).Append(line).Append('\n');
        }
    }

    private string EmitAccessors()
    {
        var builder = new StringBuilder(Header);

        foreach (var model in _model.Interfaces.Where(i => i.AccessorClass is not null))
        {
            builder.Append(model.AccessorClass).Append('\n');
        }

        return builder.ToString();
    }

    private string EmitEnums()
    {
        var builder = new StringBuilder(Header);
        builder.Append("""
            /// <summary>
            /// The WebIDL string enumerations AngleSharp models as CLR enums, in both directions. A value the
            /// enumeration does not carry is a <c>TypeError</c>, which is what WebIDL's enumeration conversion
            /// says.
            /// </summary>
            internal static class DomEnums
            {

            """);

        var first = true;
        foreach (var model in _model.StringEnums.Values.OrderBy(e => e.HelperName, StringComparer.Ordinal))
        {
            if (!first)
            {
                builder.Append('\n');
            }

            first = false;

            builder.Append("    internal static global::Jint.Native.JsValue From").Append(model.HelperName)
                .Append('(').Append(model.ClrFullName).Append(" value) => value switch\n    {\n");

            foreach (var (field, literal) in model.Values)
            {
                builder.Append("        ").Append(model.ClrFullName).Append('.').Append(field)
                    .Append(" => global::Jint.Native.JsString.Create(").Append(CSharpNames.Literal(literal)).Append("),\n");
            }

            builder.Append("        _ => global::Jint.Native.JsString.Create(value.ToString()),\n    };\n\n");

            builder.Append("    internal static ").Append(model.ClrFullName).Append(" To").Append(model.HelperName)
                .Append("(global::Jint.Native.JsValue value, string member) => global::Jint.Runtime.TypeConverter.ToString(value) switch\n    {\n");

            foreach (var (field, literal) in model.Values)
            {
                builder.Append("        ").Append(CSharpNames.Literal(literal)).Append(" => ").Append(model.ClrFullName).Append('.').Append(field).Append(",\n");
            }

            builder.Append("        _ => DomConvert.BadEnumValue<").Append(model.ClrFullName).Append(">(value, member),\n    };\n");
        }

        builder.Append("}\n");
        return builder.ToString();
    }

    private string EmitTypeMap()
    {
        var builder = new StringBuilder(Header);
        builder.Append("""
            internal static partial class DomTypeMap
            {
                /// <summary>
                /// Every generated interface, most derived first. A runtime type is matched against this in
                /// order, so the first interface it implements is the most specific one — which is how an
                /// AngleSharp element class, almost all of which are internal, is given its DOM interface.
                /// </summary>
                private static readonly DomInterfaceDefinition[] _candidates =
                [

            """);

        foreach (var model in _model.Interfaces.OrderByDescending(Depth).ThenBy(m => m.DomName, StringComparer.Ordinal))
        {
            builder.Append("        DomInterfaces.").Append(model.FieldName).Append(",\n");
        }

        builder.Append("    ];\n\n");

        builder.Append("""
                /// <summary>
                /// Closes <c>DomHtmlCollectionObject&lt;T&gt;</c> over every element type the generator saw in a
                /// member signature, so that a collection arriving through the untyped entry still gets a
                /// wrapper — and so that every instantiation is named in source rather than reflected into
                /// existence.
                /// </summary>
                internal static global::Jint.Native.Object.ObjectInstance? WrapHtmlCollection(DomRealm realm, DomInterfaceDefinition definition, object value) => value switch
                {

            """);

        // IElement last, so a more specific element type is matched first; a switch is ordered.
        const string AnyElement = "global::AngleSharp.Dom.IElement";
        foreach (var element in _model.HtmlCollectionElements.Where(e => !string.Equals(e, AnyElement, StringComparison.Ordinal)))
        {
            builder.Append("        global::AngleSharp.Dom.IHtmlCollection<").Append(element).Append("> collection => new global::Jint.Browser.Dom.Collections.DomHtmlCollectionObject<")
                .Append(element).Append(">(realm, definition, collection),\n");
        }

        builder.Append("        global::AngleSharp.Dom.IHtmlCollection<global::AngleSharp.Dom.IElement> collection => new global::Jint.Browser.Dom.Collections.DomHtmlCollectionObject<global::AngleSharp.Dom.IElement>(realm, definition, collection),\n");
        builder.Append("        _ => null,\n    };\n}\n");

        return builder.ToString();
    }

    private static int Depth(InterfaceModel model)
    {
        var depth = 0;
        var current = model.Parent;
        while (current is not null)
        {
            depth++;
            current = current.Parent;
        }

        return depth;
    }
}
