// <auto-generated />
// Generated by Jint.HtmlParser/Html/generate_known_names.py. Do not edit.
#nullable enable
using System;
using System.Buffers.Binary;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace Jint.Tests.HtmlParser.Html;

internal static class HeaderByteNames
{
    private static readonly string[] Names =
    [
        "Host",
        "Accept",
        "User-Agent",
        "Content-Type",
        "Content-Length",
        "Content-Encoding",
        "Content-Language",
        "Content-Location",
    ];

    internal static ReadOnlySpan<string> Values => Names;

    internal static string? Match(ReadOnlySpan<byte> input)
    {
        switch (input.Length)
        {
            case 4:
            {
                if ((Read4(input, 0) & 0xDFDFDFDFU) == 0x54534F48U) return "Host";
                break;
            }
            case 6:
            {
                if ((Read4(input, 0) & 0xDFDFDFDFU) == 0x45434341U && (Read2(input, 4) & 0xDFDFU) == 0x5450U) return "Accept";
                break;
            }
            case 10:
            {
                if ((Read8(input, 0) & 0xDFDFDFFFDFDFDFDFUL) == 0x4547412D52455355UL && (Read2(input, 8) & 0xDFDFU) == 0x544EU) return "User-Agent";
                break;
            }
            case 12:
            {
                if ((Read8(input, 0) & 0xFFDFDFDFDFDFDFDFUL) == 0x2D544E45544E4F43UL && (Read4(input, 8) & 0xDFDFDFDFU) == 0x45505954U) return "Content-Type";
                break;
            }
            case 14:
            {
                if ((Read8(input, 0) & 0xFFDFDFDFDFDFDFDFUL) == 0x2D544E45544E4F43UL && (Read4(input, 8) & 0xDFDFDFDFU) == 0x474E454CU && (Read2(input, 12) & 0xDFDFU) == 0x4854U) return "Content-Length";
                break;
            }
            case 16:
            {
                var chunk0 = Read8(input, 8);
                if ((chunk0 & 0xDFDFDFDFDFDFDFDFUL) == 0x45474155474E414CUL)
                {
                    if ((Read8(input, 0) & 0xFFDFDFDFDFDFDFDFUL) == 0x2D544E45544E4F43UL) return "Content-Language";
                }
                else if ((chunk0 & 0xDFDFDFDFDFDFDFDFUL) == 0x474E49444F434E45UL)
                {
                    if ((Read8(input, 0) & 0xFFDFDFDFDFDFDFDFUL) == 0x2D544E45544E4F43UL) return "Content-Encoding";
                }
                else if ((chunk0 & 0xDFDFDFDFDFDFDFDFUL) == 0x4E4F495441434F4CUL)
                {
                    if ((Read8(input, 0) & 0xFFDFDFDFDFDFDFDFUL) == 0x2D544E45544E4F43UL) return "Content-Location";
                }
                break;
            }
        }
        return null;
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private static uint Read2(ReadOnlySpan<byte> input, int offset)
        => BinaryPrimitives.ReadUInt16LittleEndian(input.Slice(offset, 2));

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private static uint Read4(ReadOnlySpan<byte> input, int offset)
        => BinaryPrimitives.ReadUInt32LittleEndian(input.Slice(offset, 4));

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private static ulong Read8(ReadOnlySpan<byte> input, int offset)
        => BinaryPrimitives.ReadUInt64LittleEndian(input.Slice(offset, 8));
}

internal static class HeaderCharNames
{
    private static readonly string[] Names =
    [
        "Host",
        "Accept",
        "User-Agent",
        "Content-Type",
        "Content-Length",
        "Content-Encoding",
        "Content-Language",
        "Content-Location",
    ];

    internal static ReadOnlySpan<string> Values => Names;

    internal static string? Match(ReadOnlySpan<char> input)
    {
        switch (input.Length)
        {
            case 4:
            {
                if ((Read4(input, 0) & 0xFFDFFFDFFFDFFFDFUL) == 0x00540053004F0048UL) return "Host";
                break;
            }
            case 6:
            {
                if ((Read4(input, 0) & 0xFFDFFFDFFFDFFFDFUL) == 0x0045004300430041UL && (Read2(input, 4) & 0xFFDFFFDFU) == 0x00540050U) return "Accept";
                break;
            }
            case 10:
            {
                if ((Read4(input, 0) & 0xFFDFFFDFFFDFFFDFUL) == 0x0052004500530055UL && (Read4(input, 4) & 0xFFDFFFDFFFDFFFFFUL) == 0x004500470041002DUL && (Read2(input, 8) & 0xFFDFFFDFU) == 0x0054004EU) return "User-Agent";
                break;
            }
            case 12:
            {
                if ((Read4(input, 0) & 0xFFDFFFDFFFDFFFDFUL) == 0x0054004E004F0043UL && (Read4(input, 4) & 0xFFFFFFDFFFDFFFDFUL) == 0x002D0054004E0045UL && (Read4(input, 8) & 0xFFDFFFDFFFDFFFDFUL) == 0x0045005000590054UL) return "Content-Type";
                break;
            }
            case 14:
            {
                if ((Read4(input, 0) & 0xFFDFFFDFFFDFFFDFUL) == 0x0054004E004F0043UL && (Read4(input, 4) & 0xFFFFFFDFFFDFFFDFUL) == 0x002D0054004E0045UL && (Read4(input, 8) & 0xFFDFFFDFFFDFFFDFUL) == 0x0047004E0045004CUL && (Read2(input, 12) & 0xFFDFFFDFU) == 0x00480054U) return "Content-Length";
                break;
            }
            case 16:
            {
                var chunk0 = Read4(input, 8);
                if ((chunk0 & 0xFFDFFFDFFFDFFFDFUL) == 0x00410043004F004CUL)
                {
                    if ((Read4(input, 0) & 0xFFDFFFDFFFDFFFDFUL) == 0x0054004E004F0043UL && (Read4(input, 4) & 0xFFFFFFDFFFDFFFDFUL) == 0x002D0054004E0045UL && (Read4(input, 12) & 0xFFDFFFDFFFDFFFDFUL) == 0x004E004F00490054UL) return "Content-Location";
                }
                else if ((chunk0 & 0xFFDFFFDFFFDFFFDFUL) == 0x0047004E0041004CUL)
                {
                    if ((Read4(input, 0) & 0xFFDFFFDFFFDFFFDFUL) == 0x0054004E004F0043UL && (Read4(input, 4) & 0xFFFFFFDFFFDFFFDFUL) == 0x002D0054004E0045UL && (Read4(input, 12) & 0xFFDFFFDFFFDFFFDFUL) == 0x0045004700410055UL) return "Content-Language";
                }
                else if ((chunk0 & 0xFFDFFFDFFFDFFFDFUL) == 0x004F0043004E0045UL)
                {
                    if ((Read4(input, 0) & 0xFFDFFFDFFFDFFFDFUL) == 0x0054004E004F0043UL && (Read4(input, 4) & 0xFFFFFFDFFFDFFFDFUL) == 0x002D0054004E0045UL && (Read4(input, 12) & 0xFFDFFFDFFFDFFFDFUL) == 0x0047004E00490044UL) return "Content-Encoding";
                }
                break;
            }
        }
        return null;
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private static uint Read2(ReadOnlySpan<char> input, int offset)
    {
        var value = MemoryMarshal.Read<uint>(MemoryMarshal.AsBytes(input.Slice(offset, 2)));
        return BitConverter.IsLittleEndian ? value : (value << 16) | (value >> 16);
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private static ulong Read4(ReadOnlySpan<char> input, int offset)
    {
        var value = MemoryMarshal.Read<ulong>(MemoryMarshal.AsBytes(input.Slice(offset, 4)));
        return BitConverter.IsLittleEndian ? value
            : (value << 48) | ((value & 0xFFFF0000UL) << 16) |
              ((value >> 16) & 0xFFFF0000UL) | (value >> 48);
    }
}

internal static class KeywordByteNames
{
    private static readonly string[] Names =
    [
        "if",
        "for",
        "try",
        "break",
        "catch",
        "throw",
        "while",
        "return",
        "switch",
        "continue",
    ];

    internal static ReadOnlySpan<string> Values => Names;

    internal static string? Match(ReadOnlySpan<byte> input)
    {
        switch (input.Length)
        {
            case 2:
            {
                if (Read2(input, 0) == 0x6669U) return "if";
                break;
            }
            case 3:
            {
                var chunk0 = Read2(input, 0);
                switch (chunk0)
                {
                    case 0x6F66U:
                    {
                        if ((uint) input[2] == 0x72U) return "for";
                        break;
                    }
                    case 0x7274U:
                    {
                        if ((uint) input[2] == 0x79U) return "try";
                        break;
                    }
                }
                break;
            }
            case 5:
            {
                var chunk1 = Read4(input, 0);
                switch (chunk1)
                {
                    case 0x61657262U:
                    {
                        if ((uint) input[4] == 0x6BU) return "break";
                        break;
                    }
                    case 0x63746163U:
                    {
                        if ((uint) input[4] == 0x68U) return "catch";
                        break;
                    }
                    case 0x6C696877U:
                    {
                        if ((uint) input[4] == 0x65U) return "while";
                        break;
                    }
                    case 0x6F726874U:
                    {
                        if ((uint) input[4] == 0x77U) return "throw";
                        break;
                    }
                }
                break;
            }
            case 6:
            {
                var chunk2 = Read4(input, 0);
                switch (chunk2)
                {
                    case 0x74697773U:
                    {
                        if (Read2(input, 4) == 0x6863U) return "switch";
                        break;
                    }
                    case 0x75746572U:
                    {
                        if (Read2(input, 4) == 0x6E72U) return "return";
                        break;
                    }
                }
                break;
            }
            case 8:
            {
                if (Read8(input, 0) == 0x65756E69746E6F63UL) return "continue";
                break;
            }
        }
        return null;
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private static uint Read2(ReadOnlySpan<byte> input, int offset)
        => BinaryPrimitives.ReadUInt16LittleEndian(input.Slice(offset, 2));

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private static uint Read4(ReadOnlySpan<byte> input, int offset)
        => BinaryPrimitives.ReadUInt32LittleEndian(input.Slice(offset, 4));

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private static ulong Read8(ReadOnlySpan<byte> input, int offset)
        => BinaryPrimitives.ReadUInt64LittleEndian(input.Slice(offset, 8));
}

internal static class SharedPrefixNames
{
    private static readonly string[] Names =
    [
        "shared-prefix-blu-a-shared-suffix",
        "shared-prefix-blu-b-shared-suffix",
        "shared-prefix-blu-c-shared-suffix",
        "shared-prefix-red-a-shared-suffix",
        "shared-prefix-red-b-shared-suffix",
        "shared-prefix-red-c-shared-suffix",
    ];

    internal static ReadOnlySpan<string> Values => Names;

    internal static string? Match(ReadOnlySpan<char> input)
    {
        switch (input.Length)
        {
            case 33:
            {
                var chunk0 = Read4(input, 16);
                switch (chunk0)
                {
                    case 0x002D0061002D0064UL:
                    {
                        if (Read4(input, 0) == 0x0072006100680073UL && Read4(input, 4) == 0x0070002D00640065UL && Read4(input, 8) == 0x0069006600650072UL && Read4(input, 12) == 0x00650072002D0078UL && Read4(input, 20) == 0x0072006100680073UL && Read4(input, 24) == 0x0073002D00640065UL && Read4(input, 28) == 0x0069006600660075UL && (uint) input[32] == 0x0078U) return "shared-prefix-red-a-shared-suffix";
                        break;
                    }
                    case 0x002D0061002D0075UL:
                    {
                        if (Read4(input, 0) == 0x0072006100680073UL && Read4(input, 4) == 0x0070002D00640065UL && Read4(input, 8) == 0x0069006600650072UL && Read4(input, 12) == 0x006C0062002D0078UL && Read4(input, 20) == 0x0072006100680073UL && Read4(input, 24) == 0x0073002D00640065UL && Read4(input, 28) == 0x0069006600660075UL && (uint) input[32] == 0x0078U) return "shared-prefix-blu-a-shared-suffix";
                        break;
                    }
                    case 0x002D0062002D0064UL:
                    {
                        if (Read4(input, 0) == 0x0072006100680073UL && Read4(input, 4) == 0x0070002D00640065UL && Read4(input, 8) == 0x0069006600650072UL && Read4(input, 12) == 0x00650072002D0078UL && Read4(input, 20) == 0x0072006100680073UL && Read4(input, 24) == 0x0073002D00640065UL && Read4(input, 28) == 0x0069006600660075UL && (uint) input[32] == 0x0078U) return "shared-prefix-red-b-shared-suffix";
                        break;
                    }
                    case 0x002D0062002D0075UL:
                    {
                        if (Read4(input, 0) == 0x0072006100680073UL && Read4(input, 4) == 0x0070002D00640065UL && Read4(input, 8) == 0x0069006600650072UL && Read4(input, 12) == 0x006C0062002D0078UL && Read4(input, 20) == 0x0072006100680073UL && Read4(input, 24) == 0x0073002D00640065UL && Read4(input, 28) == 0x0069006600660075UL && (uint) input[32] == 0x0078U) return "shared-prefix-blu-b-shared-suffix";
                        break;
                    }
                    case 0x002D0063002D0064UL:
                    {
                        if (Read4(input, 0) == 0x0072006100680073UL && Read4(input, 4) == 0x0070002D00640065UL && Read4(input, 8) == 0x0069006600650072UL && Read4(input, 12) == 0x00650072002D0078UL && Read4(input, 20) == 0x0072006100680073UL && Read4(input, 24) == 0x0073002D00640065UL && Read4(input, 28) == 0x0069006600660075UL && (uint) input[32] == 0x0078U) return "shared-prefix-red-c-shared-suffix";
                        break;
                    }
                    case 0x002D0063002D0075UL:
                    {
                        if (Read4(input, 0) == 0x0072006100680073UL && Read4(input, 4) == 0x0070002D00640065UL && Read4(input, 8) == 0x0069006600650072UL && Read4(input, 12) == 0x006C0062002D0078UL && Read4(input, 20) == 0x0072006100680073UL && Read4(input, 24) == 0x0073002D00640065UL && Read4(input, 28) == 0x0069006600660075UL && (uint) input[32] == 0x0078U) return "shared-prefix-blu-c-shared-suffix";
                        break;
                    }
                }
                break;
            }
        }
        return null;
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private static ulong Read4(ReadOnlySpan<char> input, int offset)
    {
        var value = MemoryMarshal.Read<ulong>(MemoryMarshal.AsBytes(input.Slice(offset, 4)));
        return BitConverter.IsLittleEndian ? value
            : (value << 48) | ((value & 0xFFFF0000UL) << 16) |
              ((value >> 16) & 0xFFFF0000UL) | (value >> 48);
    }
}
