"""Generate HTML first-strong direction data from Unicode 17 DerivedBidiClass.txt.

Usage: python3 tools/bidi-data/generate.py /path/to/DerivedBidiClass.txt
Source: https://www.unicode.org/Public/17.0.0/ucd/extracted/DerivedBidiClass.txt
Includes @missing defaults, including unassigned RTL characters.
"""
import pathlib
import re
import sys

source = pathlib.Path(sys.argv[1]).read_text()
assert source.startswith('# DerivedBidiClass-17.0.0.txt')
values = bytearray(0x110000)
def assign(start, end, name):
    value = 1 if name in ('L', 'Left_To_Right') else 2 if name in ('R', 'AL', 'Right_To_Left', 'Arabic_Letter') else 0
    start, end = int(start, 16), int(end or start, 16)
    values[start:end + 1] = bytes([value]) * (end - start + 1)
for match in re.finditer(r'@missing: ([0-9A-F]+)(?:\.\.([0-9A-F]+))?; (\w+)', source):
    assign(*match.groups())
for match in re.finditer(r'^([0-9A-F]+)(?:\.\.([0-9A-F]+))?\s*; (\w+)', source, re.M):
    assign(*match.groups())
bounds = [i << 2 | value for i, value in enumerate(values) if i == 0 or value != values[i - 1]]
output = '''// Generated by tools/bidi-data/generate.py from Unicode 17.0.0 DerivedBidiClass.txt.
// Unicode data: https://www.unicode.org/license.txt
namespace Jint.Browser.Dom;

internal static class HtmlBidiData
{
    // Each entry packs a range start and its class: 0 neutral, 1 L, 2 R/AL.
    private static ReadOnlySpan<int> Ranges =>
    [
'''
for i in range(0, len(bounds), 8):
    output += '        ' + ', '.join(f'0x{x:X}' for x in bounds[i:i+8]) + ',\n'
output += '''    ];

    internal static int ClassOf(int codePoint)
    {
        var ranges = Ranges;
        var low = 0;
        var high = ranges.Length;
        while (low + 1 < high)
        {
            var middle = low + (high - low) / 2;
            if ((ranges[middle] >> 2) <= codePoint)
            {
                low = middle;
            }
            else
            {
                high = middle;
            }
        }
        return ranges[low] & 3;
    }
}
'''
pathlib.Path('Jint.Browser/Dom/HtmlBidiData.cs').write_text(output)
