// <auto-generated />
// Generated by Jint.HtmlParser/Html/generate_known_names.py. Do not edit.
#nullable enable
using System;
using System.Buffers.Binary;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace Jint.HtmlParser.Html;

internal static class HtmlKnownNames
{
    private static readonly string[] Names =
    [
        "a",
        "b",
        "i",
        "p",
        "s",
        "u",
        "br",
        "em",
        "h1",
        "h2",
        "h3",
        "h4",
        "h5",
        "h6",
        "hr",
        "id",
        "li",
        "ol",
        "td",
        "th",
        "tr",
        "ul",
        "alt",
        "div",
        "img",
        "rel",
        "src",
        "body",
        "form",
        "head",
        "href",
        "html",
        "link",
        "meta",
        "name",
        "span",
        "type",
        "class",
        "input",
        "label",
        "style",
        "table",
        "tbody",
        "tfoot",
        "thead",
        "title",
        "value",
        "button",
        "option",
        "script",
        "select",
        "strong",
        "content",
        "section",
        "template",
        "textarea",
    ];

    internal static ReadOnlySpan<string> Values => Names;

    internal static string? Match(ReadOnlySpan<char> input)
    {
        switch (input.Length)
        {
            case 1:
            {
                var chunk0 = (uint) input[0];
                switch (chunk0)
                {
                    case 0x0061U:
                    {
                        return "a";
                    }
                    case 0x0062U:
                    {
                        return "b";
                    }
                    case 0x0069U:
                    {
                        return "i";
                    }
                    case 0x0070U:
                    {
                        return "p";
                    }
                    case 0x0073U:
                    {
                        return "s";
                    }
                    case 0x0075U:
                    {
                        return "u";
                    }
                }
                break;
            }
            case 2:
            {
                var chunk1 = Read2(input, 0);
                switch (chunk1)
                {
                    case 0x00310068U:
                    {
                        return "h1";
                    }
                    case 0x00320068U:
                    {
                        return "h2";
                    }
                    case 0x00330068U:
                    {
                        return "h3";
                    }
                    case 0x00340068U:
                    {
                        return "h4";
                    }
                    case 0x00350068U:
                    {
                        return "h5";
                    }
                    case 0x00360068U:
                    {
                        return "h6";
                    }
                    case 0x00640069U:
                    {
                        return "id";
                    }
                    case 0x00640074U:
                    {
                        return "td";
                    }
                    case 0x00680074U:
                    {
                        return "th";
                    }
                    case 0x0069006CU:
                    {
                        return "li";
                    }
                    case 0x006C006FU:
                    {
                        return "ol";
                    }
                    case 0x006C0075U:
                    {
                        return "ul";
                    }
                    case 0x006D0065U:
                    {
                        return "em";
                    }
                    case 0x00720062U:
                    {
                        return "br";
                    }
                    case 0x00720068U:
                    {
                        return "hr";
                    }
                    case 0x00720074U:
                    {
                        return "tr";
                    }
                }
                break;
            }
            case 3:
            {
                var chunk2 = Read2(input, 0);
                switch (chunk2)
                {
                    case 0x00650072U:
                    {
                        if ((uint) input[2] == 0x006CU) return "rel";
                        break;
                    }
                    case 0x00690064U:
                    {
                        if ((uint) input[2] == 0x0076U) return "div";
                        break;
                    }
                    case 0x006C0061U:
                    {
                        if ((uint) input[2] == 0x0074U) return "alt";
                        break;
                    }
                    case 0x006D0069U:
                    {
                        if ((uint) input[2] == 0x0067U) return "img";
                        break;
                    }
                    case 0x00720073U:
                    {
                        if ((uint) input[2] == 0x0063U) return "src";
                        break;
                    }
                }
                break;
            }
            case 4:
            {
                var chunk3 = Read4(input, 0);
                switch (chunk3)
                {
                    case 0x006100740065006DUL:
                    {
                        return "meta";
                    }
                    case 0x0064006100650068UL:
                    {
                        return "head";
                    }
                    case 0x0065006D0061006EUL:
                    {
                        return "name";
                    }
                    case 0x0065007000790074UL:
                    {
                        return "type";
                    }
                    case 0x0066006500720068UL:
                    {
                        return "href";
                    }
                    case 0x006B006E0069006CUL:
                    {
                        return "link";
                    }
                    case 0x006C006D00740068UL:
                    {
                        return "html";
                    }
                    case 0x006D0072006F0066UL:
                    {
                        return "form";
                    }
                    case 0x006E006100700073UL:
                    {
                        return "span";
                    }
                    case 0x00790064006F0062UL:
                    {
                        return "body";
                    }
                }
                break;
            }
            case 5:
            {
                var chunk4 = Read4(input, 0);
                switch (chunk4)
                {
                    case 0x0061006500680074UL:
                    {
                        if ((uint) input[4] == 0x0064U) return "thead";
                        break;
                    }
                    case 0x0064006F00620074UL:
                    {
                        if ((uint) input[4] == 0x0079U) return "tbody";
                        break;
                    }
                    case 0x006500620061006CUL:
                    {
                        if ((uint) input[4] == 0x006CU) return "label";
                        break;
                    }
                    case 0x006C006200610074UL:
                    {
                        if ((uint) input[4] == 0x0065U) return "table";
                        break;
                    }
                    case 0x006C007400690074UL:
                    {
                        if ((uint) input[4] == 0x0065U) return "title";
                        break;
                    }
                    case 0x006C007900740073UL:
                    {
                        if ((uint) input[4] == 0x0065U) return "style";
                        break;
                    }
                    case 0x006F006F00660074UL:
                    {
                        if ((uint) input[4] == 0x0074U) return "tfoot";
                        break;
                    }
                    case 0x00730061006C0063UL:
                    {
                        if ((uint) input[4] == 0x0073U) return "class";
                        break;
                    }
                    case 0x0075006C00610076UL:
                    {
                        if ((uint) input[4] == 0x0065U) return "value";
                        break;
                    }
                    case 0x00750070006E0069UL:
                    {
                        if ((uint) input[4] == 0x0074U) return "input";
                        break;
                    }
                }
                break;
            }
            case 6:
            {
                var chunk5 = Read4(input, 0);
                switch (chunk5)
                {
                    case 0x0065006C00650073UL:
                    {
                        if (Read2(input, 4) == 0x00740063U) return "select";
                        break;
                    }
                    case 0x0069007200630073UL:
                    {
                        if (Read2(input, 4) == 0x00740070U) return "script";
                        break;
                    }
                    case 0x006900740070006FUL:
                    {
                        if (Read2(input, 4) == 0x006E006FU) return "option";
                        break;
                    }
                    case 0x006F007200740073UL:
                    {
                        if (Read2(input, 4) == 0x0067006EU) return "strong";
                        break;
                    }
                    case 0x0074007400750062UL:
                    {
                        if (Read2(input, 4) == 0x006E006FU) return "button";
                        break;
                    }
                }
                break;
            }
            case 7:
            {
                var chunk6 = Read4(input, 0);
                switch (chunk6)
                {
                    case 0x0074006300650073UL:
                    {
                        if (Read2(input, 4) == 0x006F0069U && (uint) input[6] == 0x006EU) return "section";
                        break;
                    }
                    case 0x0074006E006F0063UL:
                    {
                        if (Read2(input, 4) == 0x006E0065U && (uint) input[6] == 0x0074U) return "content";
                        break;
                    }
                }
                break;
            }
            case 8:
            {
                var chunk7 = Read4(input, 0);
                switch (chunk7)
                {
                    case 0x0070006D00650074UL:
                    {
                        if (Read4(input, 4) == 0x006500740061006CUL) return "template";
                        break;
                    }
                    case 0x0074007800650074UL:
                    {
                        if (Read4(input, 4) == 0x0061006500720061UL) return "textarea";
                        break;
                    }
                }
                break;
            }
        }
        return null;
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private static uint Read2(ReadOnlySpan<char> input, int offset)
    {
        var value = MemoryMarshal.Read<uint>(MemoryMarshal.AsBytes(input.Slice(offset, 2)));
        return BitConverter.IsLittleEndian ? value : (value << 16) | (value >> 16);
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private static ulong Read4(ReadOnlySpan<char> input, int offset)
    {
        var value = MemoryMarshal.Read<ulong>(MemoryMarshal.AsBytes(input.Slice(offset, 4)));
        return BitConverter.IsLittleEndian ? value
            : (value << 48) | ((value & 0xFFFF0000UL) << 16) |
              ((value >> 16) & 0xFFFF0000UL) | (value >> 48);
    }
}
