// Copyright 2009 the Sputnik authors.  All rights reserved.
/**
 * The depth of nested function calls reaches 32
 *
 * @path ch13/13.2/S13.2.1_A1_T1.js
 * @description Creating function calls 32 elements depth
 */

(function(){
    (function(){
        (function(){
            (function(){
                (function(){
                    (function(){
                        (function(){
                            (function(){
                                (function(){
                                    (function(){
                                        (function(){
                                            (function(){
                                                (function(){
                                                    (function(){
                                                        (function(){
                                                            (function(){
                                                                (function(){
                                                                    (function(){
                                                                        (function(){
                                                                            (function(){
                                                                                (function(){
                                                                                    (function(){
                                                                                        (function(){
                                                                                            (function(){
                                                                                                (function(){
                                                                                                    (function(){
                                                                                                        (function(){
                                                                                                            (function(){
                                                                                                                (function(){
                                                                                                                    (function(){
                                                                                                                        (function(){
                                                                                                                            (function(){})()
                                                                                                                        })()
                                                                                                                    })()
                                                                                                                })()
                                                                                                            })()
                                                                                                        })()
                                                                                                    })()
                                                                                                })()
                                                                                            })()
                                                                                        })()
                                                                                    })()
                                                                                })()
                                                                            })()
                                                                        })()
                                                                    })()
                                                                })()
                                                            })()
                                                        })()
                                                    })()
                                                })()
                                            })()
                                        })()
                                    })()
                                })()
                            })()
                        })()
                    })()
                })()
            })()
        })()
    })()
})()                            

