namespace Jint.HtmlParser.Css.Values.Colors;

// CSS Color 4 §6.1/§6.2 and Appendix A, Editor’s Draft 13 September 2026.
// Copyright © 2026 World Wide Web Consortium.
// Named RGB constants and system identities adapted from the W3C tables:
// https://drafts.csswg.org/css-color-4/ (W3C Document License,
// https://www.w3.org/copyright/document-license/). No environment palette is invented.
internal static class CssColorKeywords
{
    internal static IReadOnlyDictionary<string, uint> Named { get; } =
        new System.Collections.ObjectModel.ReadOnlyDictionary<string, uint>(
            new Dictionary<string, uint>(StringComparer.Ordinal)
            {
                ["aliceblue"] = 0xf0f8ffu,
                ["antiquewhite"] = 0xfaebd7u,
                ["aqua"] = 0x00ffffu,
                ["aquamarine"] = 0x7fffd4u,
                ["azure"] = 0xf0ffffu,
                ["beige"] = 0xf5f5dcu,
                ["bisque"] = 0xffe4c4u,
                ["black"] = 0x000000u,
                ["blanchedalmond"] = 0xffebcdu,
                ["blue"] = 0x0000ffu,
                ["blueviolet"] = 0x8a2be2u,
                ["brown"] = 0xa52a2au,
                ["burlywood"] = 0xdeb887u,
                ["cadetblue"] = 0x5f9ea0u,
                ["chartreuse"] = 0x7fff00u,
                ["chocolate"] = 0xd2691eu,
                ["coral"] = 0xff7f50u,
                ["cornflowerblue"] = 0x6495edu,
                ["cornsilk"] = 0xfff8dcu,
                ["crimson"] = 0xdc143cu,
                ["cyan"] = 0x00ffffu,
                ["darkblue"] = 0x00008bu,
                ["darkcyan"] = 0x008b8bu,
                ["darkgoldenrod"] = 0xb8860bu,
                ["darkgray"] = 0xa9a9a9u,
                ["darkgreen"] = 0x006400u,
                ["darkgrey"] = 0xa9a9a9u,
                ["darkkhaki"] = 0xbdb76bu,
                ["darkmagenta"] = 0x8b008bu,
                ["darkolivegreen"] = 0x556b2fu,
                ["darkorange"] = 0xff8c00u,
                ["darkorchid"] = 0x9932ccu,
                ["darkred"] = 0x8b0000u,
                ["darksalmon"] = 0xe9967au,
                ["darkseagreen"] = 0x8fbc8fu,
                ["darkslateblue"] = 0x483d8bu,
                ["darkslategray"] = 0x2f4f4fu,
                ["darkslategrey"] = 0x2f4f4fu,
                ["darkturquoise"] = 0x00ced1u,
                ["darkviolet"] = 0x9400d3u,
                ["deeppink"] = 0xff1493u,
                ["deepskyblue"] = 0x00bfffu,
                ["dimgray"] = 0x696969u,
                ["dimgrey"] = 0x696969u,
                ["dodgerblue"] = 0x1e90ffu,
                ["firebrick"] = 0xb22222u,
                ["floralwhite"] = 0xfffaf0u,
                ["forestgreen"] = 0x228b22u,
                ["fuchsia"] = 0xff00ffu,
                ["gainsboro"] = 0xdcdcdcu,
                ["ghostwhite"] = 0xf8f8ffu,
                ["gold"] = 0xffd700u,
                ["goldenrod"] = 0xdaa520u,
                ["gray"] = 0x808080u,
                ["green"] = 0x008000u,
                ["greenyellow"] = 0xadff2fu,
                ["grey"] = 0x808080u,
                ["honeydew"] = 0xf0fff0u,
                ["hotpink"] = 0xff69b4u,
                ["indianred"] = 0xcd5c5cu,
                ["indigo"] = 0x4b0082u,
                ["ivory"] = 0xfffff0u,
                ["khaki"] = 0xf0e68cu,
                ["lavender"] = 0xe6e6fau,
                ["lavenderblush"] = 0xfff0f5u,
                ["lawngreen"] = 0x7cfc00u,
                ["lemonchiffon"] = 0xfffacdu,
                ["lightblue"] = 0xadd8e6u,
                ["lightcoral"] = 0xf08080u,
                ["lightcyan"] = 0xe0ffffu,
                ["lightgoldenrodyellow"] = 0xfafad2u,
                ["lightgray"] = 0xd3d3d3u,
                ["lightgreen"] = 0x90ee90u,
                ["lightgrey"] = 0xd3d3d3u,
                ["lightpink"] = 0xffb6c1u,
                ["lightsalmon"] = 0xffa07au,
                ["lightseagreen"] = 0x20b2aau,
                ["lightskyblue"] = 0x87cefau,
                ["lightslategray"] = 0x778899u,
                ["lightslategrey"] = 0x778899u,
                ["lightsteelblue"] = 0xb0c4deu,
                ["lightyellow"] = 0xffffe0u,
                ["lime"] = 0x00ff00u,
                ["limegreen"] = 0x32cd32u,
                ["linen"] = 0xfaf0e6u,
                ["magenta"] = 0xff00ffu,
                ["maroon"] = 0x800000u,
                ["mediumaquamarine"] = 0x66cdaau,
                ["mediumblue"] = 0x0000cdu,
                ["mediumorchid"] = 0xba55d3u,
                ["mediumpurple"] = 0x9370dbu,
                ["mediumseagreen"] = 0x3cb371u,
                ["mediumslateblue"] = 0x7b68eeu,
                ["mediumspringgreen"] = 0x00fa9au,
                ["mediumturquoise"] = 0x48d1ccu,
                ["mediumvioletred"] = 0xc71585u,
                ["midnightblue"] = 0x191970u,
                ["mintcream"] = 0xf5fffau,
                ["mistyrose"] = 0xffe4e1u,
                ["moccasin"] = 0xffe4b5u,
                ["navajowhite"] = 0xffdeadu,
                ["navy"] = 0x000080u,
                ["oldlace"] = 0xfdf5e6u,
                ["olive"] = 0x808000u,
                ["olivedrab"] = 0x6b8e23u,
                ["orange"] = 0xffa500u,
                ["orangered"] = 0xff4500u,
                ["orchid"] = 0xda70d6u,
                ["palegoldenrod"] = 0xeee8aau,
                ["palegreen"] = 0x98fb98u,
                ["paleturquoise"] = 0xafeeeeu,
                ["palevioletred"] = 0xdb7093u,
                ["papayawhip"] = 0xffefd5u,
                ["peachpuff"] = 0xffdab9u,
                ["peru"] = 0xcd853fu,
                ["pink"] = 0xffc0cbu,
                ["plum"] = 0xdda0ddu,
                ["powderblue"] = 0xb0e0e6u,
                ["purple"] = 0x800080u,
                ["rebeccapurple"] = 0x663399u,
                ["red"] = 0xff0000u,
                ["rosybrown"] = 0xbc8f8fu,
                ["royalblue"] = 0x4169e1u,
                ["saddlebrown"] = 0x8b4513u,
                ["salmon"] = 0xfa8072u,
                ["sandybrown"] = 0xf4a460u,
                ["seagreen"] = 0x2e8b57u,
                ["seashell"] = 0xfff5eeu,
                ["sienna"] = 0xa0522du,
                ["silver"] = 0xc0c0c0u,
                ["skyblue"] = 0x87ceebu,
                ["slateblue"] = 0x6a5acdu,
                ["slategray"] = 0x708090u,
                ["slategrey"] = 0x708090u,
                ["snow"] = 0xfffafau,
                ["springgreen"] = 0x00ff7fu,
                ["steelblue"] = 0x4682b4u,
                ["tan"] = 0xd2b48cu,
                ["teal"] = 0x008080u,
                ["thistle"] = 0xd8bfd8u,
                ["tomato"] = 0xff6347u,
                ["turquoise"] = 0x40e0d0u,
                ["violet"] = 0xee82eeu,
                ["wheat"] = 0xf5deb3u,
                ["white"] = 0xffffffu,
                ["whitesmoke"] = 0xf5f5f5u,
                ["yellow"] = 0xffff00u,
                ["yellowgreen"] = 0x9acd32u,
            });

    internal static CssColorKind? ContextualKind(string name) => name switch
    {
        "transparent" => CssColorKind.Transparent,
        "currentcolor" => CssColorKind.CurrentColor,
        "accentcolor" or "accentcolortext" or "activetext" or "buttonborder" or "buttonface" or "buttontext" or "canvas" or "canvastext" or "field" or "fieldtext" or "graytext" or "highlight" or "highlighttext" or "linktext" or "mark" or "marktext" or "selecteditem" or "selecteditemtext" or "visitedtext" => CssColorKind.System,
        "activeborder" or "activecaption" or "appworkspace" or "background" or "buttonhighlight" or "buttonshadow" or "captiontext" or "inactiveborder" or "inactivecaption" or "inactivecaptiontext" or "infobackground" or "infotext" or "menu" or "menutext" or "scrollbar" or "threeddarkshadow" or "threedface" or "threedhighlight" or "threedlightshadow" or "threedshadow" or "window" or "windowframe" or "windowtext" => CssColorKind.DeprecatedSystem,
        _ => null
    };
}
