using System.Text;

namespace Jint.SourceGenerators;

internal static class AccessibleEmitter
{
    public static string Emit(AccessibleTypeDefinition def)
    {
        var sb = new StringBuilder(2048);
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("namespace Jint.Runtime.Interop.Generated;");
        sb.AppendLine();

        var safe = SanitizeName(def.SafeId);
        EmitRegistration(sb, def, safe);
        sb.AppendLine();

        foreach (var prop in def.Properties)
        {
            EmitPropertyAccessor(sb, def, safe, prop);
            sb.AppendLine();
        }

        foreach (var method in def.Methods)
        {
            EmitMethodAccessor(sb, def, safe, method);
            sb.AppendLine();
        }

        return sb.ToString();
    }

    private static void EmitRegistration(StringBuilder sb, AccessibleTypeDefinition def, string safe)
    {
        sb.AppendLine($"internal static class {safe}_JsAccessibleRegistration");
        sb.AppendLine("{");
        sb.AppendLine("    [global::System.Runtime.CompilerServices.ModuleInitializer]");
        sb.AppendLine("    internal static void Register()");
        sb.AppendLine("    {");
        foreach (var prop in def.Properties)
        {
            sb.AppendLine($"        global::Jint.Runtime.Interop.GeneratedAccessorRegistry.Register(typeof({def.FullyQualifiedName}), \"{prop.Name}\", new {safe}_{prop.Name}_Accessor());");
        }
        foreach (var method in def.Methods)
        {
            sb.AppendLine($"        global::Jint.Runtime.Interop.GeneratedAccessorRegistry.Register(typeof({def.FullyQualifiedName}), \"{method.Name}\", new {safe}_{method.Name}_Accessor());");
        }
        sb.AppendLine("    }");
        sb.AppendLine("}");
    }

    private static void EmitPropertyAccessor(StringBuilder sb, AccessibleTypeDefinition def, string safe, AccessibleProperty prop)
    {
        sb.AppendLine($"internal sealed class {safe}_{prop.Name}_Accessor : global::Jint.Runtime.Interop.Reflection.GeneratedReflectionAccessor");
        sb.AppendLine("{");
        sb.AppendLine($"    public {safe}_{prop.Name}_Accessor() : base(typeof({prop.TypeFqn})) {{ }}");
        sb.AppendLine();
        sb.AppendLine($"    public override bool Readable => {(prop.CanGet ? "true" : "false")};");
        sb.AppendLine($"    public override bool Writable => {(prop.CanSet ? "true" : "false")};");
        sb.AppendLine();
        sb.AppendLine("    public override global::Jint.Native.JsValue GetJsValue(global::Jint.Engine engine, object target)");
        sb.AppendLine("    {");
        if (prop.CanGet)
        {
            sb.AppendLine($"        var __t = (({def.FullyQualifiedName})target);");
            sb.AppendLine($"        var __v = __t.{prop.Name};");
            sb.Append("        return ");
            sb.AppendLine(EmitToJsValue(prop.ValueType, "__v") + ";");
        }
        else
        {
            sb.AppendLine("        return global::Jint.Native.JsValue.Undefined;");
        }
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    public override void SetFromJsValue(global::Jint.Engine engine, object target, global::Jint.Native.JsValue value)");
        sb.AppendLine("    {");
        if (prop.CanSet)
        {
            sb.AppendLine($"        var __t = (({def.FullyQualifiedName})target);");
            sb.Append($"        __t.{prop.Name} = ");
            sb.AppendLine(EmitFromJsValue(prop.ValueType, prop.TypeFqn, "value") + ";");
        }
        sb.AppendLine("    }");
        sb.AppendLine("}");
    }

    private static void EmitMethodAccessor(StringBuilder sb, AccessibleTypeDefinition def, string safe, AccessibleMethod method)
    {
        // GeneratedMethodAccessor + nested Function subclass.
        sb.AppendLine($"internal sealed class {safe}_{method.Name}_Accessor : global::Jint.Runtime.Interop.Reflection.GeneratedMethodAccessor");
        sb.AppendLine("{");
        sb.AppendLine("    protected override global::Jint.Native.Function.Function CreateFunction(global::Jint.Engine engine, object target, string memberName)");
        sb.AppendLine($"        => new {safe}_{method.Name}_Function(engine, ({def.FullyQualifiedName})target);");
        sb.AppendLine("}");
        sb.AppendLine();

        sb.AppendLine($"internal sealed class {safe}_{method.Name}_Function : global::Jint.Native.Function.Function");
        sb.AppendLine("{");
        sb.AppendLine($"    private readonly {def.FullyQualifiedName} _target;");
        sb.AppendLine();
        sb.AppendLine($"    public {safe}_{method.Name}_Function(global::Jint.Engine engine, {def.FullyQualifiedName} target)");
        sb.AppendLine($"        : base(engine, engine.Realm, new global::Jint.Native.JsString(\"{method.Name}\"))");
        sb.AppendLine("    {");
        sb.AppendLine("        _target = target;");
        sb.AppendLine("        _prototype = engine.Realm.Intrinsics.Function.PrototypeObject;");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    protected internal override global::Jint.Native.JsValue Call(global::Jint.Native.JsValue thisObject, global::Jint.Native.JsValue[] arguments)");
        sb.AppendLine("    {");
        if (method.ParameterType.HasValue)
        {
            sb.AppendLine("        var __arg0 = arguments.Length > 0 ? arguments[0] : global::Jint.Native.JsValue.Undefined;");
            sb.Append($"        var __p0 = ");
            sb.AppendLine(EmitFromJsValue(method.ParameterType.Value, method.ParameterTypeFqn!, "__arg0") + ";");
            sb.AppendLine($"        var __r = _target.{method.Name}(__p0);");
        }
        else if (method.ReturnType == AccessibleType.Void)
        {
            sb.AppendLine($"        _target.{method.Name}();");
        }
        else
        {
            sb.AppendLine($"        var __r = _target.{method.Name}();");
        }

        if (method.ReturnType == AccessibleType.Void)
        {
            sb.AppendLine("        return global::Jint.Native.JsValue.Undefined;");
        }
        else
        {
            sb.Append("        return ");
            sb.AppendLine(EmitToJsValue(method.ReturnType, "__r") + ";");
        }

        sb.AppendLine("    }");
        sb.AppendLine("}");
    }

    private static string EmitToJsValue(AccessibleType type, string expr) => type switch
    {
        AccessibleType.Int32 => $"global::Jint.Native.JsNumber.Create({expr})",
        AccessibleType.Double => $"global::Jint.Native.JsNumber.Create({expr})",
        AccessibleType.Boolean => $"({expr}) ? global::Jint.Native.JsBoolean.True : global::Jint.Native.JsBoolean.False",
        AccessibleType.String => $"({expr}) is null ? (global::Jint.Native.JsValue)global::Jint.Native.JsValue.Null : global::Jint.Native.JsString.Create({expr})",
        AccessibleType.JsValue => $"({expr}) ?? global::Jint.Native.JsValue.Undefined",
        _ => "global::Jint.Native.JsValue.Undefined",
    };

    private static string EmitFromJsValue(AccessibleType type, string typeFqn, string expr) => type switch
    {
        AccessibleType.Int32 => $"global::Jint.Runtime.TypeConverter.ToInt32({expr})",
        AccessibleType.Double => $"global::Jint.Runtime.TypeConverter.ToNumber({expr})",
        AccessibleType.Boolean => $"global::Jint.Runtime.TypeConverter.ToBoolean({expr})",
        AccessibleType.String => $"global::Jint.Runtime.TypeConverter.ToString({expr})",
        AccessibleType.JsValue => $"({typeFqn})({expr})",
        _ => $"default({typeFqn})!",
    };

    private static string SanitizeName(string id)
    {
        // Replace any character not valid in a C# identifier.
        var sb = new StringBuilder(id.Length);
        foreach (var ch in id)
        {
            if (char.IsLetterOrDigit(ch) || ch == '_') sb.Append(ch);
            else sb.Append('_');
        }
        return sb.ToString();
    }
}
