namespace Jint.SourceGenerators;

internal static class Attributes
{
    public const string Source = """
        // <auto-generated/>
        #nullable enable

        namespace Jint;

        [global::System.AttributeUsage(global::System.AttributeTargets.Class)]
        [global::System.Diagnostics.Conditional("JINT_SOURCE_GENERATORS")]
        internal sealed class JsObjectAttribute : global::System.Attribute
        {
            /// <summary>
            /// Extra capacity to add to the generated property dictionary's initial size, on top of the
            /// statically declared [JsFunction]/[JsAccessor]/[JsProperty] entries. Use when the host's
            /// Initialize() body adds further properties post-CreateProperties_Generated() (e.g. cross-realm
            /// constructor references in IntlInstance / TemporalInstance) — presizes the HybridDictionary
            /// to avoid the list→hash transition during init.
            /// </summary>
            public int ExtraCapacity { get; set; }

            /// <summary>
            /// Built-in shape storage (a shared immutable BuiltinShape plus a per-realm lazily-filled
            /// descriptor array instead of a per-realm property dictionary) is used <b>by default</b> for any
            /// host that derives from <c>BuiltinShapeObject</c> — deriving from it is the opt-in. Set this to
            /// <c>false</c> to opt a derived host back out to the dictionary path. Hosts that do not derive
            /// from <c>BuiltinShapeObject</c> always use the dictionary path regardless of this flag.
            /// Supported members: [JsFunction]s, static-immutable [JsProperty] constants, and symbols. See
            /// BuiltinShapeObject.
            /// </summary>
            public bool UseShape { get; set; } = true;
        }

        [global::System.AttributeUsage(global::System.AttributeTargets.Method)]
        [global::System.Diagnostics.Conditional("JINT_SOURCE_GENERATORS")]
        internal sealed class JsFunctionAttribute : global::System.Attribute
        {
            public string? Name { get; set; }
            public int Length { get; set; } = -1;

            // CaptureField optionally names a host field (or settable property) assigned the
            // materialized function — the SAME instance the object hands out for the key, forced
            // into existence via GetOwnProperty at the end of CreateProperties_Generated — for
            // ReferenceEquals fast paths such as ArrayIteratorPrototype._originalNextFunction and
            // WeakSetPrototype.OriginalAddFunction.
            public string? CaptureField { get; set; }

            /// <summary>
            /// Opt in to the arity-specialized invoke (<c>Function.CallFast</c>): the call site passes
            /// arguments in registers instead of renting a pooled <c>JsValue[]</c>, and jumps straight
            /// at the target instead of going through the generated <c>switch (_slot)</c>. The
            /// call-stack frame is still pushed, so this is semantics-preserving for ANY built-in —
            /// including ones that throw or re-enter user code.
            /// <para>
            /// Requires a positionally expressible signature: at most two declared value parameters,
            /// no raw <c>JsCallArguments</c> and no <c>[ArgCount]</c> (CallFast carries no arity to
            /// hand it). A <c>[Rest]</c> tail is expressible — such a method is dispatched through
            /// <c>Function.CallFastVariadic</c>, which carries a span whose length is the call site's
            /// statically known arity, and simply declines the arities that overflow the registers.
            /// Anything the generator cannot honor is reported as JINT023 rather than silently
            /// ignored.
            /// </para>
            /// </summary>
            public bool FastCall { get; set; }

            /// <summary>
            /// Opt in to frame elision on top of <see cref="FastCall"/> (which this implies). Only
            /// declare it when the body provably runs no user code and raises no JavaScript error
            /// once every <see cref="global::Jint.Native.Function.FastCallGuard"/> the generator
            /// derives from the declaration holds — user code reached through a coercion can observe
            /// <c>error.stack</c>, and a missing frame would be visible there.
            /// <para>
            /// Guards come from the declaration, never from inference: a coercion attribute
            /// (<c>[ToNumber]</c>, <c>[ToInteger]</c>, <c>[ToInt32]</c>, <c>[ToUint32]</c>,
            /// <c>[ToLength]</c>) contributes a Number guard, <c>[ToString]</c>/<c>[ToJsString]</c>
            /// contribute a String guard, and a cast <c>thisObject</c> contributes the guard matching
            /// its type. A plain <c>JsValue</c> value parameter derives no guard and is therefore
            /// rejected outright (JINT023) unless the declaration supplies one through
            /// <see cref="LeafArg0"/>/<see cref="LeafArg1"/>: the generator cannot see whether the
            /// body coerces it, and a body that does would run user code frameless.
            /// </para>
            /// <para>
            /// This is never inferred from the signature, because a body with perfectly numeric
            /// parameters can still <c>Throw.RangeError</c>.
            /// </para>
            /// </summary>
            public bool Leaf { get; set; }

            /// <summary>
            /// Declares the receiver precondition under which <see cref="Leaf"/> holds, for methods
            /// whose 'this' stays untyped because they legitimately accept any coercible receiver.
            /// The frameless lane is then taken only when the receiver actually matches at runtime;
            /// every other receiver keeps its frame and its exact semantics. This is what lets a
            /// String.prototype method be leaf for a primitive string without giving up boxed or
            /// object receivers, which coerce through user code and must stay framed.
            /// </summary>
            public global::Jint.Native.Function.FastCallGuard LeafReceiver { get; set; }

            /// <summary>
            /// Declares the precondition under which <see cref="Leaf"/> holds for the first declared
            /// value parameter, for a body that takes it as a plain <c>JsValue</c> and coerces it
            /// itself. Without one such a parameter blocks <see cref="Leaf"/> outright, because the
            /// generator cannot see the coercion; with one, the frameless lane is taken only for
            /// values the declaration names, and every other value keeps its frame and its exact
            /// semantics — which is what makes a <c>String.prototype</c> method leaf for a number
            /// without letting an object's <c>valueOf</c> anywhere near the frameless window.
            /// <para>
            /// Include <c>FastCallGuard.Undefined</c> when the body is also safe for an omitted
            /// argument; the call site pads the registers with <c>undefined</c>, so a Number-only
            /// guard silently costs the lane every call site that omits the argument.
            /// </para>
            /// <para>
            /// Only consulted for a parameter that derives no guard of its own. A declared conversion
            /// already carries one, and an explicit value must never be able to weaken it — the same
            /// rule <see cref="LeafReceiver"/> follows.
            /// </para>
            /// </summary>
            public global::Jint.Native.Function.FastCallGuard LeafArg0 { get; set; }

            /// <summary><see cref="LeafArg0"/> for the second declared value parameter.</summary>
            public global::Jint.Native.Function.FastCallGuard LeafArg1 { get; set; }
        }

        [global::System.AttributeUsage(global::System.AttributeTargets.Field | global::System.AttributeTargets.Property)]
        [global::System.Diagnostics.Conditional("JINT_SOURCE_GENERATORS")]
        internal sealed class JsPropertyAttribute : global::System.Attribute
        {
            public string? Name { get; set; }
            public global::Jint.Runtime.Descriptors.PropertyFlag Flags { get; set; } = global::Jint.Runtime.Descriptors.PropertyFlag.AllForbidden;
        }

        [global::System.AttributeUsage(global::System.AttributeTargets.Parameter)]
        [global::System.Diagnostics.Conditional("JINT_SOURCE_GENERATORS")]
        internal sealed class RestAttribute : global::System.Attribute
        {
        }

        // Marks a parameter as receiving the result of a TypeConverter.ToXxx coercion of arguments[N].
        // The CLR parameter type must match the converter's return type (double for ToNumber, int for
        // ToInt32, uint for ToUint32). The generator emits the conversion at the dispatcher boundary.

        [global::System.AttributeUsage(global::System.AttributeTargets.Parameter)]
        [global::System.Diagnostics.Conditional("JINT_SOURCE_GENERATORS")]
        internal sealed class ToNumberAttribute : global::System.Attribute { }

        [global::System.AttributeUsage(global::System.AttributeTargets.Parameter)]
        [global::System.Diagnostics.Conditional("JINT_SOURCE_GENERATORS")]
        internal sealed class ToInt32Attribute : global::System.Attribute { }

        [global::System.AttributeUsage(global::System.AttributeTargets.Parameter)]
        [global::System.Diagnostics.Conditional("JINT_SOURCE_GENERATORS")]
        internal sealed class ToUint32Attribute : global::System.Attribute { }

        [global::System.AttributeUsage(global::System.AttributeTargets.Parameter)]
        [global::System.Diagnostics.Conditional("JINT_SOURCE_GENERATORS")]
        internal sealed class ToIntegerAttribute : global::System.Attribute { }

        [global::System.AttributeUsage(global::System.AttributeTargets.Parameter)]
        [global::System.Diagnostics.Conditional("JINT_SOURCE_GENERATORS")]
        internal sealed class ToLengthAttribute : global::System.Attribute { }

        [global::System.AttributeUsage(global::System.AttributeTargets.Parameter)]
        [global::System.Diagnostics.Conditional("JINT_SOURCE_GENERATORS")]
        internal sealed class ToStringAttribute : global::System.Attribute { }

        [global::System.AttributeUsage(global::System.AttributeTargets.Parameter)]
        [global::System.Diagnostics.Conditional("JINT_SOURCE_GENERATORS")]
        internal sealed class ToJsStringAttribute : global::System.Attribute { }

        [global::System.AttributeUsage(global::System.AttributeTargets.Parameter)]
        [global::System.Diagnostics.Conditional("JINT_SOURCE_GENERATORS")]
        internal sealed class ToObjectAttribute : global::System.Attribute { }

        // Marks an `int` pseudo-parameter that receives the caller's argument count. It exists so a
        // body that must distinguish an ABSENT argument from an explicitly passed `undefined` can
        // still declare its real parameters positionally instead of taking the raw JsCallArguments
        // array. Two spec shapes need it:
        //   * the Date setters — "arguments.Length <= 1 ? MsFromTime(t) : ToNumber(arg1)", i.e.
        //     an omitted field keeps its current value while an explicit undefined poisons it to NaN;
        //   * the reduce family — "if (argc < 2) throw" distinguishing a missing initial value from
        //     a supplied `undefined` one.
        // The parameter does NOT count toward the JS-visible `length`, and may appear at any position
        // after `thisObject`.
        //
        // A method declaring [ArgCount] cannot opt into JsFunction.FastCall: Function.CallFast
        // carries a receiver and two argument registers but no arity, so an argument count simply
        // cannot be conveyed through it (JINT023).
        [global::System.AttributeUsage(global::System.AttributeTargets.Parameter)]
        [global::System.Diagnostics.Conditional("JINT_SOURCE_GENERATORS")]
        internal sealed class ArgCountAttribute : global::System.Attribute { }

        // Marks a [JsFunction]/[JsSymbolFunction] method whose dispatcher should call
        // TypeConverter.RequireObjectCoercible(_host._engine, thisObject) before invoking the user method.
        // Common pattern for String and Array prototype methods that require 'this' to be defined/non-null.
        [global::System.AttributeUsage(global::System.AttributeTargets.Method)]
        [global::System.Diagnostics.Conditional("JINT_SOURCE_GENERATORS")]
        internal sealed class RequireObjectCoercibleAttribute : global::System.Attribute { }

        [global::System.AttributeUsage(global::System.AttributeTargets.Field | global::System.AttributeTargets.Property)]
        [global::System.Diagnostics.Conditional("JINT_SOURCE_GENERATORS")]
        internal sealed class JsSymbolAttribute : global::System.Attribute
        {
            public JsSymbolAttribute(string symbolName)
            {
                SymbolName = symbolName;
            }

            public string SymbolName { get; }
            public global::Jint.Runtime.Descriptors.PropertyFlag Flags { get; set; } = global::Jint.Runtime.Descriptors.PropertyFlag.Configurable;
        }

        internal enum AccessorKind { Get, Set }

        // Pairs by Name on the same class. The CLR method takes the standard JsValue thisObject + value
        // parameters; the generator emits a GetSetPropertyDescriptor wrapping both halves and an entry
        // per method in the per-host dispatcher.
        [global::System.AttributeUsage(global::System.AttributeTargets.Method, AllowMultiple = false)]
        [global::System.Diagnostics.Conditional("JINT_SOURCE_GENERATORS")]
        internal sealed class JsAccessorAttribute : global::System.Attribute
        {
            public JsAccessorAttribute(string name, AccessorKind kind = AccessorKind.Get)
            {
                Name = name;
                Kind = kind;
            }

            public string Name { get; }
            public AccessorKind Kind { get; }
            public global::Jint.Runtime.Descriptors.PropertyFlag Flags { get; set; } = global::Jint.Runtime.Descriptors.PropertyFlag.Configurable;
        }

        // Class-level, repeats. Each one registers a single shared ThrowerPropertyDescriptor on the host
        // under the named key. Used for FunctionPrototype's "arguments" and "caller".
        [global::System.AttributeUsage(global::System.AttributeTargets.Class, AllowMultiple = true)]
        [global::System.Diagnostics.Conditional("JINT_SOURCE_GENERATORS")]
        internal sealed class JsThrowerAccessorAttribute : global::System.Attribute
        {
            public JsThrowerAccessorAttribute(string name) { Name = name; }
            public string Name { get; }
            public global::Jint.Runtime.Descriptors.PropertyFlag Flags { get; set; } = global::Jint.Runtime.Descriptors.PropertyFlag.Configurable;
        }

        // Class-level, repeats. Registers a lazy property descriptor that resolves to
        // host._realm.Intrinsics.<IntrinsicMember> on first read. Same shape as a [JsFunction] lazy
        // descriptor — Function objects allocate on first access only — but the value source is the
        // realm's intrinsic constructor object instead of a generated dispatcher. Used by GlobalObject
        // to expose the ~50 constructor properties (Array, Object, JSON, etc.) without eagerly
        // resolving every realm intrinsic during Initialize.
        // IntrinsicMember defaults to JsName; override for casing/name mismatches:
        //   [JsIntrinsicReference("JSON", IntrinsicMember = "Json")]
        //   [JsIntrinsicReference("URIError", IntrinsicMember = "UriError")]
        //   [JsIntrinsicReference("Generator", IntrinsicMember = "GeneratorFunction")]
        //   [JsIntrinsicReference("eval", IntrinsicMember = "Eval")]
        // Requires the host to have an accessible Realm-typed _realm field (same JINT018 constraint as
        // a method that casts thisObject).
        [global::System.AttributeUsage(global::System.AttributeTargets.Class, AllowMultiple = true)]
        [global::System.Diagnostics.Conditional("JINT_SOURCE_GENERATORS")]
        internal sealed class JsIntrinsicReferenceAttribute : global::System.Attribute
        {
            public JsIntrinsicReferenceAttribute(string jsName) { JsName = jsName; }
            public string JsName { get; }
            public string? IntrinsicMember { get; set; }
            public global::Jint.Runtime.Descriptors.PropertyFlag Flags { get; set; } = global::Jint.Runtime.Descriptors.PropertyFlag.Configurable | global::Jint.Runtime.Descriptors.PropertyFlag.Writable;
        }

        // Like [JsFunction] but registers in SymbolDictionary instead of PropertyDictionary.
        // SymbolName must match a static property on Jint.Native.Symbol.GlobalSymbolRegistry.
        // CaptureField optionally names a host field assigned the dispatcher Function for
        // ReferenceEquals fast paths (e.g. StringPrototype._originalIteratorFunction); setting it
        // makes the member EAGER — the Function is constructed inside CreateSymbols_Generated and
        // that same instance is both captured and registered under the symbol, matching the
        // hand-written eager tails it replaces.
        [global::System.AttributeUsage(global::System.AttributeTargets.Method)]
        [global::System.Diagnostics.Conditional("JINT_SOURCE_GENERATORS")]
        internal sealed class JsSymbolFunctionAttribute : global::System.Attribute
        {
            public JsSymbolFunctionAttribute(string symbolName) { SymbolName = symbolName; }
            public string SymbolName { get; }
            public int Length { get; set; } = -1;
            public global::Jint.Runtime.Descriptors.PropertyFlag Flags { get; set; } = global::Jint.Runtime.Descriptors.PropertyFlag.AllForbidden;
            public string? CaptureField { get; set; }
        }

        // Symbol-keyed accessor: pairs by SymbolName on the same class. Get and Set halves emit one
        // GetSetPropertyDescriptor wrapping eagerly-allocated dispatcher slots, registered under
        // GlobalSymbolRegistry.<SymbolName>. Most commonly used for "@@species" getters.
        [global::System.AttributeUsage(global::System.AttributeTargets.Method, AllowMultiple = false)]
        [global::System.Diagnostics.Conditional("JINT_SOURCE_GENERATORS")]
        internal sealed class JsSymbolAccessorAttribute : global::System.Attribute
        {
            public JsSymbolAccessorAttribute(string symbolName, AccessorKind kind = AccessorKind.Get)
            {
                SymbolName = symbolName;
                Kind = kind;
            }

            public string SymbolName { get; }
            public AccessorKind Kind { get; }
            public global::Jint.Runtime.Descriptors.PropertyFlag Flags { get; set; } = global::Jint.Runtime.Descriptors.PropertyFlag.Configurable;
        }

        // Class-level, repeats. Registers a string own property <Name> that shares the descriptor of another
        // generated [JsFunction] member <Target> (which must exist on the same host), so the two names resolve
        // to the very same function object — the spec function-identity aliases, e.g.
        //   [JsAlias("keys", "values")]       // Set.prototype.keys === values
        //   [JsAlias("trimLeft", "trimStart")]
        //   [JsAlias("toGMTString", "toUTCString")]
        // The alias appears after all other own properties in own-key order (matching the hand-written
        // AddDangerous/SetProperty tail it replaces).
        [global::System.AttributeUsage(global::System.AttributeTargets.Class, AllowMultiple = true)]
        [global::System.Diagnostics.Conditional("JINT_SOURCE_GENERATORS")]
        internal sealed class JsAliasAttribute : global::System.Attribute
        {
            public JsAliasAttribute(string name, string target)
            {
                Name = name;
                Target = target;
            }

            public string Name { get; }
            public string Target { get; }
        }

        // Class-level, repeats. Reserves a per-realm own-property slot (appended after all other own
        // properties, matching a hand-written SetProperty/AddDangerous tail) that the host fills in
        // Initialize via SetBuiltinSlotByName(name, descriptor) — for a computed/lazy value the generator
        // can't express, e.g. %TypedArray%.prototype.toString aliasing %Array.prototype.toString% lazily.
        // Shape hosts only (a non-shaped host just SetProperty()s the value in Initialize as before).
        [global::System.AttributeUsage(global::System.AttributeTargets.Class, AllowMultiple = true)]
        [global::System.Diagnostics.Conditional("JINT_SOURCE_GENERATORS")]
        internal sealed class JsInstanceSlotAttribute : global::System.Attribute
        {
            public JsInstanceSlotAttribute(string name) { Name = name; }
            public string Name { get; }
        }

        // Class-level, repeats. Registers a symbol-keyed own property under
        // GlobalSymbolRegistry.<SymbolName> whose value is the SAME function object as the generated
        // string-keyed [JsFunction] member <Target> — the spec symbol-identity aliases, e.g.
        //   [JsSymbolAlias("Iterator", "values")]   // Array.prototype[Symbol.iterator] === values
        // The target's descriptor is materialized eagerly inside CreateSymbols_Generated (call it
        // after CreateProperties_Generated), matching the hand-written tails this replaces.
        // CaptureField optionally names a host field assigned the materialized function, for
        // identity fast paths such as ArrayPrototype._originalIteratorFunction.
        [global::System.AttributeUsage(global::System.AttributeTargets.Class, AllowMultiple = true)]
        [global::System.Diagnostics.Conditional("JINT_SOURCE_GENERATORS")]
        internal sealed class JsSymbolAliasAttribute : global::System.Attribute
        {
            public JsSymbolAliasAttribute(string symbolName, string target)
            {
                SymbolName = symbolName;
                Target = target;
            }

            public string SymbolName { get; }
            public string Target { get; }
            public string? CaptureField { get; set; }
            public global::Jint.Runtime.Descriptors.PropertyFlag Flags { get; set; } = global::Jint.Runtime.Descriptors.PropertyFlag.Configurable | global::Jint.Runtime.Descriptors.PropertyFlag.Writable;
        }

        """;
}
