using System.Text;

namespace Jint.SourceGenerators;

internal static class Emitter
{
    public static string Emit(ObjectDefinition obj)
    {
        var sb = new StringBuilder(4096);

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();

        var hasNs = !string.IsNullOrEmpty(obj.Namespace);
        if (hasNs)
        {
            sb.Append("namespace ").Append(obj.Namespace).AppendLine(";");
            sb.AppendLine();
        }

        sb.Append(obj.Accessibility).Append(" ");
        if (obj.IsSealed) sb.Append("sealed ");
        sb.Append("partial class ").AppendLine(obj.Name);
        sb.AppendLine("{");

        EmitInitialize(sb, obj);

        if (obj.Symbols.Count > 0)
        {
            sb.AppendLine();
            EmitSymbolInitialize(sb, obj);
        }

        if (obj.Functions.Count > 0)
        {
            sb.AppendLine();
            EmitDispatcher(sb, obj);
        }

        sb.AppendLine("}");
        return sb.ToString();
    }

    private static void EmitInitialize(StringBuilder sb, ObjectDefinition obj)
    {
        var totalEntries = obj.Functions.Count + obj.Properties.Count;

        sb.AppendLine("    /// <summary>Generated property registration. Call from <c>Initialize()</c>.</summary>");
        sb.AppendLine("    private void CreateProperties_Generated()");
        sb.AppendLine("    {");

        if (totalEntries == 0)
        {
            sb.AppendLine("        // no [JsFunction] or [JsProperty] members");
            sb.AppendLine("    }");
            return;
        }

        sb.Append("        var properties = new global::Jint.Collections.HybridDictionary<global::Jint.Runtime.Descriptors.PropertyDescriptor>(")
          .Append(totalEntries)
          .AppendLine(", checkExistingKeys: false);");

        foreach (var prop in obj.Properties)
        {
            sb.Append("        properties[\"").Append(EscapeStringLit(prop.JsName)).Append("\"] = new global::Jint.Runtime.Descriptors.PropertyDescriptor(");
            if (prop.IsStatic) sb.Append(obj.Name).Append('.');
            sb.Append(prop.ClrName).Append(", ");
            sb.Append(prop.FlagsExpression);
            sb.AppendLine(");");
        }

        foreach (var fn in obj.Functions)
        {
            sb.Append("        properties[\"").Append(EscapeStringLit(fn.JsName)).Append("\"] = new global::Jint.Runtime.Descriptors.Specialized.LazyPropertyDescriptor<")
              .Append(obj.Name).Append(">(this, static host => new __").Append(obj.Name).Append("Function(host, __")
              .Append(obj.Name).Append("Function.Slot.").Append(fn.ClrName).AppendLine("), global::Jint.Runtime.Descriptors.PropertyFlag.NonEnumerable);");
        }

        sb.AppendLine("        SetProperties(properties);");
        sb.AppendLine("    }");
    }

    private static void EmitDispatcher(StringBuilder sb, ObjectDefinition obj)
    {
        var typeName = "__" + obj.Name + "Function";

        sb.Append("    private sealed class ").Append(typeName).AppendLine(" : global::Jint.Native.Function.Function");
        sb.AppendLine("    {");
        sb.AppendLine("        internal enum Slot : ushort");
        sb.AppendLine("        {");
        foreach (var fn in obj.Functions)
        {
            sb.Append("            ").Append(fn.ClrName).AppendLine(",");
        }
        sb.AppendLine("        }");
        sb.AppendLine();

        sb.Append("        private readonly ").Append(obj.Name).AppendLine(" _host;");
        sb.AppendLine("        private readonly Slot _slot;");
        sb.AppendLine();

        sb.Append("        internal ").Append(typeName).Append("(").Append(obj.Name).AppendLine(" host, Slot slot)");
        sb.AppendLine("            : base(host.Engine, host.Engine.Realm, GetName(slot))");
        sb.AppendLine("        {");
        sb.AppendLine("            _host = host;");
        sb.AppendLine("            _slot = slot;");
        sb.AppendLine("            _prototype = host.Engine.Realm.Intrinsics.Function.PrototypeObject;");
        sb.AppendLine("            _length = new global::Jint.Runtime.Descriptors.PropertyDescriptor(global::Jint.Native.JsNumber.Create(GetLength(slot)), global::Jint.Runtime.Descriptors.PropertyFlag.Configurable);");
        sb.AppendLine("        }");
        sb.AppendLine();

        sb.AppendLine("        protected internal override global::Jint.Native.JsValue Call(global::Jint.Native.JsValue thisObject, global::Jint.Native.JsValue[] arguments)");
        sb.AppendLine("        {");
        sb.AppendLine("            switch (_slot)");
        sb.AppendLine("            {");
        foreach (var fn in obj.Functions)
        {
            sb.Append("                case Slot.").Append(fn.ClrName).Append(": return ");
            EmitInvocation(sb, obj, fn);
            sb.AppendLine(";");
        }
        sb.AppendLine("                default: throw UnknownSlot(_slot);");
        sb.AppendLine("            }");
        sb.AppendLine("        }");
        sb.AppendLine();

        sb.AppendLine("        private static global::Jint.Native.JsString GetName(Slot slot)");
        sb.AppendLine("        {");
        sb.AppendLine("            switch (slot)");
        sb.AppendLine("            {");
        foreach (var fn in obj.Functions)
        {
            sb.Append("                case Slot.").Append(fn.ClrName).Append(": return global::Jint.Native.JsString.CachedCreate(\"").Append(EscapeStringLit(fn.JsName)).AppendLine("\");");
        }
        sb.AppendLine("                default: throw UnknownSlot(slot);");
        sb.AppendLine("            }");
        sb.AppendLine("        }");
        sb.AppendLine();

        sb.AppendLine("        private static int GetLength(Slot slot)");
        sb.AppendLine("        {");
        sb.AppendLine("            switch (slot)");
        sb.AppendLine("            {");
        foreach (var fn in obj.Functions)
        {
            sb.Append("                case Slot.").Append(fn.ClrName).Append(": return ").Append(fn.Length).AppendLine(";");
        }
        sb.AppendLine("                default: throw UnknownSlot(slot);");
        sb.AppendLine("            }");
        sb.AppendLine("        }");
        sb.AppendLine();

        sb.AppendLine("        private static global::System.InvalidOperationException UnknownSlot(Slot slot)");
        sb.AppendLine("            => new global::System.InvalidOperationException(\"Unknown slot \" + slot + \" — generator/runtime mismatch.\");");

        sb.AppendLine("    }");
    }

    private static void EmitInvocation(StringBuilder sb, ObjectDefinition obj, FunctionDefinition fn)
    {
        if (fn.IsStatic) sb.Append(obj.Name).Append('.');
        else sb.Append("_host.");
        sb.Append(fn.ClrName).Append('(');

        var first = true;
        foreach (var p in fn.Parameters)
        {
            if (!first) sb.Append(", ");
            first = false;
            switch (p.Kind)
            {
                case ParameterKind.ThisObject:
                    sb.Append("thisObject");
                    break;
                case ParameterKind.ValueAt:
                    sb.Append("global::Jint.Runtime.Arguments.At(arguments, ").Append(p.Position).Append(')');
                    break;
                case ParameterKind.Rest:
                    // Slice past the fixed positional value parameters into a ReadOnlySpan over the array tail; no allocation.
                    if (p.Position == 0)
                    {
                        sb.Append("new global::System.ReadOnlySpan<global::Jint.Native.JsValue>(arguments, 0, arguments.Length)");
                    }
                    else
                    {
                        sb.Append("new global::System.ReadOnlySpan<global::Jint.Native.JsValue>(arguments, ");
                        sb.Append("global::System.Math.Min(").Append(p.Position).Append(", arguments.Length), ");
                        sb.Append("global::System.Math.Max(0, arguments.Length - ").Append(p.Position).Append("))");
                    }
                    break;
                case ParameterKind.AllArguments:
                    sb.Append("arguments");
                    break;
            }
        }

        sb.Append(')');
    }

    private static void EmitSymbolInitialize(StringBuilder sb, ObjectDefinition obj)
    {
        sb.AppendLine("    /// <summary>Generated symbol-keyed registration. Call from <c>Initialize()</c>.</summary>");
        sb.AppendLine("    private void CreateSymbols_Generated()");
        sb.AppendLine("    {");
        sb.Append("        var symbols = new global::Jint.Collections.DictionarySlim<global::Jint.Native.JsSymbol, global::Jint.Runtime.Descriptors.PropertyDescriptor>(")
          .Append(obj.Symbols.Count)
          .AppendLine(");");

        foreach (var sym in obj.Symbols)
        {
            sb.Append("        symbols[global::Jint.Native.Symbol.GlobalSymbolRegistry.").Append(sym.SymbolName).Append("] = new global::Jint.Runtime.Descriptors.PropertyDescriptor(");
            if (sym.IsStatic) sb.Append(obj.Name).Append('.');
            sb.Append(sym.ClrName).Append(", ");
            sb.Append(sym.FlagsExpression);
            sb.AppendLine(");");
        }

        sb.AppendLine("        SetSymbols(symbols);");
        sb.AppendLine("    }");
    }

    private static string EscapeStringLit(string s)
        => s.Replace("\\", "\\\\").Replace("\"", "\\\"");
}
