using System.Text;

namespace Jint.SourceGenerators;

internal static class Emitter
{
    public static string Emit(ObjectDefinition obj)
    {
        var sb = new StringBuilder(4096);

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();

        var hasNs = !string.IsNullOrEmpty(obj.Namespace);
        if (hasNs)
        {
            sb.Append("namespace ").Append(obj.Namespace).AppendLine(";");
            sb.AppendLine();
        }

        sb.Append(obj.Accessibility).Append(" ");
        if (obj.IsSealed) sb.Append("sealed ");
        sb.Append("partial class ").AppendLine(obj.Name);
        sb.AppendLine("{");

        EmitStaticPropertyDescriptors(sb, obj);
        EmitInitialize(sb, obj);

        var hasSymbolMembers = false;
        foreach (var fn in obj.Functions)
        {
            if (fn.Registration == RegistrationKind.SymbolFunction
                || fn.Registration == RegistrationKind.SymbolAccessorGet
                || fn.Registration == RegistrationKind.SymbolAccessorSet)
            {
                hasSymbolMembers = true;
                break;
            }
        }

        if (obj.Symbols.Count > 0 || hasSymbolMembers)
        {
            sb.AppendLine();
            EmitSymbolInitialize(sb, obj);
        }

        if (obj.Functions.Count > 0)
        {
            sb.AppendLine();
            EmitDispatcher(sb, obj);
        }

        sb.AppendLine("}");
        return sb.ToString();
    }

    /// <summary>
    /// Emits one <c>private static readonly PropertyDescriptor</c> field per
    /// <em>spec-immutable</em> static <c>[JsProperty]</c> entry — i.e. <c>IsStatic &amp;&amp; IsImmutable</c>
    /// (default flags = <c>PropertyFlag.AllForbidden</c> — Configurable=Writable=Enumerable=false,
    /// all explicitly set). JS code can't mutate such a descriptor: <c>writable=false</c> blocks
    /// value writes, <c>configurable=false</c> blocks <c>defineProperty</c> redefinition and
    /// <c>delete</c>. So sharing across Engines is safe by construction — same pattern as
    /// <c>PropertyDescriptor.AllForbiddenDescriptor</c> already in the runtime.
    /// <para>
    /// Mutable static <c>[JsProperty]</c> entries (e.g. <c>Error.prototype.message</c> with
    /// <c>NonEnumerable</c> flags — configurable=writable=true) are deliberately NOT cached here:
    /// test262's <c>verifyProperty</c> mutates property attributes, so a static descriptor's
    /// <c>_flags</c> would leak across parallel Engines, manifesting as flaky
    /// <c>NativeErrors/*/prototype/message.js</c> failures. Per-Engine descriptors keep mutations
    /// scoped to the Engine that performed them.
    /// </para>
    /// Instance <c>[JsProperty]</c> entries are also skipped here — the value depends on the host
    /// instance, so the descriptor must be per-instance regardless of immutability.
    /// </summary>
    private static void EmitStaticPropertyDescriptors(StringBuilder sb, ObjectDefinition obj)
    {
        var emitted = false;
        foreach (var prop in obj.Properties)
        {
            if (!prop.IsStatic || !prop.IsImmutable) continue;
            sb.Append("    private static readonly global::Jint.Runtime.Descriptors.PropertyDescriptor __")
              .Append(obj.Name).Append("_Property_").Append(prop.ClrName)
              .Append(" = new(").Append(obj.Name).Append('.').Append(prop.ClrName).Append(", ")
              .Append(prop.FlagsExpression).AppendLine(");");
            emitted = true;
        }
        if (emitted) sb.AppendLine();
    }

    /// <summary>
    /// Emits one <c>private static readonly Key __Key_&lt;name&gt;</c> field per unique JsName used
    /// in <c>CreateProperties_Generated</c>. Without this, every <c>properties.AddDangerous("name",...)</c>
    /// call triggers <c>string→Key</c> implicit conversion which recomputes the FNV hash on every
    /// Engine init. Caching the Key once per process saves ~10-20ns per entry × N entries — for
    /// GlobalObject (71 entries) that's ~700-1400ns of Engine startup.
    /// </summary>
    private static void EmitStaticKeyCache(StringBuilder sb, ObjectDefinition obj, IReadOnlyList<FunctionDefinition> dataProperties, IReadOnlyDictionary<string, (FunctionDefinition? Get, FunctionDefinition? Set, string Flags)> accessorsByName)
    {
        var seen = new HashSet<string>(StringComparer.Ordinal);
        var emitted = false;
        foreach (var name in EnumerateAllJsNames(obj, dataProperties, accessorsByName))
        {
            if (!seen.Add(name)) continue;
            sb.Append("    private static readonly global::Jint.Key __Key_")
              .Append(SanitizeIdentifier(name))
              .Append(" = \"").Append(EscapeStringLit(name)).AppendLine("\";");
            emitted = true;
        }
        if (emitted) sb.AppendLine();
    }

    private static IEnumerable<string> EnumerateAllJsNames(ObjectDefinition obj, IReadOnlyList<FunctionDefinition> dataProperties, IReadOnlyDictionary<string, (FunctionDefinition? Get, FunctionDefinition? Set, string Flags)> accessorsByName)
    {
        foreach (var prop in obj.Properties) yield return prop.JsName;
        foreach (var fn in dataProperties) yield return fn.JsName;
        foreach (var ir in obj.IntrinsicReferences) yield return ir.JsName;
        foreach (var name in accessorsByName.Keys) yield return name;
        foreach (var thr in obj.ThrowerAccessors) yield return thr.JsName;
    }

    /// <summary>
    /// Maps a JsName to a valid C# identifier suffix for the cached Key field. Mostly identity since
    /// every property/function name in the migrated surface is already a valid identifier; the
    /// fallback handles any future edge cases (digits, dollar signs, symbols).
    /// </summary>
    private static string SanitizeIdentifier(string name)
    {
        var sb = new StringBuilder(name.Length);
        for (var i = 0; i < name.Length; i++)
        {
            var c = name[i];
            if (i == 0 && char.IsDigit(c)) sb.Append('_');
            sb.Append(char.IsLetterOrDigit(c) || c == '_' ? c : '_');
        }
        return sb.ToString();
    }

    private static void EmitInitialize(StringBuilder sb, ObjectDefinition obj)
    {
        // Group function registrations by JsName for accessor pairing.
        var dataProperties = new List<FunctionDefinition>();
        var accessorsByName = new Dictionary<string, (FunctionDefinition? Get, FunctionDefinition? Set, string Flags)>(StringComparer.Ordinal);
        foreach (var fn in obj.Functions)
        {
            switch (fn.Registration)
            {
                case RegistrationKind.DataProperty:
                    dataProperties.Add(fn);
                    break;
                case RegistrationKind.AccessorGet:
                    accessorsByName.TryGetValue(fn.JsName, out var slotG);
                    accessorsByName[fn.JsName] = (fn, slotG.Set, slotG.Get is null && slotG.Set is null ? fn.FlagsExpression : slotG.Flags);
                    break;
                case RegistrationKind.AccessorSet:
                    accessorsByName.TryGetValue(fn.JsName, out var slotS);
                    accessorsByName[fn.JsName] = (slotS.Get, fn, slotS.Get is null && slotS.Set is null ? fn.FlagsExpression : slotS.Flags);
                    break;
                case RegistrationKind.SymbolFunction:
                case RegistrationKind.SymbolAccessorGet:
                case RegistrationKind.SymbolAccessorSet:
                    // Handled in EmitSymbolInitialize.
                    break;
            }
        }

        var totalEntries = dataProperties.Count + obj.Properties.Count + accessorsByName.Count + obj.ThrowerAccessors.Count + obj.IntrinsicReferences.Count;

        if (totalEntries > 0) EmitStaticKeyCache(sb, obj, dataProperties, accessorsByName);

        sb.AppendLine("    /// <summary>Generated property registration. Call from <c>Initialize()</c>.</summary>");
        sb.AppendLine("    private void CreateProperties_Generated()");
        sb.AppendLine("    {");

        if (totalEntries == 0 && obj.ExtraCapacity == 0)
        {
            sb.AppendLine("        // no [JsFunction] / [JsProperty] / [JsAccessor] / [JsThrowerAccessor] / [JsIntrinsicReference] members");
            sb.AppendLine("    }");
            return;
        }

        // [JsObject(ExtraCapacity=N)] presizes the dictionary for post-CreateProperties_Generated
        // SetProperty calls (e.g. cross-realm constructor refs in IntlInstance/TemporalInstance) so
        // the dictionary doesn't grow + transition list→hash during init.
        // Emit StringDictionarySlim directly instead of HybridDictionary — SetProperties has an
        // overload that wraps the slim dict at the end (one allocation), so we skip the wrapper
        // overhead during the bulk insert (no null-check delegation per AddDangerous call) and
        // save the HybridDictionary instance (~32 bytes per Engine init).
        sb.Append("        var properties = new global::Jint.Collections.StringDictionarySlim<global::Jint.Runtime.Descriptors.PropertyDescriptor>(")
          .Append(totalEntries + obj.ExtraCapacity)
          .AppendLine(");");

        // AddDangerous skips the duplicate-key lookup and writes directly to the backing array.
        // Safe here because every key emitted below is unique by construction (JINT012 forbids
        // overload-style duplicates).
        //
        // Static + spec-immutable [JsProperty] (IsStatic && IsImmutable, i.e. AllForbidden flags):
        // share a single PropertyDescriptor across Engines via the field emitted in
        // EmitStaticPropertyDescriptors. JS can't mutate the descriptor (writable=false,
        // configurable=false), so the cache is safe.
        //
        // Static + mutable [JsProperty] (e.g. NonEnumerable on Error.prototype.message): allocate
        // per Engine. test262's verifyProperty mutates attributes, so a shared descriptor would
        // leak across parallel Engines.
        //
        // Instance [JsProperty]: always per-Engine (value depends on the host instance).
        foreach (var prop in obj.Properties)
        {
            if (prop.IsStatic && prop.IsImmutable)
            {
                sb.Append("        properties.AddDangerous(__Key_").Append(SanitizeIdentifier(prop.JsName)).Append(", __").Append(obj.Name).Append("_Property_").Append(prop.ClrName).AppendLine(");");
            }
            else
            {
                sb.Append("        properties.AddDangerous(__Key_").Append(SanitizeIdentifier(prop.JsName)).Append(", new global::Jint.Runtime.Descriptors.PropertyDescriptor(");
                if (prop.IsStatic) sb.Append(obj.Name).Append('.');
                sb.Append(prop.ClrName).Append(", ");
                sb.Append(prop.FlagsExpression);
                sb.AppendLine("));");
            }
        }

        // Slot elimination (Phase 2d): single-slot hosts get a constructor that takes no slot arg.
        var singleSlot = obj.Functions.Count == 1;
        foreach (var fn in dataProperties)
        {
            sb.Append("        properties.AddDangerous(__Key_").Append(SanitizeIdentifier(fn.JsName)).Append(", new global::Jint.Runtime.Descriptors.Specialized.LazyPropertyDescriptor<")
              .Append(obj.Name).Append(">(this, static host => new __").Append(obj.Name);
            if (singleSlot)
            {
                sb.Append("Function(host)");
            }
            else
            {
                sb.Append("Function(host, __").Append(obj.Name).Append("Function.Slot.").Append(fn.ClrName).Append(")");
            }
            sb.Append(", ").Append(fn.FlagsExpression).AppendLine("));");
        }

        // [JsIntrinsicReference]: LazyPropertyDescriptor whose factory hands back a realm intrinsic
        // (e.g. host._realm.Intrinsics.Array). Same lazy shape as [JsFunction] but the value source is
        // an intrinsic constructor object, not a generated dispatcher Function. Used by GlobalObject
        // for the constructor properties on globalThis.
        foreach (var ir in obj.IntrinsicReferences)
        {
            sb.Append("        properties.AddDangerous(__Key_").Append(SanitizeIdentifier(ir.JsName)).Append(", new global::Jint.Runtime.Descriptors.Specialized.LazyPropertyDescriptor<")
              .Append(obj.Name).Append(">(this, static host => host._realm.Intrinsics.")
              .Append(ir.IntrinsicMember).Append(", ").Append(ir.FlagsExpression).AppendLine("));");
        }

        // Accessors: LazyGetSetPropertyDescriptor — dispatcher Functions allocate on first read,
        // so prototypes with many never-read accessors (Temporal date/time has 10-20 each) skip the
        // up-front allocations. The shape mirrors the data-property [JsFunction] emission above.
        var accessorNames = new List<string>(accessorsByName.Keys);
        accessorNames.Sort(StringComparer.Ordinal);
        foreach (var name in accessorNames)
        {
            var (getFn, setFn, flagsExpr) = accessorsByName[name];
            sb.Append("        properties.AddDangerous(__Key_").Append(SanitizeIdentifier(name)).Append(", new global::Jint.Runtime.Descriptors.Specialized.LazyGetSetPropertyDescriptor<")
              .Append(obj.Name).Append(">(this, ");
            if (getFn is not null)
            {
                sb.Append("static host => new __").Append(obj.Name);
                if (singleSlot) sb.Append("Function(host)");
                else            sb.Append("Function(host, __").Append(obj.Name).Append("Function.Slot.").Append(getFn.ClrName).Append(')');
            }
            else
            {
                sb.Append("null");
            }
            sb.Append(", ");
            if (setFn is not null)
            {
                sb.Append("static host => new __").Append(obj.Name);
                if (singleSlot) sb.Append("Function(host)");
                else            sb.Append("Function(host, __").Append(obj.Name).Append("Function.Slot.").Append(setFn.ClrName).Append(')');
            }
            else
            {
                sb.Append("null");
            }
            sb.Append(", ").Append(flagsExpr).AppendLine("));");
        }

        // Thrower accessors: a single shared instance per host, assigned to each name.
        if (obj.ThrowerAccessors.Count > 0)
        {
            // Reuse the same descriptor instance — the runtime allows this; it has no per-property state.
            sb.Append("        var __thrower = new global::Jint.Runtime.Descriptors.GetSetPropertyDescriptor.ThrowerPropertyDescriptor(_engine, ").Append(obj.ThrowerAccessors[0].FlagsExpression).AppendLine(");");
            foreach (var thr in obj.ThrowerAccessors)
            {
                sb.Append("        properties.AddDangerous(__Key_").Append(SanitizeIdentifier(thr.JsName)).AppendLine(", __thrower);");
            }
        }

        sb.AppendLine("        SetProperties(properties);");
        sb.AppendLine("    }");
    }

    private static void EmitDispatcher(StringBuilder sb, ObjectDefinition obj)
    {
        var typeName = "__" + obj.Name + "Function";
        // Slot elimination: hosts with exactly one [JsFunction]/[JsAccessor]/[JsSymbol*] entry get
        // a simplified dispatcher — no Slot enum, no `_slot` field, no switch in Call/GetName/
        // GetLength. The dispatcher constructor stops taking the slot parameter, so the lambda
        // factory in CreateProperties_Generated drops the second arg too. Saves 1 ushort field +
        // the enum metadata; small but real for the ~10 single-function hosts (e.g. ArrayBuffer.
        // isView, Error.toString, Atomics ops live alongside others so they don't qualify, but
        // hosts like ArrayBufferConstructor / ArrayIteratorPrototype do).
        var singleSlot = obj.Functions.Count == 1;

        sb.Append("    private sealed class ").Append(typeName).AppendLine(" : global::Jint.Native.Function.Function");
        sb.AppendLine("    {");
        if (!singleSlot)
        {
            sb.AppendLine("        internal enum Slot : ushort");
            sb.AppendLine("        {");
            foreach (var fn in obj.Functions)
            {
                sb.Append("            ").Append(fn.ClrName).AppendLine(",");
            }
            sb.AppendLine("        }");
        }
        sb.AppendLine();

        sb.Append("        private readonly ").Append(obj.Name).AppendLine(" _host;");
        if (!singleSlot)
        {
            sb.AppendLine("        private readonly Slot _slot;");
        }
        sb.AppendLine();

        // Use host._realm — the realm captured at host construction time (= host's home realm) — not
        // host.Engine.Realm, which is the *currently active* realm. Lazy descriptors materialize on
        // first read; if first access is cross-realm (e.g. via ShadowRealm), Engine.Realm would be the
        // wrong realm and the dispatcher Function would carry the wrong [[Realm]] internal slot.
        if (singleSlot)
        {
            // No slot parameter — only one entry, name/length are constants captured directly below.
            var only = obj.Functions[0];
            sb.Append("        internal ").Append(typeName).Append("(").Append(obj.Name).AppendLine(" host)");
            sb.Append("            : base(host.Engine, host._realm, global::Jint.Native.JsString.CachedCreate(\"").Append(EscapeStringLit(only.FunctionName)).AppendLine("\"))");
            sb.AppendLine("        {");
            sb.AppendLine("            _host = host;");
            sb.AppendLine("            _prototype = host._realm.Intrinsics.Function.PrototypeObject;");
            sb.Append("            _length = new global::Jint.Runtime.Descriptors.PropertyDescriptor(global::Jint.Native.JsNumber.Create(").Append(only.Length).AppendLine("), global::Jint.Runtime.Descriptors.PropertyFlag.Configurable);");
            sb.AppendLine("        }");
        }
        else
        {
            sb.Append("        internal ").Append(typeName).Append("(").Append(obj.Name).AppendLine(" host, Slot slot)");
            sb.AppendLine("            : base(host.Engine, host._realm, GetName(slot))");
            sb.AppendLine("        {");
            sb.AppendLine("            _host = host;");
            sb.AppendLine("            _slot = slot;");
            sb.AppendLine("            _prototype = host._realm.Intrinsics.Function.PrototypeObject;");
            sb.AppendLine("            _length = new global::Jint.Runtime.Descriptors.PropertyDescriptor(global::Jint.Native.JsNumber.Create(GetLength(slot)), global::Jint.Runtime.Descriptors.PropertyFlag.Configurable);");
            sb.AppendLine("        }");
        }
        sb.AppendLine();

        sb.AppendLine("        protected internal override global::Jint.Native.JsValue Call(global::Jint.Native.JsValue thisObject, global::Jint.Native.JsValue[] arguments)");
        sb.AppendLine("        {");
        if (!singleSlot)
        {
            sb.AppendLine("            switch (_slot)");
            sb.AppendLine("            {");
        }
        foreach (var fn in obj.Functions)
        {
            // If thisObject is typed as a JsValue subtype or ICallable, emit a cast + TypeError precondition.
            string? castType = null;
            foreach (var p in fn.Parameters)
            {
                if (p.Kind == ParameterKind.ThisObject && p.CastTargetType is not null)
                {
                    castType = p.CastTargetType;
                    break;
                }
            }

            // Coerced [Rest]: param is `[Rest, ToX] ReadOnlySpan<T>`. Generator emits a Span<T>
            // local with stackalloc for ≤16 elements and a heap array for larger sizes, then
            // populates it via TypeConverter.ToX in a separate pass *before* calling the host
            // method (the spec requires every element's coercion to run before any scanning logic
            // — observable via valueOf side effects).
            ParameterDefinition? coercedRest = null;
            foreach (var p in fn.Parameters)
            {
                if (p.Kind == ParameterKind.Rest && p.CoercionKind is not null)
                {
                    coercedRest = p;
                    break;
                }
            }

            // Indent: "                " (16 sp) for switch-case body, "            " (12 sp) for flat single-slot body.
            var bodyIndent = singleSlot ? "            " : "                ";

            if (castType is not null || fn.RequireObjectCoercible || coercedRest is not null)
            {
                if (!singleSlot)
                {
                    sb.Append("                case Slot.").Append(fn.ClrName).AppendLine(":");
                    sb.AppendLine("                {");
                }
                if (fn.RequireObjectCoercible)
                {
                    sb.Append(bodyIndent).Append("    ").AppendLine("global::Jint.Runtime.TypeConverter.RequireObjectCoercible(_host._engine, thisObject);");
                }
                if (castType is not null)
                {
                    sb.Append(bodyIndent).Append("    ").Append("var __cast = thisObject as global::").Append(castType).AppendLine(";");
                    // Use the host's _realm (which carries the realm where the host was constructed) — not the
                    // dispatcher's own _realm, which only reflects the engine's active realm at first access of
                    // the lazy descriptor. Cross-realm tests like apply/this-not-callable-realm depend on this.
                    sb.Append(bodyIndent).Append("    ").Append("if (__cast is null) global::Jint.Runtime.Throw.TypeError(_host._realm, \"")
                      .Append(EscapeStringLit(fn.FunctionName))
                      .Append(" requires 'this' to be of type ")
                      .Append(EscapeStringLit(castType.Substring(castType.LastIndexOf('.') + 1)))
                      .AppendLine("\");");
                }
                if (coercedRest is { } cr)
                {
                    EmitCoercedRestPreamble(sb, cr, singleSlot);
                }
                sb.Append(bodyIndent).Append("    ").Append("return ");
                EmitInvocation(sb, obj, fn);
                sb.AppendLine(";");
                if (!singleSlot)
                {
                    sb.AppendLine("                }");
                }
            }
            else
            {
                if (singleSlot)
                {
                    sb.Append("            return ");
                }
                else
                {
                    sb.Append("                case Slot.").Append(fn.ClrName).Append(": return ");
                }
                EmitInvocation(sb, obj, fn);
                sb.AppendLine(";");
            }
        }
        if (!singleSlot)
        {
            sb.AppendLine("                default: throw UnknownSlot(_slot);");
            sb.AppendLine("            }");
        }
        sb.AppendLine("        }");

        if (!singleSlot)
        {
            sb.AppendLine();
            sb.AppendLine("        private static global::Jint.Native.JsString GetName(Slot slot)");
            sb.AppendLine("        {");
            sb.AppendLine("            switch (slot)");
            sb.AppendLine("            {");
            foreach (var fn in obj.Functions)
            {
                sb.Append("                case Slot.").Append(fn.ClrName).Append(": return global::Jint.Native.JsString.CachedCreate(\"").Append(EscapeStringLit(fn.FunctionName)).AppendLine("\");");
            }
            sb.AppendLine("                default: throw UnknownSlot(slot);");
            sb.AppendLine("            }");
            sb.AppendLine("        }");
            sb.AppendLine();

            sb.AppendLine("        private static int GetLength(Slot slot)");
            sb.AppendLine("        {");
            sb.AppendLine("            switch (slot)");
            sb.AppendLine("            {");
            foreach (var fn in obj.Functions)
            {
                sb.Append("                case Slot.").Append(fn.ClrName).Append(": return ").Append(fn.Length).AppendLine(";");
            }
            sb.AppendLine("                default: throw UnknownSlot(slot);");
            sb.AppendLine("            }");
            sb.AppendLine("        }");
            sb.AppendLine();

            sb.AppendLine("        private static global::System.InvalidOperationException UnknownSlot(Slot slot)");
            sb.AppendLine("            => new global::System.InvalidOperationException(\"Unknown slot \" + slot + \" — generator/runtime mismatch.\");");
        }

        sb.AppendLine("    }");
    }

    /// <summary>
    /// Emits the stackalloc-or-heap span + coerce-loop preamble for a coerced <c>[Rest]</c>
    /// parameter (e.g. <c>[Rest, ToNumber] ReadOnlySpan&lt;double&gt;</c>). Written into local
    /// <c>__coerced</c> which <see cref="EmitInvocation"/> then references. Stackalloc threshold
    /// is 16 elements — the same convention <c>MathInstance.Max/Min/Hypot</c> used pre-migration.
    /// </summary>
    private static void EmitCoercedRestPreamble(StringBuilder sb, ParameterDefinition p, bool singleSlot)
    {
        var (csharpType, _) = ConversionTargetTypeNames(p.CoercionKind!.Value);
        var converter = ConversionConverterCall(p.CoercionKind!.Value);
        var startExpr = p.Position == 0 ? "0" : "global::System.Math.Min(" + p.Position + ", arguments.Length)";
        var lenExpr   = p.Position == 0 ? "arguments.Length" : "global::System.Math.Max(0, arguments.Length - " + p.Position + ")";
        // Switch-case body lives at 16 sp; flat single-slot Call body at 12 sp. Inner indent +4.
        var i = singleSlot ? "            " : "                    ";

        sb.Append(i).Append("var __values = new global::System.ReadOnlySpan<global::Jint.Native.JsValue>(arguments, ").Append(startExpr).Append(", ").Append(lenExpr).AppendLine(");");
        sb.Append(i).Append("global::System.Span<").Append(csharpType).AppendLine("> __coerced = __values.Length <= 16");
        sb.Append(i).Append("    ? stackalloc ").Append(csharpType).AppendLine("[__values.Length]");
        sb.Append(i).Append("    : new ").Append(csharpType).AppendLine("[__values.Length];");
        sb.Append(i).AppendLine("for (var __i = 0; __i < __values.Length; __i++)");
        sb.Append(i).AppendLine("{");
        sb.Append(i).Append("    __coerced[__i] = ").Append(converter).AppendLine("(__values[__i]);");
        sb.Append(i).AppendLine("}");
    }

    private static (string csharpType, string attrName) ConversionTargetTypeNames(ParameterKind kind) => kind switch
    {
        ParameterKind.ToNumber  => ("double", "ToNumber"),
        ParameterKind.ToInt32   => ("int", "ToInt32"),
        ParameterKind.ToUint32  => ("uint", "ToUint32"),
        ParameterKind.ToInteger => ("double", "ToInteger"),
        ParameterKind.ToLength  => ("ulong", "ToLength"),
        ParameterKind.ToString  => ("string", "ToString"),
        ParameterKind.ToJsString => ("global::Jint.Native.JsString", "ToJsString"),
        ParameterKind.ToObject  => ("global::Jint.Native.Object.ObjectInstance", "ToObject"),
        _ => throw new System.InvalidOperationException($"ConversionTargetTypeNames called with non-coercion kind {kind}"),
    };

    private static string ConversionConverterCall(ParameterKind kind) => kind switch
    {
        ParameterKind.ToNumber   => "global::Jint.Runtime.TypeConverter.ToNumber",
        ParameterKind.ToInt32    => "global::Jint.Runtime.TypeConverter.ToInt32",
        ParameterKind.ToUint32   => "global::Jint.Runtime.TypeConverter.ToUint32",
        ParameterKind.ToInteger  => "global::Jint.Runtime.TypeConverter.ToInteger",
        ParameterKind.ToLength   => "global::Jint.Runtime.TypeConverter.ToLength",
        ParameterKind.ToString   => "global::Jint.Runtime.TypeConverter.ToString",
        ParameterKind.ToJsString => "global::Jint.Runtime.TypeConverter.ToJsString",
        // [ToObject] needs the realm — for a coerced rest this would have to capture _realm; not
        // useful in practice (no built-in variadic takes ObjectInstance[]) so we throw.
        _ => throw new System.InvalidOperationException($"Coerced [Rest] does not support {kind}"),
    };

    private static void EmitInvocation(StringBuilder sb, ObjectDefinition obj, FunctionDefinition fn)
    {
        if (fn.IsStatic) sb.Append(obj.Name).Append('.');
        else sb.Append("_host.");
        sb.Append(fn.ClrName).Append('(');

        var first = true;
        foreach (var p in fn.Parameters)
        {
            if (!first) sb.Append(", ");
            first = false;
            switch (p.Kind)
            {
                case ParameterKind.ThisObject:
                    sb.Append(p.CastTargetType is null ? "thisObject" : "__cast");
                    break;
                case ParameterKind.ValueAt:
                    sb.Append("global::Jint.Runtime.Arguments.At(arguments, ").Append(p.Position).Append(')');
                    break;
                case ParameterKind.ToNumber:
                    sb.Append("global::Jint.Runtime.TypeConverter.ToNumber(global::Jint.Runtime.Arguments.At(arguments, ").Append(p.Position).Append("))");
                    break;
                case ParameterKind.ToInt32:
                    sb.Append("global::Jint.Runtime.TypeConverter.ToInt32(global::Jint.Runtime.Arguments.At(arguments, ").Append(p.Position).Append("))");
                    break;
                case ParameterKind.ToUint32:
                    sb.Append("global::Jint.Runtime.TypeConverter.ToUint32(global::Jint.Runtime.Arguments.At(arguments, ").Append(p.Position).Append("))");
                    break;
                case ParameterKind.ToInteger:
                    sb.Append("global::Jint.Runtime.TypeConverter.ToInteger(global::Jint.Runtime.Arguments.At(arguments, ").Append(p.Position).Append("))");
                    break;
                case ParameterKind.ToLength:
                    sb.Append("global::Jint.Runtime.TypeConverter.ToLength(global::Jint.Runtime.Arguments.At(arguments, ").Append(p.Position).Append("))");
                    break;
                case ParameterKind.ToString:
                    sb.Append("global::Jint.Runtime.TypeConverter.ToString(global::Jint.Runtime.Arguments.At(arguments, ").Append(p.Position).Append("))");
                    break;
                case ParameterKind.ToJsString:
                    sb.Append("global::Jint.Runtime.TypeConverter.ToJsString(global::Jint.Runtime.Arguments.At(arguments, ").Append(p.Position).Append("))");
                    break;
                case ParameterKind.ToObject:
                    sb.Append("global::Jint.Runtime.TypeConverter.ToObject(_realm, global::Jint.Runtime.Arguments.At(arguments, ").Append(p.Position).Append("))");
                    break;
                case ParameterKind.Rest:
                    if (p.CoercionKind is not null)
                    {
                        // Coerced [Rest]: the dispatcher's preamble (EmitCoercedRestPreamble) has
                        // already populated `__coerced`; just pass it through.
                        sb.Append("__coerced");
                    }
                    else if (p.Position == 0)
                    {
                        // Slice past the fixed positional value parameters into a ReadOnlySpan over the array tail; no allocation.
                        sb.Append("new global::System.ReadOnlySpan<global::Jint.Native.JsValue>(arguments, 0, arguments.Length)");
                    }
                    else
                    {
                        sb.Append("new global::System.ReadOnlySpan<global::Jint.Native.JsValue>(arguments, ");
                        sb.Append("global::System.Math.Min(").Append(p.Position).Append(", arguments.Length), ");
                        sb.Append("global::System.Math.Max(0, arguments.Length - ").Append(p.Position).Append("))");
                    }
                    break;
                case ParameterKind.AllArguments:
                    sb.Append("arguments");
                    break;
            }
        }

        sb.Append(')');
    }

    private static void EmitSymbolInitialize(StringBuilder sb, ObjectDefinition obj)
    {
        var symbolFunctions = new List<FunctionDefinition>();
        var symbolAccessorsByName = new Dictionary<string, (FunctionDefinition? Get, FunctionDefinition? Set, string Flags)>(StringComparer.Ordinal);
        foreach (var fn in obj.Functions)
        {
            switch (fn.Registration)
            {
                case RegistrationKind.SymbolFunction:
                    symbolFunctions.Add(fn);
                    break;
                case RegistrationKind.SymbolAccessorGet:
                    symbolAccessorsByName.TryGetValue(fn.JsName, out var slotG);
                    symbolAccessorsByName[fn.JsName] = (fn, slotG.Set, slotG.Get is null && slotG.Set is null ? fn.FlagsExpression : slotG.Flags);
                    break;
                case RegistrationKind.SymbolAccessorSet:
                    symbolAccessorsByName.TryGetValue(fn.JsName, out var slotS);
                    symbolAccessorsByName[fn.JsName] = (slotS.Get, fn, slotS.Get is null && slotS.Set is null ? fn.FlagsExpression : slotS.Flags);
                    break;
            }
        }

        var totalEntries = obj.Symbols.Count + symbolFunctions.Count + symbolAccessorsByName.Count;

        sb.AppendLine("    /// <summary>Generated symbol-keyed registration. Call from <c>Initialize()</c>.</summary>");
        sb.AppendLine("    private void CreateSymbols_Generated()");
        sb.AppendLine("    {");
        sb.Append("        var symbols = new global::Jint.Collections.DictionarySlim<global::Jint.Native.JsSymbol, global::Jint.Runtime.Descriptors.PropertyDescriptor>(")
          .Append(totalEntries)
          .AppendLine(");");

        foreach (var sym in obj.Symbols)
        {
            sb.Append("        symbols[global::Jint.Native.Symbol.GlobalSymbolRegistry.").Append(sym.SymbolName).Append("] = new global::Jint.Runtime.Descriptors.PropertyDescriptor(");
            if (sym.IsStatic) sb.Append(obj.Name).Append('.');
            sb.Append(sym.ClrName).Append(", ");
            sb.Append(sym.FlagsExpression);
            sb.AppendLine(");");
        }

        var singleSlot = obj.Functions.Count == 1;
        foreach (var fn in symbolFunctions)
        {
            sb.Append("        symbols[global::Jint.Native.Symbol.GlobalSymbolRegistry.").Append(fn.JsName).Append("] = new global::Jint.Runtime.Descriptors.Specialized.LazyPropertyDescriptor<")
              .Append(obj.Name).Append(">(this, static host => new __").Append(obj.Name);
            if (singleSlot) sb.Append("Function(host)");
            else            sb.Append("Function(host, __").Append(obj.Name).Append("Function.Slot.").Append(fn.ClrName).Append(")");
            sb.Append(", ").Append(fn.FlagsExpression).AppendLine(");");
        }

        // Symbol-keyed accessors: LazyGetSetPropertyDescriptor — dispatcher Functions allocate on
        // first read, registered under GlobalSymbolRegistry.<SymbolName>.
        var symbolAccessorNames = new List<string>(symbolAccessorsByName.Keys);
        symbolAccessorNames.Sort(StringComparer.Ordinal);
        foreach (var name in symbolAccessorNames)
        {
            var (getFn, setFn, flagsExpr) = symbolAccessorsByName[name];
            sb.Append("        symbols[global::Jint.Native.Symbol.GlobalSymbolRegistry.").Append(name).Append("] = new global::Jint.Runtime.Descriptors.Specialized.LazyGetSetPropertyDescriptor<")
              .Append(obj.Name).Append(">(this, ");
            if (getFn is not null)
            {
                sb.Append("static host => new __").Append(obj.Name);
                if (singleSlot) sb.Append("Function(host)");
                else            sb.Append("Function(host, __").Append(obj.Name).Append("Function.Slot.").Append(getFn.ClrName).Append(')');
            }
            else
            {
                sb.Append("null");
            }
            sb.Append(", ");
            if (setFn is not null)
            {
                sb.Append("static host => new __").Append(obj.Name);
                if (singleSlot) sb.Append("Function(host)");
                else            sb.Append("Function(host, __").Append(obj.Name).Append("Function.Slot.").Append(setFn.ClrName).Append(')');
            }
            else
            {
                sb.Append("null");
            }
            sb.Append(", ").Append(flagsExpr).AppendLine(");");
        }

        sb.AppendLine("        SetSymbols(symbols);");
        sb.AppendLine("    }");
    }

    private static string EscapeStringLit(string s)
        => s.Replace("\\", "\\\\").Replace("\"", "\\\"");
}
