using System.Text;

namespace Jint.SourceGenerators;

internal static class Emitter
{
    public static string Emit(ObjectDefinition obj)
    {
        var sb = new StringBuilder(4096);

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();

        var hasNs = !string.IsNullOrEmpty(obj.Namespace);
        if (hasNs)
        {
            sb.Append("namespace ").Append(obj.Namespace).AppendLine(";");
            sb.AppendLine();
        }

        sb.Append(obj.Accessibility).Append(" ");
        if (obj.IsSealed) sb.Append("sealed ");
        sb.Append("partial class ").AppendLine(obj.Name);
        sb.AppendLine("{");

        EmitInitialize(sb, obj);

        var hasSymbolMembers = false;
        foreach (var fn in obj.Functions)
        {
            if (fn.Registration == RegistrationKind.SymbolFunction
                || fn.Registration == RegistrationKind.SymbolAccessorGet
                || fn.Registration == RegistrationKind.SymbolAccessorSet)
            {
                hasSymbolMembers = true;
                break;
            }
        }

        if (obj.Symbols.Count > 0 || hasSymbolMembers)
        {
            sb.AppendLine();
            EmitSymbolInitialize(sb, obj);
        }

        if (obj.Functions.Count > 0)
        {
            sb.AppendLine();
            EmitDispatcher(sb, obj);
        }

        sb.AppendLine("}");
        return sb.ToString();
    }

    private static void EmitInitialize(StringBuilder sb, ObjectDefinition obj)
    {
        // Group function registrations by JsName for accessor pairing.
        var dataProperties = new List<FunctionDefinition>();
        var accessorsByName = new Dictionary<string, (FunctionDefinition? Get, FunctionDefinition? Set, string Flags)>(StringComparer.Ordinal);
        foreach (var fn in obj.Functions)
        {
            switch (fn.Registration)
            {
                case RegistrationKind.DataProperty:
                    dataProperties.Add(fn);
                    break;
                case RegistrationKind.AccessorGet:
                    accessorsByName.TryGetValue(fn.JsName, out var slotG);
                    accessorsByName[fn.JsName] = (fn, slotG.Set, slotG.Get is null && slotG.Set is null ? fn.FlagsExpression : slotG.Flags);
                    break;
                case RegistrationKind.AccessorSet:
                    accessorsByName.TryGetValue(fn.JsName, out var slotS);
                    accessorsByName[fn.JsName] = (slotS.Get, fn, slotS.Get is null && slotS.Set is null ? fn.FlagsExpression : slotS.Flags);
                    break;
                case RegistrationKind.SymbolFunction:
                case RegistrationKind.SymbolAccessorGet:
                case RegistrationKind.SymbolAccessorSet:
                    // Handled in EmitSymbolInitialize.
                    break;
            }
        }

        var totalEntries = dataProperties.Count + obj.Properties.Count + accessorsByName.Count + obj.ThrowerAccessors.Count;

        sb.AppendLine("    /// <summary>Generated property registration. Call from <c>Initialize()</c>.</summary>");
        sb.AppendLine("    private void CreateProperties_Generated()");
        sb.AppendLine("    {");

        if (totalEntries == 0)
        {
            sb.AppendLine("        // no [JsFunction] / [JsProperty] / [JsAccessor] / [JsThrowerAccessor] members");
            sb.AppendLine("    }");
            return;
        }

        sb.Append("        var properties = new global::Jint.Collections.HybridDictionary<global::Jint.Runtime.Descriptors.PropertyDescriptor>(")
          .Append(totalEntries)
          .AppendLine(", checkExistingKeys: false);");

        foreach (var prop in obj.Properties)
        {
            sb.Append("        properties[\"").Append(EscapeStringLit(prop.JsName)).Append("\"] = new global::Jint.Runtime.Descriptors.PropertyDescriptor(");
            if (prop.IsStatic) sb.Append(obj.Name).Append('.');
            sb.Append(prop.ClrName).Append(", ");
            sb.Append(prop.FlagsExpression);
            sb.AppendLine(");");
        }

        foreach (var fn in dataProperties)
        {
            sb.Append("        properties[\"").Append(EscapeStringLit(fn.JsName)).Append("\"] = new global::Jint.Runtime.Descriptors.Specialized.LazyPropertyDescriptor<")
              .Append(obj.Name).Append(">(this, static host => new __").Append(obj.Name).Append("Function(host, __")
              .Append(obj.Name).Append("Function.Slot.").Append(fn.ClrName).Append("), ").Append(fn.FlagsExpression).AppendLine(");");
        }

        // Accessors: GetSetPropertyDescriptor wrapping eagerly-allocated dispatcher slots.
        var accessorNames = new List<string>(accessorsByName.Keys);
        accessorNames.Sort(StringComparer.Ordinal);
        foreach (var name in accessorNames)
        {
            var (getFn, setFn, flagsExpr) = accessorsByName[name];
            sb.Append("        properties[\"").Append(EscapeStringLit(name)).Append("\"] = new global::Jint.Runtime.Descriptors.GetSetPropertyDescriptor(");
            if (getFn is not null)
            {
                sb.Append("new __").Append(obj.Name).Append("Function(this, __").Append(obj.Name).Append("Function.Slot.").Append(getFn.ClrName).Append(')');
            }
            else
            {
                sb.Append("null");
            }
            sb.Append(", ");
            if (setFn is not null)
            {
                sb.Append("new __").Append(obj.Name).Append("Function(this, __").Append(obj.Name).Append("Function.Slot.").Append(setFn.ClrName).Append(')');
            }
            else
            {
                sb.Append("null");
            }
            sb.Append(", ").Append(flagsExpr).AppendLine(");");
        }

        // Thrower accessors: a single shared instance per host, assigned to each name.
        if (obj.ThrowerAccessors.Count > 0)
        {
            // Reuse the same descriptor instance — the runtime allows this; it has no per-property state.
            sb.Append("        var __thrower = new global::Jint.Runtime.Descriptors.GetSetPropertyDescriptor.ThrowerPropertyDescriptor(_engine, ").Append(obj.ThrowerAccessors[0].FlagsExpression).AppendLine(");");
            foreach (var thr in obj.ThrowerAccessors)
            {
                sb.Append("        properties[\"").Append(EscapeStringLit(thr.JsName)).AppendLine("\"] = __thrower;");
            }
        }

        sb.AppendLine("        SetProperties(properties);");
        sb.AppendLine("    }");
    }

    private static void EmitDispatcher(StringBuilder sb, ObjectDefinition obj)
    {
        var typeName = "__" + obj.Name + "Function";

        sb.Append("    private sealed class ").Append(typeName).AppendLine(" : global::Jint.Native.Function.Function");
        sb.AppendLine("    {");
        sb.AppendLine("        internal enum Slot : ushort");
        sb.AppendLine("        {");
        foreach (var fn in obj.Functions)
        {
            sb.Append("            ").Append(fn.ClrName).AppendLine(",");
        }
        sb.AppendLine("        }");
        sb.AppendLine();

        sb.Append("        private readonly ").Append(obj.Name).AppendLine(" _host;");
        sb.AppendLine("        private readonly Slot _slot;");
        sb.AppendLine();

        sb.Append("        internal ").Append(typeName).Append("(").Append(obj.Name).AppendLine(" host, Slot slot)");
        sb.AppendLine("            : base(host.Engine, host.Engine.Realm, GetName(slot))");
        sb.AppendLine("        {");
        sb.AppendLine("            _host = host;");
        sb.AppendLine("            _slot = slot;");
        sb.AppendLine("            _prototype = host.Engine.Realm.Intrinsics.Function.PrototypeObject;");
        sb.AppendLine("            _length = new global::Jint.Runtime.Descriptors.PropertyDescriptor(global::Jint.Native.JsNumber.Create(GetLength(slot)), global::Jint.Runtime.Descriptors.PropertyFlag.Configurable);");
        sb.AppendLine("        }");
        sb.AppendLine();

        sb.AppendLine("        protected internal override global::Jint.Native.JsValue Call(global::Jint.Native.JsValue thisObject, global::Jint.Native.JsValue[] arguments)");
        sb.AppendLine("        {");
        sb.AppendLine("            switch (_slot)");
        sb.AppendLine("            {");
        foreach (var fn in obj.Functions)
        {
            // If thisObject is typed as a JsValue subtype or ICallable, emit a cast + TypeError precondition.
            string? castType = null;
            foreach (var p in fn.Parameters)
            {
                if (p.Kind == ParameterKind.ThisObject && p.CastTargetType is not null)
                {
                    castType = p.CastTargetType;
                    break;
                }
            }

            if (castType is not null || fn.RequireObjectCoercible)
            {
                sb.Append("                case Slot.").Append(fn.ClrName).AppendLine(":");
                sb.AppendLine("                {");
                if (fn.RequireObjectCoercible)
                {
                    sb.AppendLine("                    global::Jint.Runtime.TypeConverter.RequireObjectCoercible(_host._engine, thisObject);");
                }
                if (castType is not null)
                {
                    sb.Append("                    var __cast = thisObject as global::").Append(castType).AppendLine(";");
                    // Use the host's _realm (which carries the realm where the host was constructed) — not the
                    // dispatcher's own _realm, which only reflects the engine's active realm at first access of
                    // the lazy descriptor. Cross-realm tests like apply/this-not-callable-realm depend on this.
                    sb.Append("                    if (__cast is null) global::Jint.Runtime.Throw.TypeError(_host._realm, \"")
                      .Append(EscapeStringLit(fn.FunctionName))
                      .Append(" requires 'this' to be of type ")
                      .Append(EscapeStringLit(castType.Substring(castType.LastIndexOf('.') + 1)))
                      .AppendLine("\");");
                }
                sb.Append("                    return ");
                EmitInvocation(sb, obj, fn);
                sb.AppendLine(";");
                sb.AppendLine("                }");
            }
            else
            {
                sb.Append("                case Slot.").Append(fn.ClrName).Append(": return ");
                EmitInvocation(sb, obj, fn);
                sb.AppendLine(";");
            }
        }
        sb.AppendLine("                default: throw UnknownSlot(_slot);");
        sb.AppendLine("            }");
        sb.AppendLine("        }");
        sb.AppendLine();

        sb.AppendLine("        private static global::Jint.Native.JsString GetName(Slot slot)");
        sb.AppendLine("        {");
        sb.AppendLine("            switch (slot)");
        sb.AppendLine("            {");
        foreach (var fn in obj.Functions)
        {
            sb.Append("                case Slot.").Append(fn.ClrName).Append(": return global::Jint.Native.JsString.CachedCreate(\"").Append(EscapeStringLit(fn.FunctionName)).AppendLine("\");");
        }
        sb.AppendLine("                default: throw UnknownSlot(slot);");
        sb.AppendLine("            }");
        sb.AppendLine("        }");
        sb.AppendLine();

        sb.AppendLine("        private static int GetLength(Slot slot)");
        sb.AppendLine("        {");
        sb.AppendLine("            switch (slot)");
        sb.AppendLine("            {");
        foreach (var fn in obj.Functions)
        {
            sb.Append("                case Slot.").Append(fn.ClrName).Append(": return ").Append(fn.Length).AppendLine(";");
        }
        sb.AppendLine("                default: throw UnknownSlot(slot);");
        sb.AppendLine("            }");
        sb.AppendLine("        }");
        sb.AppendLine();

        sb.AppendLine("        private static global::System.InvalidOperationException UnknownSlot(Slot slot)");
        sb.AppendLine("            => new global::System.InvalidOperationException(\"Unknown slot \" + slot + \" — generator/runtime mismatch.\");");

        sb.AppendLine("    }");
    }

    private static void EmitInvocation(StringBuilder sb, ObjectDefinition obj, FunctionDefinition fn)
    {
        if (fn.IsStatic) sb.Append(obj.Name).Append('.');
        else sb.Append("_host.");
        sb.Append(fn.ClrName).Append('(');

        var first = true;
        foreach (var p in fn.Parameters)
        {
            if (!first) sb.Append(", ");
            first = false;
            switch (p.Kind)
            {
                case ParameterKind.ThisObject:
                    sb.Append(p.CastTargetType is null ? "thisObject" : "__cast");
                    break;
                case ParameterKind.ValueAt:
                    sb.Append("global::Jint.Runtime.Arguments.At(arguments, ").Append(p.Position).Append(')');
                    break;
                case ParameterKind.ToNumber:
                    sb.Append("global::Jint.Runtime.TypeConverter.ToNumber(global::Jint.Runtime.Arguments.At(arguments, ").Append(p.Position).Append("))");
                    break;
                case ParameterKind.ToInt32:
                    sb.Append("global::Jint.Runtime.TypeConverter.ToInt32(global::Jint.Runtime.Arguments.At(arguments, ").Append(p.Position).Append("))");
                    break;
                case ParameterKind.ToUint32:
                    sb.Append("global::Jint.Runtime.TypeConverter.ToUint32(global::Jint.Runtime.Arguments.At(arguments, ").Append(p.Position).Append("))");
                    break;
                case ParameterKind.ToInteger:
                    sb.Append("global::Jint.Runtime.TypeConverter.ToInteger(global::Jint.Runtime.Arguments.At(arguments, ").Append(p.Position).Append("))");
                    break;
                case ParameterKind.ToLength:
                    sb.Append("global::Jint.Runtime.TypeConverter.ToLength(global::Jint.Runtime.Arguments.At(arguments, ").Append(p.Position).Append("))");
                    break;
                case ParameterKind.ToString:
                    sb.Append("global::Jint.Runtime.TypeConverter.ToString(global::Jint.Runtime.Arguments.At(arguments, ").Append(p.Position).Append("))");
                    break;
                case ParameterKind.ToJsString:
                    sb.Append("global::Jint.Runtime.TypeConverter.ToJsString(global::Jint.Runtime.Arguments.At(arguments, ").Append(p.Position).Append("))");
                    break;
                case ParameterKind.ToObject:
                    sb.Append("global::Jint.Runtime.TypeConverter.ToObject(_realm, global::Jint.Runtime.Arguments.At(arguments, ").Append(p.Position).Append("))");
                    break;
                case ParameterKind.Rest:
                    // Slice past the fixed positional value parameters into a ReadOnlySpan over the array tail; no allocation.
                    if (p.Position == 0)
                    {
                        sb.Append("new global::System.ReadOnlySpan<global::Jint.Native.JsValue>(arguments, 0, arguments.Length)");
                    }
                    else
                    {
                        sb.Append("new global::System.ReadOnlySpan<global::Jint.Native.JsValue>(arguments, ");
                        sb.Append("global::System.Math.Min(").Append(p.Position).Append(", arguments.Length), ");
                        sb.Append("global::System.Math.Max(0, arguments.Length - ").Append(p.Position).Append("))");
                    }
                    break;
                case ParameterKind.AllArguments:
                    sb.Append("arguments");
                    break;
            }
        }

        sb.Append(')');
    }

    private static void EmitSymbolInitialize(StringBuilder sb, ObjectDefinition obj)
    {
        var symbolFunctions = new List<FunctionDefinition>();
        var symbolAccessorsByName = new Dictionary<string, (FunctionDefinition? Get, FunctionDefinition? Set, string Flags)>(StringComparer.Ordinal);
        foreach (var fn in obj.Functions)
        {
            switch (fn.Registration)
            {
                case RegistrationKind.SymbolFunction:
                    symbolFunctions.Add(fn);
                    break;
                case RegistrationKind.SymbolAccessorGet:
                    symbolAccessorsByName.TryGetValue(fn.JsName, out var slotG);
                    symbolAccessorsByName[fn.JsName] = (fn, slotG.Set, slotG.Get is null && slotG.Set is null ? fn.FlagsExpression : slotG.Flags);
                    break;
                case RegistrationKind.SymbolAccessorSet:
                    symbolAccessorsByName.TryGetValue(fn.JsName, out var slotS);
                    symbolAccessorsByName[fn.JsName] = (slotS.Get, fn, slotS.Get is null && slotS.Set is null ? fn.FlagsExpression : slotS.Flags);
                    break;
            }
        }

        var totalEntries = obj.Symbols.Count + symbolFunctions.Count + symbolAccessorsByName.Count;

        sb.AppendLine("    /// <summary>Generated symbol-keyed registration. Call from <c>Initialize()</c>.</summary>");
        sb.AppendLine("    private void CreateSymbols_Generated()");
        sb.AppendLine("    {");
        sb.Append("        var symbols = new global::Jint.Collections.DictionarySlim<global::Jint.Native.JsSymbol, global::Jint.Runtime.Descriptors.PropertyDescriptor>(")
          .Append(totalEntries)
          .AppendLine(");");

        foreach (var sym in obj.Symbols)
        {
            sb.Append("        symbols[global::Jint.Native.Symbol.GlobalSymbolRegistry.").Append(sym.SymbolName).Append("] = new global::Jint.Runtime.Descriptors.PropertyDescriptor(");
            if (sym.IsStatic) sb.Append(obj.Name).Append('.');
            sb.Append(sym.ClrName).Append(", ");
            sb.Append(sym.FlagsExpression);
            sb.AppendLine(");");
        }

        foreach (var fn in symbolFunctions)
        {
            sb.Append("        symbols[global::Jint.Native.Symbol.GlobalSymbolRegistry.").Append(fn.JsName).Append("] = new global::Jint.Runtime.Descriptors.Specialized.LazyPropertyDescriptor<")
              .Append(obj.Name).Append(">(this, static host => new __").Append(obj.Name).Append("Function(host, __")
              .Append(obj.Name).Append("Function.Slot.").Append(fn.ClrName).Append("), ").Append(fn.FlagsExpression).AppendLine(");");
        }

        // Symbol-keyed accessors: GetSetPropertyDescriptor wrapping eagerly-allocated dispatcher slots,
        // registered under GlobalSymbolRegistry.<SymbolName>.
        var symbolAccessorNames = new List<string>(symbolAccessorsByName.Keys);
        symbolAccessorNames.Sort(StringComparer.Ordinal);
        foreach (var name in symbolAccessorNames)
        {
            var (getFn, setFn, flagsExpr) = symbolAccessorsByName[name];
            sb.Append("        symbols[global::Jint.Native.Symbol.GlobalSymbolRegistry.").Append(name).Append("] = new global::Jint.Runtime.Descriptors.GetSetPropertyDescriptor(");
            if (getFn is not null)
            {
                sb.Append("new __").Append(obj.Name).Append("Function(this, __").Append(obj.Name).Append("Function.Slot.").Append(getFn.ClrName).Append(')');
            }
            else
            {
                sb.Append("null");
            }
            sb.Append(", ");
            if (setFn is not null)
            {
                sb.Append("new __").Append(obj.Name).Append("Function(this, __").Append(obj.Name).Append("Function.Slot.").Append(setFn.ClrName).Append(')');
            }
            else
            {
                sb.Append("null");
            }
            sb.Append(", ").Append(flagsExpr).AppendLine(");");
        }

        sb.AppendLine("        SetSymbols(symbols);");
        sb.AppendLine("    }");
    }

    private static string EscapeStringLit(string s)
        => s.Replace("\\", "\\\\").Replace("\"", "\\\"");
}
