namespace Jint.HtmlParser.Css.Values.Properties;

// Exact pinned 433-registration assignment: docs/design/html-parser-cssom.md appendix.
// A family assignment is an obligation, not a claim of implemented grammar or allowed context.
internal static class CssPropertyCatalog
{
    internal static IReadOnlyDictionary<string, string> Obligations { get; } = Create();

    private static System.Collections.ObjectModel.ReadOnlyDictionary<string, string> Create()
    {
        var names = new Dictionary<string, string>(StringComparer.Ordinal);
        Add(names, "V1", "accent-color appearance background background-attachment background-blend-mode background-clip background-color background-image background-origin background-position background-position-x background-position-y background-repeat background-repeat-x background-repeat-y background-size border border-block border-block-color border-block-end border-block-end-color border-block-end-style border-block-end-width border-block-start border-block-start-color border-block-start-style border-block-start-width border-block-style border-block-width border-bottom border-bottom-color border-bottom-left-radius border-bottom-right-radius border-bottom-style border-bottom-width border-color border-end-end-radius border-end-start-radius border-image border-image-outset border-image-repeat border-image-slice border-image-source border-image-width border-inline border-inline-color border-inline-end border-inline-end-color border-inline-end-style border-inline-end-width border-inline-start border-inline-start-color border-inline-start-style border-inline-start-width border-inline-style border-inline-width border-left border-left-color border-left-style border-left-width border-radius border-right border-right-color border-right-style border-right-width border-start-end-radius border-start-start-radius border-style border-top border-top-color border-top-left-radius border-top-right-radius border-top-style border-top-width border-width box-decoration-break box-shadow caret-color color color-scheme forced-color-adjust isolation mix-blend-mode opacity outline outline-color outline-offset outline-style outline-width print-color-adjust");
        Add(names, "V2", "anchor-name anchor-scope aspect-ratio block-size bottom box-sizing clear float height inline-size inset inset-block inset-block-end inset-block-start inset-inline inset-inline-end inset-inline-start left margin margin-block margin-block-end margin-block-start margin-bottom margin-inline margin-inline-end margin-inline-start margin-left margin-right margin-top max-block-size max-height max-inline-size max-width min-block-size min-height min-inline-size min-width padding padding-block padding-block-end padding-block-start padding-bottom padding-inline padding-inline-end padding-inline-start padding-left padding-right padding-top position position-anchor position-area position-try-fallbacks position-try-order position-visibility right top width z-index");
        Add(names, "V3", "align-content align-items align-self break-after break-before break-inside column-count column-fill column-gap column-rule column-rule-color column-rule-style column-rule-width column-span column-width columns contain contain-intrinsic-block-size contain-intrinsic-height contain-intrinsic-inline-size contain-intrinsic-size contain-intrinsic-width container container-name container-type content-visibility display flex flex-basis flex-direction flex-flow flex-grow flex-shrink flex-wrap gap grid grid-area grid-auto-columns grid-auto-flow grid-auto-rows grid-column grid-column-end grid-column-gap grid-column-start grid-gap grid-row grid-row-end grid-row-gap grid-row-start grid-template grid-template-areas grid-template-columns grid-template-rows justify-content justify-items justify-self order place-content place-items place-self row-gap");
        Add(names, "V4", "direction font font-family font-feature-settings font-kerning font-language-override font-optical-sizing font-palette font-size font-size-adjust font-stretch font-style font-synthesis font-synthesis-small-caps font-synthesis-style font-synthesis-weight font-variant font-variation-settings font-weight hanging-punctuation hyphenate-character hyphenate-limit-chars hyphens initial-letter initial-letter-align letter-spacing line-break line-height ruby-align ruby-overhang ruby-position tab-size text-align text-align-last text-anchor text-decoration text-decoration-color text-decoration-line text-decoration-skip-ink text-decoration-style text-decoration-thickness text-indent text-justify text-overflow text-shadow text-transform text-underline-offset text-underline-position text-wrap text-wrap-mode text-wrap-style unicode-bidi vertical-align white-space white-space-collapse word-break word-spacing word-wrap writing-mode");
        Add(names, "V5", "animation animation-composition animation-delay animation-direction animation-duration animation-fill-mode animation-iteration-count animation-name animation-play-state animation-range animation-range-end animation-range-start animation-timeline animation-timing-function backface-visibility perspective perspective-origin rotate scale transform transform-origin transform-style transition transition-delay transition-duration transition-property transition-timing-function translate view-transition-class view-transition-name will-change");
        Add(names, "V6", "cursor overflow overflow-anchor overflow-clip-margin overflow-wrap overflow-x overflow-y overscroll-behavior overscroll-behavior-block overscroll-behavior-inline overscroll-behavior-x overscroll-behavior-y pointer-events resize scroll-behavior scroll-margin scroll-margin-block scroll-margin-block-end scroll-margin-block-start scroll-margin-bottom scroll-margin-inline scroll-margin-inline-end scroll-margin-inline-start scroll-margin-left scroll-margin-right scroll-margin-top scroll-padding scroll-padding-block scroll-padding-block-end scroll-padding-block-start scroll-padding-bottom scroll-padding-inline scroll-padding-inline-end scroll-padding-inline-start scroll-padding-left scroll-padding-right scroll-padding-top scroll-snap-stop scroll-snap-type scrollbar-arrow-color scrollbar-base-color scrollbar-color scrollbar-dark-shadow-color scrollbar-face-color scrollbar-gutter scrollbar-highlight-color scrollbar-shadow-color scrollbar-track-color scrollbar-width scrollbar3d-light-color touch-action user-select visibility");
        Add(names, "V7", "alignment-baseline backdrop-filter baseline-shift clip clip-path clip-rule color-interpolation-filters dominant-baseline fill fill-opacity fill-rule filter image-orientation image-rendering marker-end marker-mid marker-start mask mask-border mask-border-mode mask-border-outset mask-border-repeat mask-border-slice mask-border-source mask-border-width mask-clip mask-composite mask-image mask-mode mask-origin mask-position mask-repeat mask-size mask-type object-fit object-position shape-image-threshold shape-margin shape-outside shape-rendering stroke stroke-dasharray stroke-dashoffset stroke-linecap stroke-linejoin stroke-miterlimit stroke-opacity stroke-width");
        Add(names, "V8", "bookmark-label bookmark-level bookmark-state border-collapse border-spacing caption-side content counter-increment counter-reset counter-set empty-cells footnote-display footnote-policy list-style list-style-image list-style-position list-style-type orphans page-break-after page-break-before page-break-inside quotes running string-set table-layout widows");
        Add(names, "V9", "ascent-override descent-override font-display line-gap-override size-adjust src unicode-range");
        return new System.Collections.ObjectModel.ReadOnlyDictionary<string, string>(names);
    }

    private static void Add(Dictionary<string, string> names, string family, string assigned)
    {
        foreach (var name in assigned.Split(' ')) names.Add(name, family);
    }
}
