#nullable enable

using System.Globalization;
using System.Net.Http;
using System.Text;
using System.Text.RegularExpressions;

namespace Jint.Tests;

/// <summary>
/// Every <c>tc39.es</c> anchor this repository cites, held against a checked-in register of anchors that
/// were verified to exist in the document that defines them.
/// </summary>
/// <remarks>
/// <para>
/// <b>Why a test.</b> The root <c>AGENTS.md</c> already says code cites the section it implements and that
/// the citations are maintained when anchors get renamed. Nothing enforced it, and nothing could notice: a
/// fragment that no longer exists does not 404, it silently lands the reader at the top of the document. By
/// the time <see href="https://github.com/sebastienros/jint/issues/3508">#3508</see> was filed, 34 of the
/// ECMA-402 anchors Jint cited had been renamed out from under it — including the two carrying the argument
/// that <c>format</c> is the concatenation of <c>formatToParts</c>, which are the citations a reader is most
/// likely to follow, because the surrounding prose is arguing from them.
/// </para>
/// <para>
/// <b>Why a register rather than a live check.</b> Fetching ten megabytes of specification would make every
/// run depend on tc39.es being up and on the machine having a network, and would fail for reasons that have
/// nothing to do with the change under test. So the anchors are resolved once, into
/// <c>Jint.Tests/SpecAnchors.txt</c>, and an ordinary run only compares against it. That catches the half
/// worth catching per-commit: a citation written or edited without checking it, because its anchor is not in
/// the register and the register is only regenerated by fetching the documents.
/// </para>
/// <para>
/// <b>What it does not catch.</b> Rot in an anchor nobody touched — the exact failure #3508 describes — is
/// found only by re-running the update, which re-verifies every registered anchor against the living
/// documents. That is a periodic chore rather than a gate, and the <c>verified</c> date at the top of the
/// register is what says how stale the answer is.
/// </para>
/// <para>
/// <b>The absent list is debt, not configuration.</b> A <c>!</c> line records an anchor that is cited and
/// that its document does not have — because the citation is waiting on another pull request, or because the
/// rendered document is itself frozen behind the text it describes. Each carries its reason, and an update
/// refuses to add one on its own: an anchor that stops resolving fails the run, and a person decides whether
/// it is repointed or recorded.
/// </para>
/// </remarks>
public class SpecCitationTests
{
    /// <summary>
    /// Every anchor the tree cites is one the register holds.
    /// </summary>
    [Test]
    public void EverySpecCitationNamesAnAnchorTheRegisterHolds()
    {
        var register = SpecAnchorRegister.Read();
        var cited = SpecCitations.InRepository();

        if (SpecAnchorRegister.UpdateRequested())
        {
            Regenerate(register, cited);
            return;
        }

        var unregistered = cited
            .Where(citation => !register.Holds(citation))
            .OrderBy(citation => citation.Location, StringComparer.Ordinal)
            .ToList();

        if (unregistered.Count == 0)
        {
            return;
        }

        var report = new StringBuilder();
        report.AppendLine(string.Format(
            CultureInfo.InvariantCulture,
            "{0} citation(s) name an anchor '{1}' does not hold:",
            unregistered.Count,
            SpecAnchorRegister.RelativePath));
        report.AppendLine();
        foreach (var citation in unregistered)
        {
            report.AppendLine("  " + citation.Location + ": " + citation.Url);
        }

        report.AppendLine();
        report.AppendLine("""
            An anchor reaches the register only once something has fetched the document and found the clause,
            which is the whole point of the register. Re-run with a network available:

                JINT_SPEC_ANCHORS=update dotnet test -c Release Jint.Tests/Jint.Tests.csproj -f net10.0 --filter "FullyQualifiedName~SpecCitationTests"

            then review the diff. If that run reports the anchor as absent instead, the citation is wrong:
            find the clause in the current document and repoint it.
            """);

        Assert.Fail(report.ToString());
    }

    /// <summary>
    /// The register names nothing the tree stopped citing, so it stays a list of live citations.
    /// </summary>
    [Test]
    public void TheRegisterNamesNoAnchorTheTreeStoppedCiting()
    {
        var register = SpecAnchorRegister.Read();
        var cited = new HashSet<string>(StringComparer.Ordinal);
        foreach (var citation in SpecCitations.InRepository())
        {
            cited.Add(citation.Key);
            if (citation.TrimmedKey is not null)
            {
                cited.Add(citation.TrimmedKey);
            }
        }

        var orphaned = register.All
            .Where(entry => !cited.Contains(entry))
            .OrderBy(entry => entry, StringComparer.Ordinal)
            .ToList();

        if (orphaned.Count == 0)
        {
            return;
        }

        Assert.Fail(
            "'" + SpecAnchorRegister.RelativePath + "' holds " + orphaned.Count.ToString(CultureInfo.InvariantCulture)
            + " anchor(s) nothing cites any more:" + Environment.NewLine + Environment.NewLine
            + string.Join(Environment.NewLine, orphaned.Select(entry => "  " + entry))
            + Environment.NewLine + Environment.NewLine
            + "Re-run with JINT_SPEC_ANCHORS=update to prune them.");
    }

    /// <summary>
    /// The register states the counts it holds, which is what catches a hand edit.
    /// </summary>
    [Test]
    public void TheRegisterStatesTheCountsItHolds()
    {
        var register = SpecAnchorRegister.Read();

        register.StatedAnchors.Should().Be(register.Anchors.Count, "'" + SpecAnchorRegister.RelativePath + "' states its own anchor count");
        register.StatedAbsent.Should().Be(register.Absent.Count, "'" + SpecAnchorRegister.RelativePath + "' states its own absent count");
        register.Verified.Should().NotBeEmpty("'" + SpecAnchorRegister.RelativePath + "' says when it was last checked");
    }

    private static void Regenerate(SpecAnchorRegister register, IReadOnlyList<SpecCitation> cited)
    {
        var documents = cited
            .Select(citation => citation.Document)
            .Distinct(StringComparer.Ordinal)
            .OrderBy(name => name, StringComparer.Ordinal)
            .ToList();

        var anchorsByDocument = new Dictionary<string, HashSet<string>>(StringComparer.Ordinal);
        foreach (var document in documents)
        {
            anchorsByDocument[document] = SpecDocument.AnchorsOf(document);
        }

        var resolved = new HashSet<string>(StringComparer.Ordinal);
        var absent = new List<SpecCitation>();

        foreach (var citation in cited)
        {
            var anchors = anchorsByDocument[citation.Document];
            if (anchors.Contains(citation.Anchor))
            {
                resolved.Add(citation.Key);
                continue;
            }

            var trimmed = citation.TrimmedKey;
            if (trimmed is not null && anchors.Contains(trimmed.Substring(citation.Document.Length + 1)))
            {
                resolved.Add(trimmed);
                continue;
            }

            absent.Add(citation);
        }

        var unaccepted = absent
            .Where(citation => !register.Records(citation.Key) && !(citation.TrimmedKey is not null && register.Records(citation.TrimmedKey)))
            .OrderBy(citation => citation.Location, StringComparer.Ordinal)
            .ToList();

        if (unaccepted.Count > 0)
        {
            var report = new StringBuilder();
            report.AppendLine(string.Format(
                CultureInfo.InvariantCulture,
                "{0} citation(s) name an anchor the document no longer has:",
                unaccepted.Count));
            report.AppendLine();
            foreach (var citation in unaccepted)
            {
                report.AppendLine("  " + citation.Location + ": " + citation.Url);
            }

            report.AppendLine();
            report.AppendLine("""
                Find the clause in the current document and repoint the citation; where a clause was merged
                into another, cite the one it lives in now. If the rendered document is itself the thing that
                is wrong — a proposal page frozen before the text it describes — record the anchor in
                Jint.Tests/SpecAnchors.txt as a '!' line with that reason, and re-run.
                """);

            Assert.Fail(report.ToString());
        }

        var keptAbsent = new List<string>();
        var seen = new HashSet<string>(StringComparer.Ordinal);
        foreach (var citation in absent)
        {
            var key = register.Records(citation.Key) || citation.TrimmedKey is null ? citation.Key : citation.TrimmedKey;
            if (seen.Add(key))
            {
                keptAbsent.Add(register.RecordOf(key));
            }
        }

        var path = SpecAnchorRegister.Write(resolved, keptAbsent);
        TestContext.Out.WriteLine(string.Format(
            CultureInfo.InvariantCulture,
            "Wrote {0} verified anchor(s) and {1} absent one(s) to {2}.",
            resolved.Count,
            keptAbsent.Count,
            path));
    }
}

/// <summary>
/// One <c>https://tc39.es/{document}/#{anchor}</c> citation, and where it is written.
/// </summary>
internal sealed record SpecCitation(string Document, string Anchor, string Location)
{
    /// <summary>The register's key for this citation: the document and the anchor, space separated.</summary>
    internal string Key => Document + " " + Anchor;

    /// <summary>
    /// The same key with a trailing full stop dropped, since a citation written inside prose can end at a
    /// sentence and the stop is not part of the anchor. Null when the anchor does not end in one.
    /// </summary>
    internal string? TrimmedKey
    {
        get
        {
            var trimmed = Anchor.TrimEnd('.', '-');
            return trimmed.Length == Anchor.Length ? null : Document + " " + trimmed;
        }
    }

    /// <summary>The citation as it is written.</summary>
    internal string Url => "https://tc39.es/" + Document + "/#" + Anchor;
}

/// <summary>
/// The <c>tc39.es</c> citations written anywhere in the working tree.
/// </summary>
internal static class SpecCitations
{
    private static readonly Regex _citation = new(
        @"https://tc39\.es/(ecma262|ecma402|proposal-[A-Za-z0-9-]+)/#([A-Za-z0-9._%@~-]*)",
        RegexOptions.Compiled);

    private static readonly string[] _scanned = [".cs", ".md", ".js", ".json", ".txt", ".props", ".targets", ".csproj", ".yml"];

    private static readonly string[] _skipped = [".git", ".vs", ".idea", "bin", "obj", "node_modules", "packages", "TestResults", "artifacts"];

    /// <summary>
    /// Every citation in the repository, in no particular order.
    /// </summary>
    internal static IReadOnlyList<SpecCitation> InRepository()
    {
        var root = AgentInstructionFiles.RepositoryRoot;
        var found = new List<SpecCitation>();
        Collect(root, root, found);
        return found;
    }

    private static void Collect(string root, string directory, List<SpecCitation> found)
    {
        foreach (var file in Directory.EnumerateFiles(directory))
        {
            if (!_scanned.Contains(Path.GetExtension(file), StringComparer.OrdinalIgnoreCase))
            {
                continue;
            }

            var relative = file.Substring(root.Length)
                .TrimStart(Path.DirectorySeparatorChar, Path.AltDirectorySeparatorChar)
                .Replace('\\', '/');

            var line = 0;
            foreach (var text in File.ReadLines(file))
            {
                line++;
                if (text.IndexOf("tc39.es/", StringComparison.Ordinal) < 0)
                {
                    continue;
                }

                foreach (Match match in _citation.Matches(text))
                {
                    var anchor = match.Groups[2].Value;

                    // "sec-..." is how AGENTS.md writes the shape of a citation, not a citation.
                    if (anchor.Length == 0 || anchor.IndexOf("..", StringComparison.Ordinal) >= 0)
                    {
                        continue;
                    }

                    var location = relative + ":" + line.ToString(CultureInfo.InvariantCulture);
                    found.Add(new SpecCitation(match.Groups[1].Value, anchor, location));
                }
            }
        }

        foreach (var child in Directory.EnumerateDirectories(directory))
        {
            if (_skipped.Contains(Path.GetFileName(child), StringComparer.OrdinalIgnoreCase))
            {
                continue;
            }

            Collect(root, child, found);
        }
    }
}

/// <summary>
/// The anchors a rendered ecmarkup document defines, read from tc39.es.
/// </summary>
internal static class SpecDocument
{
    // ecmarkup minifies some of these documents and not others, so both quoted and bare values occur.
    private static readonly Regex _identifier = new(
        @"\bid=(?:""([^""]*)""|([A-Za-z0-9._%@~:-]+))",
        RegexOptions.Compiled);

    // An "oldids" list is rendered as real anchors too, so a renamed clause still answers its former name.
    private static readonly Regex _formerIdentifiers = new(
        @"\boldids=(?:""([^""]*)""|([A-Za-z0-9._%@~,:-]+))",
        RegexOptions.Compiled);

    /// <summary>
    /// Every anchor <c>https://tc39.es/{document}/</c> answers to today.
    /// </summary>
    internal static HashSet<string> AnchorsOf(string document)
    {
        var url = "https://tc39.es/" + document + "/";

        string html;
        using (var client = new HttpClient { Timeout = TimeSpan.FromMinutes(2) })
        {
            try
            {
                html = client.GetStringAsync(url).GetAwaiter().GetResult();
            }
            catch (Exception exception)
            {
                throw new InvalidOperationException("Could not fetch '" + url + "'. Regenerating the anchor register needs a network.", exception);
            }
        }

        var anchors = new HashSet<string>(StringComparer.Ordinal);
        foreach (Match match in _identifier.Matches(html))
        {
            anchors.Add(match.Groups[1].Success ? match.Groups[1].Value : match.Groups[2].Value);
        }

        foreach (Match match in _formerIdentifiers.Matches(html))
        {
            var list = match.Groups[1].Success ? match.Groups[1].Value : match.Groups[2].Value;
            foreach (var former in list.Split(','))
            {
                anchors.Add(former);
            }
        }

        // A 404 or a redirect to something that is not the specification yields a handful of anchors at
        // most; the smallest proposal cited here still defines a dozen.
        if (anchors.Count < 5)
        {
            throw new InvalidOperationException(string.Format(
                CultureInfo.InvariantCulture,
                "'{0}' yielded only {1} anchors, so what came back is not the rendered specification.",
                url,
                anchors.Count));
        }

        return anchors;
    }
}

/// <summary>
/// <c>Jint.Tests/SpecAnchors.txt</c>: the anchors that were checked against the documents defining them.
/// </summary>
internal sealed class SpecAnchorRegister
{
    /// <summary>Set to <c>update</c> to re-verify every anchor and rewrite the file.</summary>
    internal const string UpdateVariable = "JINT_SPEC_ANCHORS";

    /// <summary>Where the register lives, for an error message to name.</summary>
    internal const string RelativePath = "Jint.Tests/SpecAnchors.txt";

    private const string VerifiedPrefix = "verified: ";
    private const string AnchorsPrefix = "anchors: ";
    private const string AbsentPrefix = "absent: ";

    private static readonly string[] _header =
    [
        "# Every spec anchor this repository cites, checked against the document that defines it.",
        "#",
        "# One line per anchor, as \"<document> <anchor>\", where <document> is the path segment under",
        "# tc39.es. A '!' line is the opposite: an anchor that is cited and that the document does not have,",
        "# kept with the reason it is still written that way. Those are debt, and a regeneration will not",
        "# add one on its own — an anchor that stops resolving fails the run instead.",
        "#",
        "# The gate is Jint.Tests/SpecCitationTests.cs. To re-verify every anchor against the living",
        "# documents and rewrite this file, with a network available:",
        "#",
        "#     JINT_SPEC_ANCHORS=update dotnet test -c Release Jint.Tests/Jint.Tests.csproj \\",
        "#         -f net10.0 --filter \"FullyQualifiedName~SpecCitationTests\"",
        "#",
        "# The 'verified' date is the only thing bounding anchor rot: a clause renamed upstream keeps",
        "# resolving here until somebody re-runs that.",
        "#",
    ];

    private readonly Dictionary<string, string> _absent;
    private readonly HashSet<string> _anchors;

    private SpecAnchorRegister(string verified, int statedAnchors, int statedAbsent, List<string> anchors, Dictionary<string, string> absent)
    {
        Verified = verified;
        StatedAnchors = statedAnchors;
        StatedAbsent = statedAbsent;
        Anchors = anchors;
        _anchors = new HashSet<string>(anchors, StringComparer.Ordinal);
        _absent = absent;
    }

    /// <summary>The date the file states its anchors were last checked, as <c>yyyy-MM-dd</c>.</summary>
    internal string Verified { get; }

    /// <summary>The anchor count the file states.</summary>
    internal int StatedAnchors { get; }

    /// <summary>The absent-anchor count the file states.</summary>
    internal int StatedAbsent { get; }

    /// <summary>The verified anchors, as <c>"{document} {anchor}"</c> keys.</summary>
    internal IReadOnlyList<string> Anchors { get; }

    /// <summary>The recorded absences, as <c>"{document} {anchor}"</c> keys.</summary>
    internal IReadOnlyCollection<string> Absent => _absent.Keys;

    /// <summary>Every key the file holds, verified or recorded absent.</summary>
    internal IEnumerable<string> All => Anchors.Concat(_absent.Keys);

    /// <summary>Whether the register accounts for this citation at all.</summary>
    internal bool Holds(SpecCitation citation)
        => Holds(citation.Key) || (citation.TrimmedKey is not null && Holds(citation.TrimmedKey));

    private bool Holds(string key) => _anchors.Contains(key) || _absent.ContainsKey(key);

    /// <summary>Whether the register already records this key as absent from its document.</summary>
    internal bool Records(string key) => _absent.ContainsKey(key);

    /// <summary>The recorded absence line for this key, reason and all.</summary>
    internal string RecordOf(string key)
    {
        var reason = _absent[key];
        return reason.Length == 0 ? key : key + "  # " + reason;
    }

    /// <summary>Whether this run was asked to re-verify and rewrite the register.</summary>
    internal static bool UpdateRequested()
        => string.Equals(Environment.GetEnvironmentVariable(UpdateVariable), "update", StringComparison.OrdinalIgnoreCase);

    /// <summary>The register's absolute path in this checkout.</summary>
    internal static string Path()
        => System.IO.Path.Combine(AgentInstructionFiles.RepositoryRoot, "Jint.Tests", "SpecAnchors.txt");

    /// <summary>Reads the register as it is checked in.</summary>
    internal static SpecAnchorRegister Read()
    {
        var verified = "";
        var statedAnchors = -1;
        var statedAbsent = -1;
        var anchors = new List<string>();
        var absent = new Dictionary<string, string>(StringComparer.Ordinal);

        foreach (var raw in File.ReadLines(Path()))
        {
            var line = raw.Trim();
            if (line.Length == 0 || line[0] == '#')
            {
                continue;
            }

            if (line.StartsWith(VerifiedPrefix, StringComparison.Ordinal))
            {
                verified = line.Substring(VerifiedPrefix.Length).Trim();
                continue;
            }

            if (line.StartsWith(AnchorsPrefix, StringComparison.Ordinal))
            {
                statedAnchors = int.Parse(line.Substring(AnchorsPrefix.Length).Trim(), CultureInfo.InvariantCulture);
                continue;
            }

            if (line.StartsWith(AbsentPrefix, StringComparison.Ordinal))
            {
                statedAbsent = int.Parse(line.Substring(AbsentPrefix.Length).Trim(), CultureInfo.InvariantCulture);
                continue;
            }

            if (line[0] == '!')
            {
                var comment = line.IndexOf('#');
                var reason = comment < 0 ? "" : line.Substring(comment + 1).Trim();
                var key = (comment < 0 ? line.Substring(1) : line.Substring(1, comment - 1)).Trim();
                absent[key] = reason;
                continue;
            }

            anchors.Add(line);
        }

        return new SpecAnchorRegister(verified, statedAnchors, statedAbsent, anchors, absent);
    }

    /// <summary>Rewrites the register, and answers where it was written.</summary>
    internal static string Write(IReadOnlyCollection<string> anchors, IReadOnlyCollection<string> absent)
    {
        var path = Path();

        // The working tree is CRLF on Windows and LF elsewhere; keep whichever the file already uses, so a
        // regeneration is a diff of the entries and nothing else.
        var newLine = File.Exists(path) && File.ReadAllText(path).Contains("\r\n", StringComparison.Ordinal) ? "\r\n" : "\n";

        var builder = new StringBuilder();
        foreach (var line in _header)
        {
            builder.Append(line).Append(newLine);
        }

        builder.Append(VerifiedPrefix).Append(DateTime.UtcNow.ToString("yyyy-MM-dd", CultureInfo.InvariantCulture)).Append(newLine);
        builder.Append(AnchorsPrefix).Append(anchors.Count.ToString(CultureInfo.InvariantCulture)).Append(newLine);
        builder.Append(AbsentPrefix).Append(absent.Count.ToString(CultureInfo.InvariantCulture)).Append(newLine);

        foreach (var line in absent.OrderBy(entry => entry, StringComparer.Ordinal))
        {
            builder.Append('!').Append(line).Append(newLine);
        }

        foreach (var line in anchors.OrderBy(entry => entry, StringComparer.Ordinal))
        {
            builder.Append(line).Append(newLine);
        }

        File.WriteAllText(path, builder.ToString(), new UTF8Encoding(encoderShouldEmitUTF8Identifier: false));
        return path;
    }
}
