#nullable enable

using System.IO.Compression;
using System.Security.Cryptography;
using System.Text;
using Jint.Native.Intl.Data;

namespace Jint.Tests.Runtime;

/// <summary>
/// <c>DateTimePatterns.bin</c> and its loader, <see cref="DateTimePatternData"/>: CLDR 48.2's Gregorian patterns and
/// names for every locale cldr-json carries, generated by <c>tools/cldr-dates</c>.
/// </summary>
/// <remarks>
/// These pin the data and the loader on their own, apart from the format matcher that reads them
/// (<see cref="IntlDateTimeFormatMatcherTests"/>): that the embedded resource is the one its generated header describes, that every
/// locale carries well-formed patterns and complete name tables, that a locale is rebuilt through the right parents,
/// and that the formats https://tc39.es/ecma402/#sec-intl.datetimeformat-internal-slots requires exist for every
/// locale. The expected values are CLDR's, read from cldr-json rather than from the loader.
/// </remarks>
public class IntlDateTimePatternDataTests
{
    private const string ResourceName = "Jint.Native.Intl.Data.DateTimePatterns.bin";

    /// <summary>
    /// The letters ECMA-402's fields map to, as the generator checks them.
    /// </summary>
    private const string AllowedLetters = "GyMLdEcabBhHKkmsSzvO";

    /// <summary>
    /// The six CLDR 48.2 availableFormats entries outside <see cref="AllowedLetters"/>, which the generator keeps and
    /// lists by name; a seventh fails both.
    /// </summary>
    private static readonly (string Locale, string Skeleton, string Letters)[] _knownLetterExceptions =
    [
        ("de-CH", "GyMEd", "Y"),
        ("fa", "HHmmZ", "Z"),
        ("fa-AF", "HHmmZ", "Z"),
        ("gd", "yMMM", "Y"),
        ("ksh", "yM", "Y"),
        ("sc", "yM", "Y"),
    ];

    private static DateTimePatternData Data => DateTimePatternData.Shared;

    private static Stream OpenResource() => typeof(Engine).Assembly.GetManifestResourceStream(ResourceName)!;

    /// <summary>
    /// Decodes the resource independently of the loader and hashes what it holds: the constants the generator wrote
    /// beside it must describe it, or one of the two was regenerated without the other.
    /// </summary>
    [Test]
    public void TheEmbeddedResourceIsTheOneItsGeneratedHeaderDescribes()
    {
        byte[] file;
        using (var stream = OpenResource())
        using (var buffer = new MemoryStream())
        {
            stream.CopyTo(buffer);
            file = buffer.ToArray();
        }

        Encoding.ASCII.GetString(file, 0, 4).Should().Be("JDTP");
        file[4].Should().Be(1);
        var position = 5;
        var indexRawLength = ReadVarint(file, ref position);
        var indexCompressedLength = ReadVarint(file, ref position);
        var index = Inflate(file, position, indexCompressedLength, indexRawLength);
        var blockArea = position + indexCompressedLength;

        var indexPosition = 0;
        ReadString(index, ref indexPosition).Should().Be(DateTimePatternData.CldrVersion);
        var slotCount = ReadVarint(index, ref indexPosition);
        slotCount.Should().Be(DateTimePatternData.SlotCount);
        var slotNames = new List<string>();
        for (var i = 0; i < slotCount; i++)
        {
            slotNames.Add(ReadString(index, ref indexPosition));
        }

        slotNames.Should().Equal(ExpectedSlotNames());

        using var payload = new MemoryStream();
        payload.Write(index, 0, index.Length);
        var blockCount = ReadVarint(index, ref indexPosition);
        var locales = 0;
        var blockEnd = blockArea;
        for (var block = 0; block < blockCount; block++)
        {
            ReadString(index, ref indexPosition);
            var offset = ReadVarint(index, ref indexPosition);
            var compressedLength = ReadVarint(index, ref indexPosition);
            var rawLength = ReadVarint(index, ref indexPosition);
            var raw = Inflate(file, blockArea + offset, compressedLength, rawLength);
            payload.Write(raw, 0, raw.Length);
            blockEnd = Math.Max(blockEnd, blockArea + offset + compressedLength);
            var localeCount = ReadVarint(index, ref indexPosition);
            for (var i = 0; i < localeCount; i++)
            {
                ReadString(index, ref indexPosition);
            }

            locales += localeCount;
        }

        locales.Should().Be(DateTimePatternData.LocaleCount);
        blockEnd.Should().Be(file.Length, "the blocks end where the resource does");
        Sha256(payload.ToArray()).Should().Be(DateTimePatternData.PayloadSha256);
    }

    [Test]
    public void TheResourceCarriesEveryCldrJsonLocale()
    {
        DateTimePatternData.CldrVersion.Should().Be("48.2");
        Data.Locales.Should().HaveCount(766).And.OnlyHaveUniqueItems().And.Contain(["und", "en", "de-AT", "zh-Hant-HK", "ca-ES-valencia"]);
    }

    /// <summary>
    /// The generator writes each slot's name, which is its JSON path in cldr-json, into the resource, and the header
    /// test compares them with this list; the offsets <see cref="DateTimePatternLocale"/> reads by must name the
    /// same values.
    /// </summary>
    [Test]
    public void TheSlotOffsetsTheLoaderReadsByNameTheRightValues()
    {
        var expected = ExpectedSlotNames();
        expected.Should().HaveCount(DateTimePatternLocale.SlotCount);
        expected[DateTimePatternLocale.DateTimeFormatsStart].Should().Be("dateTimeFormats/full");
        expected[DateTimePatternLocale.AtTimeFormatsStart].Should().Be("dateTimeFormats-atTime/standard/full");
        expected[DateTimePatternLocale.DateFormatsStart].Should().Be("dateFormats/full");
        expected[DateTimePatternLocale.TimeFormatsStart].Should().Be("timeFormats/full");
        expected[DateTimePatternLocale.AppendItemsStart].Should().Be("dateTimeFormats/appendItems/Era");
        expected[DateTimePatternLocale.FieldDisplayNamesStart].Should().Be("fields/era/displayName");
        expected[DateTimePatternLocale.MonthsStart].Should().Be("months/format/abbreviated/1");
        expected[DateTimePatternLocale.WeekdaysStart].Should().Be("days/format/abbreviated/sun");
        expected[DateTimePatternLocale.ErasStart].Should().Be("eras/eraAbbr/0");
        expected[DateTimePatternLocale.DayPeriodsStart].Should().Be("dayPeriods/format/abbreviated/am");
    }

    /// <summary>
    /// The slot layout, as the generator's <c>SlotLayout</c> writes it.
    /// </summary>
    private static List<string> ExpectedSlotNames()
    {
        var expected = new List<string>();
        string[] styleWidths = ["full", "long", "medium", "short"];
        expected.AddRange(styleWidths.Select(w => "dateTimeFormats/" + w));
        expected.AddRange(styleWidths.Select(w => "dateTimeFormats-atTime/standard/" + w));
        expected.AddRange(styleWidths.Select(w => "dateFormats/" + w));
        expected.AddRange(styleWidths.Select(w => "timeFormats/" + w));
        expected.AddRange(new[] { "Era", "Year", "Quarter", "Month", "Week", "Day-Of-Week", "Day", "Hour", "Minute", "Second", "Timezone" }.Select(k => "dateTimeFormats/appendItems/" + k));
        expected.AddRange(new[] { "era", "year", "quarter", "month", "week", "weekday", "day", "hour", "minute", "second", "zone" }.Select(k => "fields/" + k + "/displayName"));
        foreach (var context in new[] { "format", "stand-alone" })
        {
            foreach (var width in new[] { "abbreviated", "wide", "narrow" })
            {
                expected.AddRange(Enumerable.Range(1, 12).Select(m => $"months/{context}/{width}/{m}"));
            }
        }

        foreach (var context in new[] { "format", "stand-alone" })
        {
            foreach (var width in new[] { "abbreviated", "wide", "narrow", "short" })
            {
                expected.AddRange(new[] { "sun", "mon", "tue", "wed", "thu", "fri", "sat" }.Select(d => $"days/{context}/{width}/{d}"));
            }
        }

        foreach (var width in new[] { "eraAbbr", "eraNames", "eraNarrow" })
        {
            expected.Add($"eras/{width}/0");
            expected.Add($"eras/{width}/1");
        }

        foreach (var width in new[] { "abbreviated", "wide", "narrow" })
        {
            expected.Add($"dayPeriods/format/{width}/am");
            expected.Add($"dayPeriods/format/{width}/pm");
        }

        return expected;
    }

    /// <summary>
    /// Every availableFormats pattern and every style pattern parses and uses only the letters ECMA-402's fields map
    /// to, save the entries CLDR itself writes otherwise; every join and appendItems pattern places what it joins.
    /// </summary>
    [Test]
    public void EveryPatternParsesAndUsesOnlyTheLettersEcma402FieldsMapTo()
    {
        var problems = new List<string>();
        var exceptionsSeen = new HashSet<(string, string)>();
        foreach (var id in Data.Locales)
        {
            var locale = Data.GetLocale(id);
            locale.Locale.Should().Be(id);
            if (locale.AvailableFormats.Length < 40)
            {
                problems.Add($"{id}: only {locale.AvailableFormats.Length} availableFormats");
            }

            foreach (var entry in locale.AvailableFormats.ToArray())
            {
                var extra = _knownLetterExceptions.FirstOrDefault(e => e.Locale == id && e.Skeleton == entry.Skeleton).Letters ?? "";
                if (extra.Length > 0)
                {
                    exceptionsSeen.Add((id, entry.Skeleton));
                }

                if (entry.Skeleton.Any(c => !AllowedLetters.Contains(c) && !extra.Contains(c)))
                {
                    problems.Add($"{id}: skeleton {entry.Skeleton}");
                }

                CheckPattern(id, entry.Skeleton, entry.Pattern, extra, problems);
            }

            for (var width = DateTimeStyleWidth.Full; width <= DateTimeStyleWidth.Short; width++)
            {
                CheckPattern(id, "dateFormats " + width, locale.GetDateFormat(width), "", problems);
                CheckPattern(id, "timeFormats " + width, locale.GetTimeFormat(width), "", problems);
                CheckJoin(id, "dateTimeFormats " + width, locale.GetDateTimeFormat(width), "01", problems);
                CheckJoin(id, "atTime " + width, locale.GetAtTimeFormat(width), "01", problems);
            }

            for (var field = DateTimeAppendField.Era; field <= DateTimeAppendField.Zone; field++)
            {
                CheckJoin(id, "appendItems " + field, locale.GetAppendItem(field), "012", problems);
            }
        }

        problems.Should().BeEmpty();
        exceptionsSeen.Should().BeEquivalentTo(_knownLetterExceptions.Select(e => (e.Locale, e.Skeleton)));
    }

    /// <summary>
    /// Twelve months and seven weekdays in both contexts and every width, two eras and am/pm in three widths, and a
    /// display name for every field appendItems names, none of them empty.
    /// </summary>
    [Test]
    public void EveryLocaleHasEveryNameTable()
    {
        var problems = new List<string>();
        foreach (var id in Data.Locales)
        {
            var locale = Data.GetLocale(id);
            foreach (var context in new[] { DateTimeNameContext.Format, DateTimeNameContext.StandAlone })
            {
                for (var width = DateTimeNameWidth.Abbreviated; width <= DateTimeNameWidth.Short; width++)
                {
                    if (width != DateTimeNameWidth.Short)
                    {
                        CheckNames(id, $"months {context} {width}", locale.GetMonthNames(context, width), 12, problems);
                    }

                    CheckNames(id, $"weekdays {context} {width}", locale.GetWeekdayNames(context, width), 7, problems);
                }
            }

            for (var width = DateTimeNameWidth.Abbreviated; width <= DateTimeNameWidth.Narrow; width++)
            {
                CheckNames(id, $"eras {width}", locale.GetEraNames(width), 2, problems);
                CheckNames(id, $"day periods {width}", locale.GetDayPeriodNames(width), 2, problems);
            }

            for (var field = DateTimeAppendField.Era; field <= DateTimeAppendField.Zone; field++)
            {
                if (string.IsNullOrEmpty(locale.GetFieldDisplayName(field)))
                {
                    problems.Add($"{id}: no display name for {field}");
                }
            }
        }

        problems.Should().BeEmpty();
    }

    [Test]
    public void MonthsHaveNoShortWidth()
    {
        var root = Data.GetLocale("und");
        Invoking(() => { _ = root.GetMonthNames(DateTimeNameContext.Format, DateTimeNameWidth.Short); }).Should().Throw<ArgumentOutOfRangeException>();
        Invoking(() => { _ = root.GetEraNames(DateTimeNameWidth.Short); }).Should().Throw<ArgumentOutOfRangeException>();
    }

    /// <summary>
    /// The subsets https://tc39.es/ecma402/#sec-intl.datetimeformat-internal-slots says every locale must have,
    /// checked without a matcher: a date subset needs a skeleton with exactly its fields; a time subset without a day
    /// period needs a 24-hour skeleton, and one with a day period a 12-hour skeleton whose pattern writes one; a subset
    /// with both needs the two and a dateTimeFormats join. Fractional seconds follow the seconds field, as ICU writes
    /// them, so they need a seconds pattern.
    /// </summary>
    /// <remarks>
    /// The 12-hour skeleton may name its day period itself: CLDR 48.2's <c>bal-Latn</c> writes <c>hm</c> as
    /// <c>h:mm</c>, with no day period, and has the subset only through <c>Bhm</c>, <c>h:mm B</c>.
    /// </remarks>
    [Test]
    public void EveryLocaleHasEveryFormatSubsetEcma402Requires()
    {
        string[][] required =
        [
            ["weekday", "year", "month", "day", "hour", "minute", "second", "fractionalSecondDigits"],
            ["weekday", "year", "month", "day", "hour", "minute", "second"],
            ["weekday", "year", "month", "day"],
            ["year", "month", "day"],
            ["year", "month"],
            ["month", "day"],
            ["month"],
            ["hour", "minute", "second", "fractionalSecondDigits"],
            ["hour", "minute", "second"],
            ["hour", "minute"],
            ["dayPeriod", "hour", "minute", "second", "fractionalSecondDigits"],
            ["dayPeriod", "hour", "minute", "second"],
            ["dayPeriod", "hour", "minute"],
            ["dayPeriod", "hour"],
        ];
        string[] dateFields = ["weekday", "year", "month", "day"];

        var problems = new List<string>();
        foreach (var id in Data.Locales)
        {
            var locale = Data.GetLocale(id);
            var entries = locale.AvailableFormats.ToArray().Select(e => (Fields: FieldsOf(e.Skeleton), e.Pattern)).ToList();
            foreach (var subset in required)
            {
                var date = subset.Where(f => dateFields.Contains(f)).ToHashSet();
                if (date.Count > 0 && !entries.Exists(e => e.Fields.SetEquals(date)))
                {
                    problems.Add($"{id}: no skeleton for {{{string.Join(", ", date)}}}");
                }

                var time = subset.Where(f => !dateFields.Contains(f) && f != "fractionalSecondDigits" && f != "dayPeriod").ToHashSet();
                if (time.Count > 0)
                {
                    var twelveHour = subset.Contains("dayPeriod");
                    var wanted = time.Select(f => f == "hour" ? (twelveHour ? "hour12" : "hour24") : f).ToHashSet();
                    var found = twelveHour
                        ? entries.Where(e => e.Fields.Where(f => f != "dayPeriod").ToHashSet().SetEquals(wanted) && PatternLetters(e.Pattern).IndexOfAny(['a', 'b', 'B']) >= 0).ToList()
                        : entries.Where(e => e.Fields.SetEquals(wanted)).ToList();

                    if (subset.Contains("fractionalSecondDigits"))
                    {
                        found = found.Where(e => PatternLetters(e.Pattern).Contains('s')).ToList();
                    }

                    if (found.Count == 0)
                    {
                        problems.Add($"{id}: no {(twelveHour ? "12" : "24")}-hour skeleton for {{{string.Join(", ", subset.Where(f => !dateFields.Contains(f)))}}}");
                    }
                }

                if (date.Count > 0 && time.Count > 0)
                {
                    for (var width = DateTimeStyleWidth.Full; width <= DateTimeStyleWidth.Short; width++)
                    {
                        var join = locale.GetDateTimeFormat(width);
                        if (!join.Contains("{0}") || !join.Contains("{1}"))
                        {
                            problems.Add($"{id}: dateTimeFormats {width} does not join a date and a time");
                        }
                    }
                }
            }
        }

        problems.Should().BeEmpty();
    }

    /// <summary>
    /// CLDR's parents, including the ones truncation would get wrong: the explicit table (<c>en-150</c> to
    /// <c>en-001</c>, <c>zh-Hant</c> and <c>sr-Latn</c> to the root, <c>nb</c> to <c>no</c>, <c>hi-Latn</c> to
    /// <c>en-IN</c>), the non-likely-script rule (<c>zh-Latn</c>), and a truncation to a default-content locale
    /// cldr-json leaves out (<c>ca-ES-valencia</c> skips <c>ca-ES</c>).
    /// </summary>
    [TestCase("de-AT", "de", "und")]
    [TestCase("en-150", "en-001", "en", "und")]
    [TestCase("en-GB", "en-001", "en", "und")]
    [TestCase("es-MX", "es-419", "es", "und")]
    [TestCase("zh-Hant-HK", "zh-Hant", "und")]
    [TestCase("zh-Hant-MO", "zh-Hant-HK", "zh-Hant", "und")]
    [TestCase("zh-Hans-SG", "zh-Hans", "zh", "und")]
    [TestCase("sr-Latn-BA", "sr-Latn", "und")]
    [TestCase("sr-Cyrl-BA", "sr-Cyrl", "sr", "und")]
    [TestCase("zh-Latn", "und")]
    [TestCase("nb", "no", "und")]
    [TestCase("hi-Latn", "en-IN", "en-001", "en", "und")]
    [TestCase("ca-ES-valencia", "ca", "und")]
    [TestCase("und")]
    public void EachLocaleInheritsThroughItsCldrParents(string locale, params string[] ancestors)
    {
        var chain = new List<string>();
        for (var parent = Data.GetParentLocale(locale); parent is not null; parent = Data.GetParentLocale(parent))
        {
            chain.Add(parent);
        }

        chain.Should().Equal(ancestors);
    }

    /// <summary>
    /// A tag is served by the locale the data carries under that name if there is one, and otherwise by the one
    /// standing in for it: cldr-json leaves out the default-content locales, so <c>de-DE</c> is <c>de</c> and
    /// <c>zh-TW</c> is <c>zh-Hant</c> (never <c>zh</c>, which is Simplified). Extensions are ignored; variants too,
    /// unless the data carries the tag with them.
    /// </summary>
    [TestCase("de-AT", "de-AT")]
    [TestCase("de-DE", "de")]
    [TestCase("de", "de")]
    [TestCase("en-US", "en")]
    [TestCase("en-GB", "en-GB")]
    [TestCase("EN-gb", "en-GB")]
    [TestCase("en-150", "en-150")]
    [TestCase("en-GB-u-ca-buddhist-hc-h12", "en-GB")]
    [TestCase("de-CH-1996", "de-CH")]
    [TestCase("ca-ES-valencia", "ca-ES-valencia")]
    [TestCase("pt-BR", "pt")]
    [TestCase("pt-PT", "pt-PT")]
    [TestCase("zh", "zh")]
    [TestCase("zh-CN", "zh")]
    [TestCase("zh-TW", "zh-Hant")]
    [TestCase("zh-HK", "zh-Hant-HK")]
    [TestCase("zh-Hant", "zh-Hant")]
    [TestCase("zh-Hant-TW", "zh-Hant")]
    [TestCase("sr", "sr")]
    [TestCase("sr-RS", "sr")]
    [TestCase("sr-Latn-RS", "sr-Latn")]
    [TestCase("sr-ME", "sr-Latn-ME")]
    [TestCase("nb-NO", "nb")]
    [TestCase("ja-JP", "ja")]
    [TestCase("und", "und")]
    [TestCase("tlh", "und")]
    public void ALocaleIsServedByTheCarriedLocaleThatStandsInForIt(string tag, string expected)
    {
        Data.ResolveLocale(tag).Should().Be(expected);
        Data.GetLocale(tag).Locale.Should().Be(expected);
    }

    /// <summary>
    /// Each locale's data is its own records laid over its parents', so a value can come from any level: de-AT's
    /// January is its own, its patterns de's; en-150's short time is its own, its short date en-001's; hi-Latn's
    /// weekdays are its own and its patterns en-IN's, across languages.
    /// </summary>
    [Test]
    public void ALocalesDataIsResolvedThroughItsParents()
    {
        var root = Data.GetLocale("und");
        Pattern(root, "yMd").Should().Be("y-MM-dd");
        root.GetMonthNames(DateTimeNameContext.Format, DateTimeNameWidth.Wide)[0].Should().Be("M01");
        root.GetEraNames(DateTimeNameWidth.Abbreviated).ToArray().Should().Equal("BCE", "CE");
        root.GetAppendItem(DateTimeAppendField.Day).Should().Be("{0} ({2}: {1})");
        root.GetFieldDisplayName(DateTimeAppendField.Weekday).Should().Be("Day of the Week");
        root.AvailableFormats.Length.Should().Be(49);

        var en = Data.GetLocale("en");
        Pattern(en, "yMd").Should().Be("M/d/y");
        en.GetAtTimeFormat(DateTimeStyleWidth.Full).Should().Be("{1} 'at' {0}");
        en.GetDateTimeFormat(DateTimeStyleWidth.Medium).Should().Be("{1}, {0}");
        en.GetDateFormat(DateTimeStyleWidth.Short).Should().Be("M/d/yy");
        en.GetTimeFormat(DateTimeStyleWidth.Short).Should().Be("h:mm a");
        en.GetEraNames(DateTimeNameWidth.Abbreviated).ToArray().Should().Equal("BC", "AD");
        en.GetWeekdayNames(DateTimeNameContext.Format, DateTimeNameWidth.Wide)[0].Should().Be("Sunday");
        en.GetFieldDisplayName(DateTimeAppendField.Weekday).Should().Be("day of the week");
        en.AvailableFormats.Length.Should().Be(49);

        var en001 = Data.GetLocale("en-001");
        Pattern(en001, "yMd").Should().Be("dd/MM/y");
        en001.GetDayPeriodNames(DateTimeNameWidth.Abbreviated)[0].Should().Be("am");
        en001.AvailableFormats.Length.Should().Be(50);

        var en150 = Data.GetLocale("en-150");
        Pattern(en150, "yMd").Should().Be("dd/MM/y");
        en150.GetTimeFormat(DateTimeStyleWidth.Short).Should().Be("HH:mm");
        en150.GetDateFormat(DateTimeStyleWidth.Short).Should().Be("dd/MM/y");
        en150.AvailableFormats.Length.Should().Be(50);

        var enGb = Data.GetLocale("en-GB");
        Pattern(enGb, "MEd").Should().Be("E dd/MM");
        enGb.AvailableFormats.Length.Should().Be(55);

        var de = Data.GetLocale("de");
        Pattern(de, "yMMMd").Should().Be("d. MMM y");
        de.GetAtTimeFormat(DateTimeStyleWidth.Full).Should().Be("{1} 'um' {0}");
        de.GetMonthNames(DateTimeNameContext.Format, DateTimeNameWidth.Wide)[0].Should().Be("Januar");
        de.GetWeekdayNames(DateTimeNameContext.Format, DateTimeNameWidth.Abbreviated)[0].Should().Be("So.");
        de.GetEraNames(DateTimeNameWidth.Abbreviated).ToArray().Should().Equal("v. Chr.", "n. Chr.");
        de.AvailableFormats.Length.Should().Be(54);

        var deAt = Data.GetLocale("de-AT");
        deAt.GetMonthNames(DateTimeNameContext.Format, DateTimeNameWidth.Wide)[0].Should().Be("Jänner");
        deAt.GetMonthNames(DateTimeNameContext.StandAlone, DateTimeNameWidth.Abbreviated)[0].Should().Be("Jän");
        Pattern(deAt, "yMMMd").Should().Be("d. MMM y");
        deAt.AvailableFormats.Length.Should().Be(54);

        Pattern(Data.GetLocale("de-CH"), "GyMEd").Should().Be("E, MM.dd.Y G");

        var hiLatn = Data.GetLocale("hi-Latn");
        hiLatn.GetAtTimeFormat(DateTimeStyleWidth.Full).Should().Be("{1}, {0} 'par'");
        hiLatn.GetWeekdayNames(DateTimeNameContext.Format, DateTimeNameWidth.Abbreviated)[0].Should().Be("Ravi");
        Pattern(hiLatn, "yMd").Should().Be("d/M/y");
        hiLatn.AvailableFormats.Length.Should().Be(55);

        var nb = Data.GetLocale("nb");
        nb.GetAtTimeFormat(DateTimeStyleWidth.Full).Should().Be("{1} 'kl'. {0}");
        nb.GetMonthNames(DateTimeNameContext.Format, DateTimeNameWidth.Wide)[0].Should().Be("januar");

        var zhHant = Data.GetLocale("zh-Hant");
        Pattern(zhHant, "hm").Should().Be("Bh:mm");
        zhHant.GetEraNames(DateTimeNameWidth.Abbreviated).ToArray().Should().Equal("西元前", "西元");

        var zhHantHk = Data.GetLocale("zh-Hant-HK");
        Pattern(zhHantHk, "yMd").Should().Be("d/M/y");
        Pattern(zhHantHk, "hm").Should().Be("ah:mm");
        zhHantHk.GetEraNames(DateTimeNameWidth.Abbreviated).ToArray().Should().Equal("公元前", "公元");
        zhHantHk.GetFieldDisplayName(DateTimeAppendField.Weekday).Should().Be("星期幾");
        Pattern(Data.GetLocale("zh-Hant-MO"), "MEd").Should().Be("d/M（E）");

        var ja = Data.GetLocale("ja");
        Pattern(ja, "Hm").Should().Be("H:mm");
        Pattern(ja, "hm").Should().Be("aK:mm");
        Pattern(ja, "yMMMEd").Should().Be("y年M月d日(E)");
        ja.AvailableFormats.Length.Should().Be(56);

        Data.GetLocale("ca-ES-valencia").GetMonthNames(DateTimeNameContext.Format, DateTimeNameWidth.Wide)[0].Should().Be("de gener");

        var esMx = Data.GetLocale("es-MX");
        Pattern(esMx, "yMMMEd").Should().Be("EEE, d 'de' MMM 'de' y");
        esMx.GetDateFormat(DateTimeStyleWidth.Short).Should().Be("dd/MM/yy");
        esMx.AvailableFormats.Length.Should().Be(61);

        var ko = Data.GetLocale("ko");
        ko.GetDateFormat(DateTimeStyleWidth.Short).Should().Be("yy. M. d.");
        ko.GetTimeFormat(DateTimeStyleWidth.Short).Should().Be("a h:mm");
    }

    [Test]
    public void TheAvailableFormatsAreInOrdinalOrderAndFoundBySkeleton()
    {
        var de = Data.GetLocale("de");
        var skeletons = de.AvailableFormats.ToArray().Select(e => e.Skeleton).ToList();
        skeletons.Should().BeInAscendingOrder(StringComparer.Ordinal);
        skeletons.Should().NotContain(s => s.Contains('Q') || s.Contains('w') || s.Contains('W') || s.Contains("-count-") || s.Contains("-alt-"));
        de.TryGetAvailableFormat("Hm", out var pattern).Should().BeTrue();
        pattern.Should().Be("HH:mm");
        de.TryGetAvailableFormat("yQQQ", out _).Should().BeFalse();
    }

    [Test]
    public void ALocaleIsBuiltOnceAndShared()
    {
        Data.GetLocale("fr").Should().BeSameAs(Data.GetLocale("fr-FR"));
        Data.GetLocale("fr-CA").Should().BeSameAs(Data.GetLocale("fr-CA"));
    }

    /// <summary>
    /// Resolving a tag reads the index only; a locale inflates its own language's block, the root's (which every
    /// locale's records are relative to) and a parent's in another language, and nothing else.
    /// </summary>
    [Test]
    public void OnlyTheLanguagesALocaleNeedsAreInflated()
    {
        var data = new DateTimePatternData(OpenResource);
        data.ResolveLocale("de-AT").Should().Be("de-AT");
        data.IsLanguageInflated("de").Should().BeFalse();
        data.IsLanguageInflated("und").Should().BeFalse();

        data.GetLocale("de-AT").GetMonthNames(DateTimeNameContext.Format, DateTimeNameWidth.Wide)[0].Should().Be("Jänner");
        data.IsLanguageInflated("de").Should().BeTrue();
        data.IsLanguageInflated("und").Should().BeTrue();
        data.IsLanguageInflated("en").Should().BeFalse();
        data.IsLanguageInflated("no").Should().BeFalse();

        data.GetLocale("nb");
        data.IsLanguageInflated("nb").Should().BeTrue();
        data.IsLanguageInflated("no").Should().BeTrue();
        data.IsLanguageInflated("en").Should().BeFalse();

        data.GetLocale("hi-Latn");
        data.IsLanguageInflated("hi").Should().BeTrue();
        data.IsLanguageInflated("en").Should().BeTrue();
        data.IsLanguageInflated("ja").Should().BeFalse();
    }

    /// <summary>
    /// Two engines may ask for the same language at the same moment; every caller gets the one instance that was
    /// published, whole.
    /// </summary>
    [Test]
    public async Task ConcurrentFirstUseOfOneLanguageHandsEveryCallerTheSameData()
    {
        const int Callers = 8;
        string[] tags = ["de-AT", "de-CH", "de", "de-LI"];
        var data = new DateTimePatternData(OpenResource);
        using var barrier = new Barrier(Callers);
        var results = new DateTimePatternLocale[Callers][];
        var callers = Enumerable.Range(0, Callers).Select(i => DedicatedThread.RunAsync(() =>
        {
            if (!barrier.SignalAndWait(TestBudgets.WedgeCeiling))
            {
                throw new TimeoutException("the callers never lined up");
            }

            results[i] = tags.Select(data.GetLocale).ToArray();
        })).ToArray();

        await Task.WhenAll(callers);

        for (var i = 1; i < Callers; i++)
        {
            for (var t = 0; t < tags.Length; t++)
            {
                results[i][t].Should().BeSameAs(results[0][t], "caller {0} asked for {1}", i, tags[t]);
            }
        }

        results[0][0].GetMonthNames(DateTimeNameContext.Format, DateTimeNameWidth.Wide)[0].Should().Be("Jänner");
        results[0][1].TryGetAvailableFormat("GyMEd", out var pattern).Should().BeTrue();
        pattern.Should().Be("E, MM.dd.Y G");
        data.IsLanguageInflated("en").Should().BeFalse();
    }

    private static string Pattern(DateTimePatternLocale locale, string skeleton)
    {
        locale.TryGetAvailableFormat(skeleton, out var pattern).Should().BeTrue("{0} has an availableFormats entry for {1}", locale.Locale, skeleton);
        return pattern!;
    }

    /// <summary>
    /// The field each skeleton letter stands for, with the hour split by cycle.
    /// </summary>
    private static HashSet<string> FieldsOf(string skeleton)
    {
        return skeleton.Select(c => c switch
        {
            'G' => "era",
            'y' or 'Y' => "year",
            'M' or 'L' => "month",
            'd' => "day",
            'E' or 'c' => "weekday",
            'a' or 'b' or 'B' => "dayPeriod",
            'h' or 'K' => "hour12",
            'H' or 'k' => "hour24",
            'm' => "minute",
            's' => "second",
            'S' => "fractionalSecondDigits",
            _ => "timeZoneName",
        }).ToHashSet();
    }

    private static void CheckPattern(string id, string name, string pattern, string extra, List<string> problems)
    {
        if (!TryGetPatternLetters(pattern, out var letters))
        {
            problems.Add($"{id}: {name} \"{pattern}\" has an unclosed quote");
            return;
        }

        if (letters.Length == 0 || letters.Any(c => !AllowedLetters.Contains(c) && !extra.Contains(c)))
        {
            problems.Add($"{id}: {name} \"{pattern}\" has the letters \"{letters}\"");
        }
    }

    private static void CheckJoin(string id, string name, string pattern, string placeholders, List<string> problems)
    {
        if (!TryGetPatternLetters(pattern, out var letters) || letters.Length > 0 || !pattern.Contains("{0}") || !pattern.Contains("{1}"))
        {
            problems.Add($"{id}: {name} \"{pattern}\"");
            return;
        }

        for (var i = pattern.IndexOf('{'); i >= 0; i = pattern.IndexOf('{', i + 1))
        {
            if (i + 2 >= pattern.Length || pattern[i + 2] != '}' || !placeholders.Contains(pattern[i + 1]))
            {
                problems.Add($"{id}: {name} \"{pattern}\" has an unexpected placeholder");
            }
        }
    }

    private static void CheckNames(string id, string name, ReadOnlySpan<string> names, int count, List<string> problems)
    {
        if (names.Length != count)
        {
            problems.Add($"{id}: {name} has {names.Length} entries");
            return;
        }

        foreach (var value in names)
        {
            if (string.IsNullOrEmpty(value))
            {
                problems.Add($"{id}: {name} has an empty entry");
                return;
            }
        }
    }

    private static string PatternLetters(string pattern)
    {
        TryGetPatternLetters(pattern, out var letters);
        return letters;
    }

    /// <summary>
    /// The unquoted ASCII letters of a CLDR pattern (https://www.unicode.org/reports/tr35/tr35-dates.html#Date_Format_Patterns);
    /// false for an unclosed quote.
    /// </summary>
    private static bool TryGetPatternLetters(string pattern, out string letters)
    {
        var builder = new StringBuilder();
        var quoted = false;
        for (var i = 0; i < pattern.Length; i++)
        {
            var c = pattern[i];
            if (c == '\'')
            {
                if (i + 1 < pattern.Length && pattern[i + 1] == '\'')
                {
                    i++;
                    continue;
                }

                quoted = !quoted;
                continue;
            }

            if (!quoted && ((c >= 'a' && c <= 'z') || (c >= 'A' && c <= 'Z')))
            {
                builder.Append(c);
            }
        }

        letters = builder.ToString();
        return !quoted;
    }

    private static int ReadVarint(byte[] bytes, ref int position)
    {
        var result = 0;
        for (var shift = 0; ; shift += 7)
        {
            var b = bytes[position++];
            result |= (b & 0x7F) << shift;
            if (b < 0x80)
            {
                return result;
            }
        }
    }

    private static string ReadString(byte[] bytes, ref int position)
    {
        var length = ReadVarint(bytes, ref position);
        var value = Encoding.UTF8.GetString(bytes, position, length);
        position += length;
        return value;
    }

    private static byte[] Inflate(byte[] file, int offset, int compressedLength, int rawLength)
    {
        using var inflate = new DeflateStream(new MemoryStream(file, offset, compressedLength), CompressionMode.Decompress);
        var raw = new byte[rawLength];
        var read = 0;
        while (read < raw.Length)
        {
            var count = inflate.Read(raw, read, raw.Length - read);
            count.Should().BePositive("the block inflates to the length the index records");
            read += count;
        }

        inflate.ReadByte().Should().Be(-1, "the block inflates to no more than the length the index records");
        return raw;
    }

    private static string Sha256(byte[] bytes)
    {
        using var sha = SHA256.Create();
        return BitConverter.ToString(sha.ComputeHash(bytes)).Replace("-", "").ToLowerInvariant();
    }
}
