<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="NUnit" />
    <PackageReference Include="NUnit3TestAdapter" />
    <PackageReference Include="GitHubActionsTestLogger" />
    <ProjectReference Include="../browser-comparison/BrowserComparison.csproj" />
    <Compile Include="../../Jint.Tests/TestFrameworkConventions.cs" Link="TestFrameworkConventions.cs" />
    <Using Include="NUnit.Framework" />
    <Using Remove="Acornima" />
    <Using Remove="Acornima.Ast" />
  </ItemGroup>
</Project>
