"""Generate typed parser lookups and reference cases from parser-lookups.json."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
import re
import sys

DIRECTORY = Path(__file__).resolve().parent
ROOT = DIRECTORY.parent.parent
sys.path.insert(0, str(DIRECTORY.parent / "Html"))
import generate_known_names as generator

IMPORTS = [
    "Jint.HtmlParser.Css",
    "Jint.HtmlParser.Css.Conditions",
    "Jint.HtmlParser.Css.Values",
    "Jint.HtmlParser.Css.Values.Colors",
    "Jint.HtmlParser.Css.Values.Math",
    "Jint.HtmlParser.Css.Values.Properties",
    "Jint.HtmlParser.Css.Values.Transforms",
    "static Jint.HtmlParser.Css.Selectors.CompiledSelector",
]


def entries(spec: dict, specs: list[dict]) -> dict[str, str]:
    if "entries" in spec:
        return spec["entries"]
    source = spec["source"]
    if source["kind"] == "lookup":
        return entries(next(item for item in specs if item["name"] == source["name"]), specs)
    if source["kind"] == "union":
        names = set(source["additional"])
        for name in source["lookups"]:
            names.update(entries(next(item for item in specs if item["name"] == name), specs))
        return dict.fromkeys(sorted(names), source["result"])
    text = (DIRECTORY.parent / source["file"]).read_text()
    if source["kind"] == "colors":
        matches = re.findall(r'\["([^"]+)"\]\s*=\s*(0x[0-9a-fA-F]+u)', text)
        if len(matches) != 148:
            raise ValueError("Review the named-color vocabulary before changing its size.")
        return dict(matches)
    if source["kind"] in ("property-families", "property-indices"):
        result = {}
        for family, names in re.findall(r'Add\(names, "([^"]+)", "([^"]+)"\)', text):
            for name in names.split():
                if name in result:
                    raise ValueError(f"Duplicate property obligation: {name}")
                result[name] = json.dumps(family)
        if len(result) != 433:
            raise ValueError("Review the pinned property catalog before changing its size.")
        if source["kind"] == "property-indices":
            names = set(result)
            for file in source["additionalFiles"]:
                metadata = (DIRECTORY.parent / file).read_text()
                names.update(re.findall(r'\b(?:Add|Shorthand)\("([^"]+)",', metadata))
            return {name: str(index) for index, name in enumerate(sorted(names))}
        return result
    raise ValueError(f"Unknown vocabulary source: {source}")


def header(namespace: str, tests: bool = False) -> list[str]:
    return [
        "// <auto-generated />",
        "// Generated by Jint.HtmlParser/Parsing/generate_parser_lookups.py. Do not edit.",
        "// Named-color constants: Copyright (c) 2026 World Wide Web Consortium.",
        "// CSS Color 4 https://drafts.csswg.org/css-color-4/; W3C Document License:",
        "// https://www.w3.org/copyright/document-license/",
        "#nullable enable",
        "using System;",
        "using System.Collections.Generic;",
        "using System.Buffers.Binary;",
        "using System.Runtime.CompilerServices;",
        "using System.Runtime.InteropServices;",
        *[f"using {name};" for name in (["Jint.HtmlParser"] if tests else []) + IMPORTS],
        "",
        f"namespace {namespace};",
        "",
    ]


def outputs() -> dict[Path, str]:
    specs = json.loads((DIRECTORY / "parser-lookups.json").read_text())
    source = header("Jint.HtmlParser")
    tests = header("Jint.Tests.HtmlParser.Parsing", tests=True)
    tests.extend([
        "internal static class ParserLookupCases",
        "{",
        "    internal static readonly ParserLookupCase[] All =",
        "    [",
    ])
    seen = set()
    for spec in specs:
        name = spec["name"]
        if not re.fullmatch(r"[A-Za-z_][A-Za-z0-9_]*", name) or name in seen:
            raise ValueError(f"Invalid or duplicate lookup: {name}")
        seen.add(name)
        values = entries(spec, specs)
        ignore_case = spec.get("ignoreCase", False)
        if "enum" in spec:
            source.extend([f"internal enum {spec['type']}", "{", "    Unknown,"])
            source.extend(f"    {name}," for name in spec["enum"])
            source.extend(["}", ""])
        source.extend(generator.emit_class(
            list(values), name, ignore_case=ignore_case, results=values,
            return_type=spec["type"], default_result=spec["default"], include_values=False))
        source.append("")
        tests.extend([
            f'        new("{name}", static input => {name}.Match(input),',
            f'            ({spec["type"]}) ({spec["default"]}), {str(ignore_case).lower()},',
            "            new Dictionary<string, object?>",
            "            {",
        ])
        for word, expression in values.items():
            tests.append(f"                [{json.dumps(word)}] = ({spec['type']}) ({expression}),")
        tests.extend(["            }),"])
    keyword_sets = [spec for spec in specs if "keywordSet" in spec]
    source.extend(["internal enum CssKeywordSet", "{", "    Empty,"])
    source.extend(f"    {spec['keywordSet']}," for spec in keyword_sets)
    source.extend(["}", "", "internal static class CssKeywordLookup", "{",
                   "    internal static string? Match(ReadOnlySpan<char> input, CssKeywordSet set) => set switch",
                   "    {", "        CssKeywordSet.Empty => null,"])
    source.extend(f"        CssKeywordSet.{spec['keywordSet']} => {spec['name']}.Match(input),"
                  for spec in keyword_sets)
    source.extend(["        _ => throw new ArgumentOutOfRangeException(nameof(set))", "    };", "}", ""])
    tests.extend(["    ];", "}", ""])
    return {
        DIRECTORY / "ParserLookups.g.cs": "\n".join(source),
        ROOT / "Jint.Tests.HtmlParser/Parsing/ParserLookupCases.g.cs": "\n".join(tests),
    }


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    for path, content in outputs().items():
        if args.check:
            if not path.exists() or path.read_text() != content:
                raise SystemExit(f"Stale generated lookup: {path}")
        else:
            path.write_text(content)
        print(path.name)


if __name__ == "__main__":
    main()
