using System.Collections.Immutable;
using System.Text;

namespace Jint.SourceGenerators.Interop;

/// <summary>
/// Emits the typed lanes for one annotated type, and the one registration entry point per assembly.
/// </summary>
/// <remarks>
/// Everything here is written against Jint's <b>public</b> surface only, because it is compiled in the
/// annotated type's own assembly. The MVP this replaces emitted a <c>Function</c> subclass with a
/// <c>protected internal override Call</c>, an assignment to the internal <c>_prototype</c> field and a read
/// of the internal <c>Engine.Realm</c> — three things that compile only inside Jint or inside an assembly on
/// its <c>InternalsVisibleTo</c> list, which is why the MVP's generated code had never been compiled by a
/// third party.
/// </remarks>
internal static class JsAccessibleEmitter
{
    private const string JsValue = "global::Jint.Native.JsValue";
    private const string Builder = "global::Jint.Runtime.Interop.JsAccessibleTypeBuilder";
    private const string Registry = "global::Jint.Runtime.Interop.JsAccessibleRegistry";
    private const string GeneratedNamespace = "Jint.Generated";

    private const string Header = """
        // <auto-generated/>
        #nullable enable
        #pragma warning disable CS0219, CS8073, CS8600, CS8601, CS8602, CS8603, CS8604, CS8618, CS8625

        """;

    public static string EmitType(AccessibleTypeDefinition definition)
    {
        var sb = new StringBuilder(4096);
        sb.Append(Header);
        sb.AppendLine();
        sb.Append("namespace ").AppendLine(GeneratedNamespace);
        sb.AppendLine("{");
        sb.Append("    internal static class JsAccessible_").AppendLine(definition.SafeId);
        sb.AppendLine("    {");

        sb.AppendLine("        internal static void Register()");
        sb.AppendLine("        {");
        sb.Append("            ").Append(Registry).Append(".Register(typeof(").Append(definition.FullyQualifiedName).AppendLine("), AddMembers);");
        sb.AppendLine("        }");
        sb.AppendLine();

        sb.Append("        private static void AddMembers(").Append(Builder).AppendLine(" builder)");
        sb.AppendLine("        {");
        foreach (var member in definition.Members)
        {
            sb.AppendLine("            builder.AddMember(");
            sb.Append("                \"").Append(member.Name).AppendLine("\",");
            sb.Append("                typeof(").Append(member.TypeFullName).AppendLine("),");
            sb.Append("                ").Append(member.CanRead && member.Kind.HasTypedRead() ? "Read_" + member.Name : "null").AppendLine(",");
            sb.Append("                ").Append(member.CanRead ? "ReadBoxed_" + member.Name : "null").AppendLine(",");
            sb.Append("                ").Append(member.CanWrite && member.Kind.HasTypedWrite() ? "Write_" + member.Name : "null").AppendLine(",");
            sb.Append("                ").Append(member.CanWrite ? "WriteBoxed_" + member.Name : "null").AppendLine(");");
        }

        foreach (var method in definition.Methods)
        {
            sb.Append("            builder.AddMethod(\"").Append(method.Name).Append("\", ")
                .Append(method.ParameterCount.ToString(System.Globalization.CultureInfo.InvariantCulture))
                .Append(", Invoke_").Append(method.Name).AppendLine(");");
        }

        sb.AppendLine("        }");

        foreach (var member in definition.Members)
        {
            EmitMemberLanes(sb, definition, member);
        }

        foreach (var method in definition.Methods)
        {
            EmitMethodLane(sb, definition, method);
        }

        sb.AppendLine("    }");
        sb.AppendLine("}");
        return sb.ToString();
    }

    /// <summary>
    /// The per-assembly entry point. Registration is an explicit call rather than a
    /// <c>[ModuleInitializer]</c>: the attribute does not exist on <c>net472</c> or <c>netstandard2.0</c>
    /// without a polyfill the consumer has no reason to have, and a registration that happens because an
    /// assembly loaded is one a host can neither see nor test.
    /// </summary>
    public static string EmitRegistration(string rootNamespace, ImmutableArray<AccessibleTypeDefinition> definitions)
    {
        var sb = new StringBuilder(2048);
        sb.Append(Header);
        sb.AppendLine();

        var hasNamespace = rootNamespace.Length > 0;
        var indent = hasNamespace ? "    " : string.Empty;
        if (hasNamespace)
        {
            sb.Append("namespace ").AppendLine(rootNamespace);
            sb.AppendLine("{");
        }

        sb.Append(indent).AppendLine("/// <summary>");
        sb.Append(indent).AppendLine("/// Registers this assembly's [Jint.JsAccessible] types with the Jint engine. Call it once, during");
        sb.Append(indent).AppendLine("/// startup and before the first engine resolves a member of an annotated type; repeat calls do nothing.");
        sb.Append(indent).AppendLine("/// </summary>");
        sb.Append(indent).AppendLine("public static class JsAccessibleRegistration");
        sb.Append(indent).AppendLine("{");
        sb.Append(indent).AppendLine("    private static int _registered;");
        sb.AppendLine();
        sb.Append(indent).AppendLine("    public static void RegisterAll()");
        sb.Append(indent).AppendLine("    {");
        sb.Append(indent).AppendLine("        if (global::System.Threading.Interlocked.Exchange(ref _registered, 1) != 0)");
        sb.Append(indent).AppendLine("        {");
        sb.Append(indent).AppendLine("            return;");
        sb.Append(indent).AppendLine("        }");
        sb.AppendLine();

        foreach (var definition in definitions)
        {
            sb.Append(indent).Append("        global::").Append(GeneratedNamespace).Append(".JsAccessible_")
                .Append(definition.SafeId).AppendLine(".Register();");
        }

        sb.Append(indent).AppendLine("    }");
        sb.Append(indent).AppendLine("}");

        if (hasNamespace)
        {
            sb.AppendLine("}");
        }

        return sb.ToString();
    }

    private static void EmitMemberLanes(StringBuilder sb, AccessibleTypeDefinition definition, AccessibleMember member)
    {
        var receiver = "((" + definition.FullyQualifiedName + ") target)";

        if (member.CanRead)
        {
            if (member.Kind.HasTypedRead())
            {
                sb.AppendLine();
                sb.Append("        private static ").Append(JsValue).Append(" Read_").Append(member.Name).AppendLine("(object target)");
                sb.Append("            => ").Append(TypedRead(receiver + "." + member.Name, member.Kind)).AppendLine(";");
            }

            sb.AppendLine();
            sb.Append("        private static object? ReadBoxed_").Append(member.Name).AppendLine("(object target)");
            sb.Append("            => ").Append(receiver).Append('.').Append(member.Name).AppendLine(";");
        }

        if (!member.CanWrite)
        {
            return;
        }

        if (member.Kind.HasTypedWrite())
        {
            sb.AppendLine();
            sb.Append("        private static bool Write_").Append(member.Name).Append("(object target, ").Append(JsValue).AppendLine(" value)");
            sb.AppendLine("        {");
            EmitTypedWriteBody(sb, receiver + "." + member.Name, member.Kind);
            sb.AppendLine("        }");
        }

        sb.AppendLine();
        sb.Append("        private static void WriteBoxed_").Append(member.Name).AppendLine("(object target, object? value)");
        sb.Append("            => ").Append(receiver).Append('.').Append(member.Name).Append(" = ");

        if (member.IsValueType)
        {
            // The runtime binder writes default(T) for a null handed to a value-type member rather than
            // refusing it, so a plain unbox here would be the one place a generated write could throw where
            // the reflected one succeeded.
            sb.Append("value is null ? default(").Append(member.TypeFullName).Append(") : ");
        }

        sb.Append('(').Append(member.TypeFullName).AppendLine(") value!;");
    }

    /// <summary>
    /// Reproduces <c>CompiledMemberAccessor.BuildJsValueConversion</c>: the public implicit operators produce
    /// the same instances <c>DefaultObjectConverter</c> does, and a null reference becomes <c>JsValue.Null</c>.
    /// </summary>
    private static string TypedRead(string access, AccessibleValueKind kind)
    {
        if (kind == AccessibleValueKind.JsValue || kind == AccessibleValueKind.JsValueSubtype)
        {
            return access + " ?? (" + JsValue + ") " + JsValue + ".Null";
        }

        // int / long / double / bool / string — the string operator maps null to JsValue.Null internally
        return "(" + JsValue + ") " + access;
    }

    /// <summary>
    /// Reproduces <c>CompiledMemberAccessor.BuildValueBinding</c>: an exact JavaScript type test, then the
    /// typed write; anything else returns false having written nothing, so the caller runs the full
    /// conversion instead. The bounds are the same ones, spelled the same way — <c>Math.Floor(d) == d</c> is
    /// the integral test because it is a JIT intrinsic where <c>d % 1 == 0</c> lowers to a call.
    /// </summary>
    private static void EmitTypedWriteBody(StringBuilder sb, string access, AccessibleValueKind kind)
    {
        switch (kind)
        {
            case AccessibleValueKind.JsValue:
                // matches ReflectionAccessor.SetValue's `_memberType == typeof(JsValue)` branch: assigned
                // as-is, JsValue.Null and JsValue.Undefined included
                sb.Append("            ").Append(access).AppendLine(" = value;");
                sb.AppendLine("            return true;");
                return;

            case AccessibleValueKind.String:
                DeclineUnless(sb, "global::Jint.Native.JsString");
                sb.Append("            ").Append(access).AppendLine(" = value.ToString();");
                sb.AppendLine("            return true;");
                return;

            case AccessibleValueKind.Boolean:
                DeclineUnless(sb, "global::Jint.Native.JsBoolean");
                sb.Append("            ").Append(access).AppendLine(" = global::Jint.JsValueExtensions.AsBoolean(value);");
                sb.AppendLine("            return true;");
                return;
        }

        DeclineUnless(sb, "global::Jint.Native.JsNumber");
        sb.AppendLine("            var d = global::Jint.JsValueExtensions.AsNumber(value);");

        if (kind == AccessibleValueKind.Double)
        {
            sb.Append("            ").Append(access).AppendLine(" = d;");
            sb.AppendLine("            return true;");
            return;
        }

        // (double) long.MaxValue rounds up to 2^63, so the upper bound must be exclusive for long.
        var below = kind == AccessibleValueKind.Int32 ? "-2147483648D" : "-9223372036854775808D";
        var above = kind == AccessibleValueKind.Int32 ? "d > 2147483647D" : "d >= 9223372036854775808D";

        sb.Append("            if (double.IsNaN(d) || double.IsInfinity(d) || global::System.Math.Floor(d) != d || d < ")
            .Append(below).Append(" || ").Append(above).AppendLine(")");
        sb.AppendLine("            {");
        sb.AppendLine("                return false;");
        sb.AppendLine("            }");
        sb.AppendLine();
        sb.Append("            ").Append(access).Append(" = (")
            .Append(kind == AccessibleValueKind.Int32 ? "int" : "long").AppendLine(") d;");
        sb.AppendLine("            return true;");
    }

    private static void DeclineUnless(StringBuilder sb, string jsType)
    {
        sb.Append("            if (!(value is ").Append(jsType).AppendLine("))");
        sb.AppendLine("            {");
        sb.AppendLine("                return false;");
        sb.AppendLine("            }");
        sb.AppendLine();
    }

    private static void EmitMethodLane(StringBuilder sb, AccessibleTypeDefinition definition, AccessibleMethod method)
    {
        sb.AppendLine();
        sb.Append("        private static ").Append(JsValue).Append(" Invoke_").Append(method.Name)
            .Append("(global::Jint.Engine engine, object target, ").Append(JsValue).AppendLine("[] arguments)");
        sb.AppendLine("        {");

        var call = new StringBuilder();
        call.Append("((").Append(definition.FullyQualifiedName).Append(") target).").Append(method.Name).Append('(');
        for (var i = 0; i < method.ParameterCount; i++)
        {
            if (i > 0)
            {
                call.Append(", ");
            }

            // The engine has already refused any other argument count, exactly as the reflected path does for
            // a single candidate with no optional parameters.
            call.Append("arguments[").Append(i.ToString(System.Globalization.CultureInfo.InvariantCulture)).Append(']');
        }

        call.Append(')');

        if (method.ReturnsVoid)
        {
            sb.Append("            ").Append(call).AppendLine(";");
            // MethodInfoFunction converts even a void return, and JsValue.FromObjectWithType maps a null
            // result to JsValue.Null rather than to undefined. Calling it is how that stays true here.
            sb.Append("            return ").Append(JsValue).AppendLine(".FromObjectWithType(engine, null, typeof(void));");
        }
        else
        {
            sb.Append("            var result = ").Append(call).AppendLine(";");
            sb.Append("            return ").Append(JsValue).Append(".FromObjectWithType(engine, result, typeof(")
                .Append(method.ReturnTypeFullName).AppendLine("));");
        }

        sb.AppendLine("        }");
    }
}
